### ISSUE TITLE
Is SRX models supported with load_merge_candidate()?

### ISSUE THREAD

**Issue by GarrettStrahan** [napalm-automation/napalm#1017]
### Description of Issue/Question
Is device.load_merge_candidate() supported with the SRX models? I get napalm to do a configuration change with the following code (Don't worry I don't care if you have this password, this firewall SRX210 is not supporting any nodes and I will alter the password at a later date):

from napalm import get_network_driver
driver = get_network_driver('junos')
device = driver('10.0.0.5', 'root', 'FIreJuniper44$')
device.open()
device.load_merge_candidate(config="set interfaces lo0 unit 0 family inet address 1.1.1.1/24")
device.commit_config()
device.close()

This adds a loopback0 interface but does not add the ip address.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### napalm version
latest napalm version for Wednesday July 10, 2019
2.4.0 release2

### Network operating system version
version 12.1X46-D67;

### Steps to Reproduce the Issue
see code above

### Error Traceback
Traceback (most recent call last):
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\device.py", line 777, in execute
    ignore_warning=ignore_warning)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\decorators.py", line 169, in wrapper
    raise ex
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\device.py", line 1339, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\ncclient\manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\ncclient\operations\third_party\juniper\rpc.py", line 49, in request
    return self._request(rpc)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\ncclient\operations\rpc.py", line 349, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: 
configuration database modified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\utils\config.py", line 565, in lock
    self.rpc.lock_configuration()
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\device.py", line 797, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: configuration database modified)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\napalm\junos\junos.py", line 144, in _lock
    self.device.cu.lock()
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\jnpr\junos\utils\config.py", line 568, in lock
    raise LockError(rsp=err.rsp)
jnpr.junos.exception.LockError: LockError(severity: error, bad_element: None, message: configuration database modified)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/garre/PycharmProjects/NAPALM_Testing/configuration.py", line 14, in <module>
    device.load_merge_candidate(config="set interfaces lo0 unit 0 family inet address 1.1.1.1/24")
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\napalm\junos\junos.py", line 252, in load_merge_candidate
    self._load_candidate(filename, config, False)
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\napalm\junos\junos.py", line 224, in _load_candidate
    self._lock()
  File "C:\Users\garre\NAPALM_Testing\lib\site-packages\napalm\junos\junos.py", line 147, in _lock
    raise LockError(py23_compat.text_type(jle))
napalm.base.exceptions.LockError: LockError(severity: error, bad_element: None, message: configuration database modified)

Process finished with exit code 1

**Comment by GarrettStrahan** [comment]
Figured out what was wrong. I was connected at the same time with an SSH session, so this locked it out. Closing issue.
