### ISSUE TITLE
SyntaxError when using key_file optional_arg in CLI

### ISSUE THREAD

**Issue by thugcee** [napalm-automation/napalm#1027]
### Description of Issue/Question

When I try to connect via CLI `napalm` tool using ssh key I get `SyntaxError: invalid syntax` exception.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x ] Yes
- [ ] No

### napalm version

```
napalm                2.4.0
napalm-base           1.0.0
napalm-ios            0.8.1
napalm-junos          0.12.1
```

### Steps to Reproduce the Issue

```
$ napalm --user SOMEUSER --password None --vendor junos --optional_args 'key_file=/path-to/rsa_key' --debug ex-aci call get_facts
```

### Error Traceback

```
2019-07-31 14:56:05,332 - napalm - DEBUG - Starting napalm's debugging tool
2019-07-31 14:56:05,332 - napalm - DEBUG - Gathering napalm packages
2019-07-31 14:56:05,400 - napalm - DEBUG - napalm-base==1.0.0
2019-07-31 14:56:05,400 - napalm - DEBUG - napalm-ios==0.8.1
2019-07-31 14:56:05,400 - napalm - DEBUG - napalm-junos==0.12.1
2019-07-31 14:56:05,400 - napalm - DEBUG - napalm==2.4.0
2019-07-31 14:56:05,400 - napalm - DEBUG - get_network_driver - Calling with args: ('junos',), {}
2019-07-31 14:56:05,521 - napalm - DEBUG - get_network_driver - Successful
Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/napalm_base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/usr/local/lib/python3.6/dist-packages/napalm_base/clitools/cl_napalm.py", line 252, in run_tests
    optional_args = helpers.parse_optional_args(args.optional_args)
  File "/usr/local/lib/python3.6/dist-packages/napalm_base/clitools/helpers.py", line 125, in parse_optional_args
    for x in optional_args.split(',')}
  File "/usr/local/lib/python3.6/dist-packages/napalm_base/clitools/helpers.py", line 125, in <dictcomp>
    for x in optional_args.split(',')}
  File "/usr/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    /path-to/rsa_key
    ^
SyntaxError: invalid syntax

```

**Comment by carlniger** [comment]
`--optional_args "key_file='/Users/carl/.ssh/carl@home'"`

Looks like it should do the trick for ya. Does that work?

**Comment by thugcee** [comment]
Yes, it does. Thank you.
