### ISSUE TITLE
napalm.get not working for Arista EOS( Socket error during eAPI connection)

### ISSUE THREAD

**Issue by netwninja** [napalm-automation/napalm#1058]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### Setup

napalm server(Ubuntu 16.0.4) ---------Arista (EOS)

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
root@napalm:~# pip freeze | grep napalm
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm==2.4.0
napalm-base==1.0.0
napalm-eos==0.6.1
napalm-ios==0.8.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
EOS-A#show version 
Arista vEOS
Hardware version:    
Serial number:       
System MAC address:  5000.002f.d8fe

Software image version: 4.21.1.1F
Architecture:           i386
Internal build version: 4.21.1.1F-10146868.42111F
Internal build ID:      ed3973a9-79db-4acc-b9ac-19b9622d23e2

Uptime:                 0 weeks, 0 days, 1 hours and 12 minutes
Total memory:           2016668 kB
Free memory:            1145792 kB

root@napalm:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```

### Steps to Reproduce the Issue

Ran the below script 

```
import json
from napalm.base import get_network_driver
driver = get_network_driver('eos')
dev = driver(hostname='r1', username='ansible',
             password='ansible123')
dev.open()
dev_info = dev.get_facts
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))


```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "eos1.py", line 6, in <module>
    dev.open()
  File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [Errno 111] Connection refused

```

**Comment by mirceaulinic** [comment]
@netwninja check again https://github.com/napalm-automation/napalm#faq, and make sure you are able to connect to the device. See also https://napalm.readthedocs.io/en/latest/support/eos.html, and the Arista documentation on how to enable the HTTP API.

**Comment by netwninja** [comment]
I have checked specifically.  I know the API HTTP is enabled on the Arista switch. We should further investigate that how it's broken now

The Arista API was enabled as we can see in the below output. Also, it's working fine when i try to access the Arista switch directly via browser

```
EOS-A#show management api http-commands 
Enabled:            Yes
HTTPS server:       running, set to use port 443
HTTP server:        shutdown, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               default
Hits:               9
Last hit:           28820 seconds ago
Bytes in:           1169
Bytes out:          7970
**Requests:           3**
**Commands:           3**
Duration:           0.232 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User          Requests       Bytes in       Bytes out    Last hit          
------------- -------------- -------------- --------------- ----------------- 
   ansible       3              1169           7970         28820 seconds ago 

URLs                                   
-------------------------------------- 
Ethernet2   : https://192.168.10.1:443 
Management1 : https://10.0.0.165:443  
```

Now i went ahead and enabled HTTP, same results

Arista output

```
EOS-A#show management api http-commands
Enabled:            Yes
HTTPS server:       shutdown, set to use port 443
HTTP server:        running, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               default
Hits:               9
Last hit:           29353 seconds ago
Bytes in:           1169
Bytes out:          7970
Requests:           3
Commands:           3
Duration:           0.232 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User          Requests       Bytes in       Bytes out    Last hit          
------------- -------------- -------------- --------------- ----------------- 
   ansible       3              1169           7970         29353 seconds ago 

URLs                                 
------------------------------------ 
Ethernet2   : http://192.168.10.1:80 
Management1 : http://10.0.0.165:80   

```

NAPALM COMMAND OUTPUT FROM LINUX SERVER

```
napalm --vendor eos --user ansible --password ansible123 --optional_args 'port=80, config_lock=False' eos-a call get_facts
No handlers could be found for logger "pyeapi.eapilib"
2019-10-07 14:24:36,940 - napalm - ERROR - open - Failed: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

================= Traceback =================

Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 260, in run_tests
    call_open_device(device)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 192, in call_open_device
    return device.open()
  File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
root@napalm:~# 
```

OUTPUT FROM STACKSTORM

```
st2 run napalm.get_lldp_neighbors hostname=EOS-A port=80

.
id: 5d9b48b491b27731089848b0
status: failed
parameters: 
  hostname: EOS-A
  port: '80'
result: 
  exit_code: 1
  result: None
  stderr: "No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_lldp_neighbors.py", line 10, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 47, in __enter__
    self.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
"
  stdout: ''
```

**Comment by mirceaulinic** [comment]
You've configured only the HTTP server (HTTPS is shutdown). NAPALM is using by default HTTPS, otherwise you'll have to set the optional arg `transport` accordingly: https://napalm.readthedocs.io/en/latest/support/index.html#the-transport-argument.

**Comment by netwninja** [comment]
If you look at the first output, HTTPS was enabled and i was getting the same error. 
Let me try transport argument and update the results accordingly. 

```
HTTPS server:       running, set to use port 443
HTTP server:        shutdown, set to use port 80
```

**Comment by netwninja** [comment]
As per the links you shared i went ahead and used "transport" as an optional argument and still no luck. 

ARISTA API OUTPUT 

```
EOS-A#show management api http-commands 
Enabled:            Yes
HTTPS server:       running, set to use port 443
HTTP server:        running, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               default
Hits:               16
Last hit:           178 seconds ago
Bytes in:           2494
Bytes out:          15269
Requests:           10
Commands:           21
Duration:           4.636 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User          Requests       Bytes in       Bytes out    Last hit        
------------- -------------- -------------- --------------- --------------- 
   ansible       10             2494           15269        178 seconds ago 

URLs                                   
-------------------------------------- 
Ethernet2   : https://192.168.10.1:443 
Ethernet2   : http://192.168.10.1:80   
Management1 : https://10.0.0.165:443   
Management1 : http://10.0.0.165:80     

EOS-A#

```
For the below python script i tried https and http , no luck. 

```python
import json
from napalm.base import get_network_driver
optional_args = {'transport': 'https'}
driver = get_network_driver('eos')
dev = driver(hostname='r1', username='ansible', password='ansible123', optional_args=optional_args)
dev.open()
dev_info = dev.get_facts
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))
```

TRACEBACK 

```
root@napalm:~# python eos1.py 
No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "eos1.py", line 6, in <module>
    dev.open()
  File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [Errno 111] Connection refused
root@napalm:~# 

```

The above API request is not even hitting or reaching the Arista switch because i don't see anything in tcpdump from BASH on Arista. 

There is no reach ability issue between NAPALM server and Arista switch. 

FROM NAPALM SERVER 

```
root@napalm:~# ping 10.0.0.165
PING 10.0.0.165 (10.0.0.165) 56(84) bytes of data.
64 bytes from 10.0.0.165: icmp_seq=1 ttl=64 time=3.43 ms
64 bytes from 10.0.0.165: icmp_seq=2 ttl=64 time=2.43 ms
64 bytes from 10.0.0.165: icmp_seq=3 ttl=64 time=1.87 ms
64 bytes from 10.0.0.165: icmp_seq=4 ttl=64 time=2.87 ms
64 bytes from 10.0.0.165: icmp_seq=5 ttl=64 time=3.98 ms
64 bytes from 10.0.0.165: icmp_seq=6 ttl=64 time=2.46 ms
64 bytes from 10.0.0.165: icmp_seq=7 ttl=64 time=3.15 ms
64 bytes from 10.0.0.165: icmp_seq=8 ttl=64 time=2.11 ms
^C
--- 10.0.0.165 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7010ms
rtt min/avg/max/mdev = 1.874/2.792/3.986/0.665 ms
root@napalm:~# 
root@napalm:~# 
root@napalm:~# host eos-a
eos-a.homelab1.com has address 10.0.0.165
root@napalm:~# 

```
To me it looks like some SSL issue locally on the server.  However, it should work via Port 80. But that's also not working.

**Comment by mirceaulinic** [comment]
In the snippet you provided, you used `hostname='r1'`. Have you also tried with `hostname='eos-a'`, or `eos-a.homelab1.com` or with the IP address?

**Comment by adrianchi** [comment]
Hi. I am just following your case to learn. Could you try the tcpdump on your server just to see if something is getting out to the arista device? With the execution of napalm and then with a telnet to the http/https ports. I would say it Will not work anyway, but at least it would give you the final prove if it is network related of software server side.

Adrián.-

**Comment by netwninja** [comment]
@mirceaulinic Thanks for catching the host name mistake.It's working fine now. I have tested it without optional argument and now seeing the expected results.

**Comment by netwninja** [comment]
Also, it seems HTTPS is enabled by default on Arista EOS under API section. All, we need to do is just "no shut"

**Comment by netwninja** [comment]
```
root@napalm:~# python eos2.py 
{
    "fqdn": "EOS-A", 
    "hostname": "EOS-A", 
    "interface_list": [
        "Ethernet1", 
        "Ethernet2", 
        "Ethernet3", 
        "Management1"
    ], 
    "model": "vEOS", 
    "os_version": "4.21.1.1F-10146868.42111F", 
    "serial_number": "", 
    "uptime": 174989, 
    "vendor": "Arista"
}
root@napalm:~# 
root@napalm:~# 
root@napalm:~# 
root@napalm:~# ssh ansible@eos-a
Password: 
Last login: Wed Oct  9 03:19:31 2019 from 10.0.0.119
Warning: the following filesystems have less than 10% free space left:
tmpfs                (on /var/core)      0% (0 Available)
tmpfs                (on /var/log)      0% (0 Available)
Please remove configuration such as tracing and clean up the space.
EOS-A#show run section managment
EOS-A#show run section management
interface Management1
   speed forced 25gfull
   ip address dhcp
   ipv6 enable
   ipv6 address auto-config
   ipv6 nd ra rx accept default-route
!
management api http-commands
   no shutdown
EOS-A#

```

**Comment by netwninja** [comment]
Thanks again .. It was a good learning experience.
