### ISSUE TITLE
naplam.get_route_to() not working on EOS:failed to detect a valid IP address from u'' 

### ISSUE THREAD

**Issue by netwninja** [napalm-automation/napalm#1069]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup

napalm-server-------vEOS

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
pip freeze | grep napalm
napalm==2.5.0
napalm-base==1.0.0
napalm-eos==0.6.1
napalm-ios==0.8.1
napalm-panos==0.5.2
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
vEOS-A#show version | in image
Software image version: 4.22.2F
```

### Steps to Reproduce the Issue
Use the below script 

```
# cat eos2.py 
import json
from napalm import get_network_driver
#optional_args = {'transport': 'https'}
driver = get_network_driver('eos')
dev = driver(hostname='veos-a', username='ansible', password='ansible123')
dev.open()
dev_info = dev.get_route_to(u'3.3.3.3/32')
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "eos2.py", line 7, in <module>
    dev_info = dev.get_route_to(u'3.3.3.3/32')
  File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 1258, in get_route_to
    .get("peerAddr", "")
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/helpers.py", line 330, in ip
    addr_obj = IPAddress(addr)
  File "/usr/local/lib/python2.7/dist-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from u''

```

### JSON output from Arista vEOS

```
vEOS-A#show ip route 3.3.3.3 | json
{
    "vrfs": {
        "default": {
            "routes": {
                "3.3.3.3/32": {
                    "kernelProgrammed": true,
                    "directlyConnected": false,
                    "routeAction": "forward",
                    "routeLeaked": false,
                    "vias": [
                        {
                            "interface": "Ethernet1",
                            "nexthopAddr": "172.16.10.1"
                        }
                    ],
                    "metric": 0,
                    "hardwareProgrammed": true,
                    "routeType": "eBGP",
                    "preference": 200
                }
            },
            "allRoutesProgrammedKernel": true,
            "routingDisabled": false,
            "allRoutesProgrammedHardware": true,
            "defaultRouteState": "notSet"
        }
    }
}

```

**Comment by netwninja** [comment]
### show ip route output from Arista vEOS 

```
vEOS-A#show ip route 3.3.3.3/32 detail

VRF: default
Codes: C - connected, S - static, K - kernel, 
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B - BGP, B I - iBGP, B E - eBGP,
       R - RIP, I L1 - IS-IS level 1, I L2 - IS-IS level 2,
       O3 - OSPFv3, A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route, V - VXLAN Control Service,
       DH - DHCP client installed default route, M - Martian,
       DP - Dynamic Policy Route, L - VRF Leaked

 B E      3.3.3.3/32 [200/0] via 172.16.10.1, Ethernet1


```

**Comment by netwninja** [comment]
### show ip route 3.3.3.3/32 detail | json 

```
vEOS-A#show ip route 3.3.3.3/32 detail | json
{
    "vrfs": {
        "default": {
            "routes": {
                "3.3.3.3/32": {
                    "kernelProgrammed": true,
                    "directlyConnected": false,
                    "routeAction": "forward",
                    "routeLeaked": false,
                    "vias": [
                        {
                            "interface": "Ethernet1",
                            "nexthopAddr": "172.16.10.1"
                        }
                    ],
                    "metric": 0,
                    "hardwareProgrammed": true,
                    "routeType": "eBGP",
                    "preference": 200
                }
            },
            "allRoutesProgrammedKernel": true,
            "routingDisabled": false,
            "allRoutesProgrammedHardware": true,
            "defaultRouteState": "notSet"
        }
    }
}

```

**Comment by malanovo** [comment]
This issue hit me as well, I have created a patch and submitted a pull request for it.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm/pull/1346.
