### ISSUE TITLE
socket.timeout when trying to merge configuration on IOS-XE (12 minutes)

### ISSUE THREAD

**Issue by smaxx1337** [napalm-automation/napalm#1110]
### Description of Issue/Question

When trying to deploy a big configuration a Cisco IOS-XE router, it times out after a long time. SCP is enabled on the router. Is this a general bug or can I somewhere increase the timeout value from 12 minutes to 60 minutes? (idk)

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS XE Software, Version 16.09.04
```

### Steps to Reproduce the Issue

Use a big config that you want to merge (The config I want to merge is about 2.1 MB big and has 39750 lines.) Here is my python code:

```
import napalm

driver = napalm.get_network_driver("ios")

device = driver(
    hostname="NOPE",
    username="NOPE",
    password="NOPE",
    optional_args={'port':1234, 'secret':'NOPE', 'inline_transfer':'True', 'keepalive':300}
)

device.open()

device.load_merge_candidate(filename='routerconfig.txt')
print(device.compare_config())
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "napalm_test.py", line 16, in <module>
    device.load_merge_candidate(filename='routerconfig.txt')
  File "/usr/lib/python3.6/site-packages/napalm/ios/ios.py", line 319, in load_merge_candidate
    file_system=self.dest_file_system,
  File "/usr/lib/python3.6/site-packages/napalm/ios/ios.py", line 279, in _load_candidate_wrapper
    file_system=file_system,
  File "/usr/lib/python3.6/site-packages/napalm/ios/ios.py", line 601, in _inline_tcl_xfer
    TransferClass=InLineTransfer,
  File "/usr/lib/python3.6/site-packages/napalm/ios/ios.py", line 692, in _xfer_file
    transfer.transfer_file()
  File "/usr/lib/python3.6/site-packages/netmiko/scp_handler.py", line 304, in transfer_file
    self.put_file()
  File "/usr/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 198, in put_file
    self.ssh_ctl_chan.write_channel(file_contents)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 422, in write_channel
    self._write_channel(out_data)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 384, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 1199, in _send
    size = self._wait_for_send_window(size)
  File "/usr/lib/python3.6/site-packages/paramiko/channel.py", line 1322, in _wait_for_send_window
    raise socket.timeout()
socket.timeout
```

Update: Also tested with inline_transfer: False. The VTY is 120 minutes and 0 seconds. (exec-timeout 120 0)

**Comment by Toluk** [comment]
Hello.

How did you resolve the issue ?
I seem to have the same one, dont know where to start.

**Comment by ktbyers** [comment]
@Toluk What is your VTY timeout set to?

Also does the user you are connecting with have privilege level 15 directly (i.e. no separate enable call). If not, then you will need to use inline_transfer=True.
