### ISSUE TITLE
Install error using 'python setup.py install'

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#114]
Started off with blank virtualenv
Did 'pip install -r requirements.txt' to install dependencies
Then did 'python setup.py install'...install completed without an issue.

Tried to load:

```
>>> from napalm import get_network_driver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.40-py2.7.egg/napalm/__init__.py", line 17, in <modul
    from junos import JunOSDriver
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.40-py2.7.egg/napalm/junos.py", line 17, in <module>
    from utils import junos_views
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.40-py2.7.egg/utils/junos_views.py", line 7, in <modu
    globals().update(loadyaml(_YAML_))
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/jnpr/junos/factory/__init__.py", line 33, in loadyaml
    return FactoryLoader().load(yaml.load(open(path, 'r')))
IOError: [Errno 2] No such file or directory: '/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.40-py2.7.egg/
```

I can fix the problem if I copy the 'junos_views.yml' file into the ./site-packages/napalm-0.40-py2.7.egg/utils directory.

There is no issue if I do 'pip install napalm', it works without an issue (the ./utils directory doesn't exist in this case).

**Comment by dbarrosop** [comment]
Hello Kirk,
thanks for reporting this issue. Looks like some namespace issue that triggers under some weird circumstances. I will try to fix it this week.

Thanks!
David

**Comment by dbarrosop** [comment]
@ktbyers Could you check if you have the same issue with napalm 0.50, please?

Thanks!

**Comment by ktbyers** [comment]
I still get this error (clean install of napalm using 'python setup.py install')

$ python
Python 2.7.10 (default, Dec  8 2015, 18:25:23) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.50-py2.7.egg/napalm/__init__.py", line 17, in <module>
    from junos import JunOSDriver
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.50-py2.7.egg/napalm/junos.py", line 17, in <module>
    from napalm.utils import junos_views
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.50-py2.7.egg/napalm/utils/junos_views.py", line 7, in <module>
    globals().update(loadyaml(_YAML_))
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/jnpr/junos/factory/__init__.py", line 33, in loadyaml
    return FactoryLoader().load(yaml.load(open(path, 'r')))
IOError: [Errno 2] No such file or directory: '/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.50-py2.7.egg/napalm/utils/junos_views.yml'

This is using the napalm 0.50 code release.

**Comment by dbarrosop** [comment]
Found the issue, while moving files around to fix the namespace issue I forgot to update the Manifest.in... Should be fixed now. Try with the version 0.50.1 and let me know if it works now, please.

Thanks!

**Comment by smnmtzgr** [comment]
Same problem for me at 0.51.0

>>> from napalm import get_network_driver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/__init__.py", line 17, in <module>
  File "/usr/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/junos.py", line 17, in <module>
  File "/usr/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/utils/junos_views.py", line 7, in <module>
  File "/usr/lib/python2.7/site-packages/junos_eznc-1.3.1-py2.7.egg/jnpr/junos/factory/__init__.py", line 33, in loadyaml
IOError: [Errno 20] Not a directory: '/usr/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/utils/junos_views.yml'

**Comment by dbarrosop** [comment]
Could you try doing the following and pasting the output?

cd /usr/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/
find

**Comment by dbarrosop** [comment]
That issue is due to the way napalm was installed. If you want to install it manually do:

    git clone git@github.com:napalm-automation/napalm.git
    cd napalm
    python setup.py sdist
    pip install dist/napalm-$version.tar.gz

Replace $version with the version you are trying to install.

**Comment by smnmtzgr** [comment]
like we discussed in the slack channel -> this worked fine. Thanks for your help!
