### ISSUE TITLE
Broken get_vlan on NX-OS for VLANs with no interfaces assigned

### ISSUE THREAD

**Issue by ggiesen** [napalm-automation/napalm#1145]
### Description of Issue/Question

Using get_vlans for nxos_ssh fails when there are VLANs defined with no interfaces assigned.

Example output captured from vlan_table_raw:
```
[{'vlanshowbr-shutstate': 'noshutdown',
  'vlanshowbr-vlanid': '1',
  'vlanshowbr-vlanid-utf': '1',
  'vlanshowbr-vlanname': 'default',
  'vlanshowbr-vlanstate': 'active',
  'vlanshowplist-ifidx': 'port-channel11,port-channel12,Ethernet1/43,Ethernet1/44,Ethernet1/47,Ethernet1/48'},
 {'vlanshowbr-shutstate': 'noshutdown',
  'vlanshowbr-vlanid': '1530',
  'vlanshowbr-vlanid-utf': '1530',
  'vlanshowbr-vlanname': 'VLAN1530',
  'vlanshowbr-vlanstate': 'active',
  'vlanshowplist-ifidx': 'port-channel11,port-channel12,port-channel100,Ethernet1/1,Ethernet1/2,Ethernet1/3,Ethernet1/4,Ethernet1/5,Ethernet1/6,Ethernet1/7,Ethernet1/8,Ethernet1/43,Ethernet1/44,Ethernet1/47,Ethernet1/48,Ethernet1/53,Ethernet1/54'},
 {'vlanshowbr-shutstate': 'noshutdown',
  'vlanshowbr-vlanid': '1671',
  'vlanshowbr-vlanid-utf': '1671',
  'vlanshowbr-vlanname': 'VLAN1671',
  'vlanshowbr-vlanstate': 'active'},
 {'vlanshowbr-shutstate': 'noshutdown',
  'vlanshowbr-vlanid': '3043',
  'vlanshowbr-vlanid-utf': '3043',
  'vlanshowbr-vlanname': 'VLAN3043',
  'vlanshowbr-vlanstate': 'active',
  'vlanshowplist-ifidx': 'port-channel11,port-channel12,port-channel100,Ethernet1/1,Ethernet1/2,Ethernet1/3,Ethernet1/4,Ethernet1/5,Ethernet1/6,Ethernet1/7,Ethernet1/8,Ethernet1/43,Ethernet1/44,Ethernet1/47,Ethernet1/48,Ethernet1/53,Ethernet1/54'},
 {'vlanshowbr-shutstate': 'noshutdown',
  'vlanshowbr-vlanid': '3840',
  'vlanshowbr-vlanid-utf': '3840',
  'vlanshowbr-vlanname': 'VLAN3840',
  'vlanshowbr-vlanstate': 'active',
  'vlanshowplist-ifidx': 'port-channel11,port-channel12,port-channel100,Ethernet1/1,Ethernet1/2,Ethernet1/3,Ethernet1/4,Ethernet1/5,Ethernet1/6,Ethernet1/7,Ethernet1/8,Ethernet1/43,Ethernet1/44,Ethernet1/47,Ethernet1/48,Ethernet1/53,Ethernet1/54'}]
```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
$ git rev-parse HEAD
08e41b8f17c3f12fbe94bece44e614d71a4f93e1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2018, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 07.61
  NXOS: version 7.0(3)I7(3)
  BIOS compile time:  04/06/2017
  NXOS image file is: bootflash:///nxos.7.0.3.I7.3.bin
  NXOS compile time:  2/12/2018 13:00:00 [02/12/2018 14:13:48]


Hardware
  cisco Nexus9000 93180YC-EX chassis
  Intel(R) Xeon(R) CPU  @ 1.80GHz with 24633488 kB of memory.
  Processor Board ID FDO221316NX

  Device name: nexussw1
  bootflash:   53298520 kB
Kernel uptime is 664 day(s), 17 hour(s), 29 minute(s), 48 second(s)

Last reset
  Reason: Unknown
  System version: 7.0(3)I7(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "./napalm-test.py", line 56, in <module>
    pprint.pprint(devicenxossw.get_vlans())
  File "/home/ggiesen/napalm/napalm/nxos_ssh/nxos_ssh.py", line 1526, in get_vlans
    "interfaces": self._parse_vlan_ports(vlan["vlanshowplist-ifidx"]),
KeyError: 'vlanshowplist-ifidx'
```

**Comment by ggiesen** [comment]
Created a simple fix with PR 1150
