### ISSUE TITLE
RPC timeout when committing config

### ISSUE THREAD

**Issue by grnv** [napalm-automation/napalm#1156]
### Description of Issue/Question
Napalm gets exception if commit of configuration takes more than the default PyEZ timeout. Need a way to override default timeout.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Junos: 15.1X49-D150.2
```

### Steps to Reproduce the Issue
Try to commit large config, especially in cluster environment.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 777, in execute
    ignore_warning=ignore_warning)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 1339, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/ncclient/operations/rpc.py", line 354, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_cfg.py", line 74, in <module>
    push_config(cfg_filename)
  File "generate_cfg.py", line 55, in push_config
    device.commit_config()
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/napalm/junos/junos.py", line 271, in commit_config
    self.device.cu.commit(ignore_warning=self.ignore_warning, **commit_args)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/utils/config.py", line 149, in commit
    rsp = self.rpc.commit_configuration(*rpc_varg, **rpc_args)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/home/sgor/scripts/venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 781, in execute
    raise EzErrors.RpcTimeoutError(self, rpc_cmd_e.tag, self.timeout)
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(host: 192.168.1.1, cmd: commit-configuration, timeout: 60)
```

**Comment by mirceaulinic** [comment]
When opening the connection with the device, you should be able to pass in the `timeout`, see https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver - that should apply to the `commit-configuration` RPC as well.

**Comment by grnv** [comment]
I thought I tried setting the timeout, but it appeared that I did it in the wrong place.
Thank you.
