### ISSUE TITLE
Cisco IOS (GNS3) : Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by zakkymuhammad** [napalm-automation/napalm#1165]
Hi, can you help me? I got this error when I was trying to test simple code with napalm. Thank you.

file "candidate"
```hostname Router```

```
from napalm import get_network_driver

driver = get_network_driver("ios")
others = {
			"secret":"cisco",
			"dest_file_system":"nvram:"
			}
device = driver(hostname="192.168.124.148", username="cisco", password="cisco", optional_args=others)
device.open()

device.load_merge_candidate(filename="candidate")
compare = device.compare_config()

print(compare)
device.commit_config()

device.close()
```
```
+hostname Router
Traceback (most recent call last):
  File "c.py", line 23, in <module>
    device.commit_config()
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/napalm/ios/ios.py", line 555, in commit_config
    output += self.device.save_config()
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 37, in save_config
    return super(CiscoIosBase, self).save_config(
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 224, in save_config
    output = self.send_command(command_string=cmd)
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/base_connection.py", line 1335, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command_expect: Router\#
```

**Comment by mirceaulinic** [comment]
@zakkymuhammad I'll help you with this search query: https://github.com/napalm-automation/napalm/issues?q=is%3Aissue+Search+pattern+never+detected+is%3Aclosed
Have you tried the solutions from the past similar issues?

**Comment by zakkymuhammad** [comment]
I've tried some solutions of posts which you mentioned such as:

- delay_factor : still not working
- inline_transfer : still not working
- strip_command & strip_prompt : still not working

**Comment by mirceaulinic** [comment]
What platform are you trying this on? A `show version` as requested in the issue template would be helpful.

**Comment by zakkymuhammad** [comment]
@mirceaulinic 

I only use GNS3 with running cisco image from EVE.

```
Router#show version 
Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version 15.2(4)M5.3, DEVELOPMENT TEST SOFTWARE
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Thu 07-Nov-13 19:11 by prod_rel_team

ROM: Bootstrap program is Linux

Router uptime is 2 hours, 26 minutes
System returned to ROM by reload at 0
System image file is "unix:/opt/gns3/images/IOU/L3-ADVENTERPRISEK9-M-15.2-M5.3.bin"
Last reload reason: Unknown reason



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.
          
A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html
          
If you require further assistance please contact us by sending email to
export@cisco.com.
          
Linux Unix (Intel-x86) processor with 124347K bytes of memory.
Processor board ID 2048001
8 Ethernet interfaces
8 Serial interfaces
64K bytes of NVRAM.
          
          
          
Configuration register is 0x0
  
```

**Comment by zakkymuhammad** [comment]
`hghjgjkhkhklhlj` khklklhklh

**Comment by zakkymuhammad** [comment]
Hi,

Do you have any updates about this problem?

**Comment by zakkymuhammad** [comment]
Hi Napalm Team,

Maybe this is caused by Cisco image. I was running my code on the different version of image. Thanks.
```
Cisco IOS Software, 3600 Software (C3660-A3JK9S-M), Version 12.4(19), RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2008 by Cisco Systems, Inc.
Compiled Fri 29-Feb-08 23:47 by prod_rel_team

ROM: ROMMON Emulation Microcode
ROM: 3600 Software (C3660-A3JK9S-M), Version 12.4(19), RELEASE SOFTWARE (fc1)

Router uptime is 6 minutes
System returned to ROM by unknown reload cause - suspect boot_data[BOOT_COUNT] 0x0, BOOT_COUNT 0, BOOTDATA 19
System image file is "tftp://255.255.255.255/unknown"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.
          
A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html
          
If you require further assistance please contact us by sending email to
export@cisco.com.
          
Cisco 3660 (R527x) processor (revision 1.0) with 187392K/9216K bytes of memory.
Processor board ID FTX0945W0MY
R527x CPU at 250MHz, Implementation 40, Rev 1.2, 512KB L2 Cache
          
          
3660 Chassis type: ENTERPRISE
8 FastEthernet interfaces
DRAM configuration is 64 bits wide with parity enabled.
253K bytes of NVRAM.
8192K bytes of processor board System flash (Read/Write)
          
Configuration register is 0x2102
```
