### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by jf008339** [napalm-automation/napalm#1226]
### Description of Issue/Question

When I am trying to import napalm module, I get: 

```ModuleNotFoundError: No module named 'fcntl'```

and

```ModuleNotFoundError: No module named 'clitable'```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
```
napalm==3.0.1
```

### python version
```
Python 3.8.2
```

### Windows version
10

### Steps to Reproduce the Issue

I have tried installing and uninstalling napalm. I did not see any pre-requisite to install it in the docs.

### Error Traceback

```

PS C:\Users\juan> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
Traceback (most recent call last):
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\__init__.py", line 12, in <module>
    import napalm.junos
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\__init__.py", line 18, in <module>
    from napalm.junos.junos import JunOSDriver  # noqa
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\junos.py", line 30, in <module>
    from jnpr.junos import Device
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\__init__.py", line 3, in <module>
    from jnpr.junos.factory.to_json import PyEzJSONEncoder
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 18, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Users\juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'
```

**Comment by ktbyers** [comment]
Which version of Juniper PyEZ library do you have installed?

Downgrade to Juniper PyEZ Version 2.3.2. That will probably fix your problem.

Note, this issue is fundamentally a TextFSM issue. Fix for it is here (but hasn't been merged into TextFSM nor released):

https://github.com/google/textfsm/pull/82

**Comment by jf008339** [comment]
Junos PyEZ version was 3.4.1. I downgraded to 2.3.2 and the same problem.

I moved to Linux and it works fine. 

Thanks for your reply. 😃
