### ISSUE TITLE
Napalm 3.0+ import fails on Windows platform because of fcntl absence

### ISSUE THREAD

**Issue by ankirich** [napalm-automation/napalm#1239]
### Description of Issue/Question

"import" napalm works  perfectly fine on windows platforms (w7/w10) for version 2.3.2. however, the same fails after upgrade to 3.0+

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
PS C:\Users\devops\Documents\Tech\REPOs\maintenance> pip freeze | findstr napalm
napalm==3.0.1
```
### Steps to Reproduce the Issue

PS C:\Users\devops\Documents\Tech\REPOs\_maintenance> python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\__init__.py", line 12, in <module>
    import napalm.junos
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\__init__.py", line 18, in <module>
    from napalm.junos.junos import JunOSDriver  # noqa
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\junos\junos.py", line 30, in <module>
    from jnpr.junos import Device
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\__init__.py", line 3, in <module>
    from jnpr.junos.factory.to_json import PyEzJSONEncoder
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 18, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ntc_templates\parse.py", line 3, in <module>
    from textfsm import clitable
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Users\devops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
### Error Traceback

**Comment by ankirich** [comment]
It seems that the problem is coming with _junos_eznc_. Version 2.4.1 installed with Napalm 3.0.1 has _cmdtable.py_ calling _parse_ function from _ntc_templates_ which, in turn tries to use _textfsm_.
I guess _textfsm_ there is a native module which, at the end, is trying to import _fcntl_.

**Comment by ktbyers** [comment]
This is not a really napalm issue. 

One fix is to install this PR:

https://github.com/google/textfsm/pull/82

Second option is to install a downrev version of Juniper PyEz (2.2.1 I believe). 

The issue is not Netmiko related. Netmiko has an alternate workaround for the Textfsm issue on windows. 

The issue is that Juniper PyEZ loads ntc_parse and ntc_parse loads textfsm without the Windows workaround (that Netmiko has).
