### ISSUE TITLE
get_environment uses old show environment temperature on EOS

### ISSUE THREAD

**Issue by aletessier** [napalm-automation/napalm#1265]
### Description of Issue/Question

On latest EOS release the *show environment temperature* command used by *get_environment* is deprecated.
The new way of getting temperature is *show system environment temperature*.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm 3.1.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
EOS 4.24.1.1F
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
bash-5.0$ python
Python 3.7.8 (default, Aug  4 2020, 05:06:20)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> d = napalm.get_network_driver('eos')
>>> e = d(hostname='10.153.152.227', username='admin', password='xxxxxx')
>>> e.open()
>>> e.get_environment()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/napalm/eos/eos.py", line 599, in get_environment
    fans_output, temp_output, power_output = self.device.run_commands(commands)
  File "/usr/local/lib/python3.7/site-packages/napalm/eos/pyeapi_syntax_wrapper.py", line 42, in run_commands
    return super(Node, self).run_commands(commands, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyeapi/client.py", line 743, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyeapi/eapilib.py", line 550, in execute
    response = self.send(request)
  File "/usr/local/lib/python3.7/site-packages/pyeapi/eapilib.py", line 469, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1002]: CLI command 3 of 4 'show environment temperature' failed: invalid command [This command is deprecated by 'show system environment temperature' (at token 2: 'temperature')]
```

**Comment by mirceaulinic** [comment]
Hey @aletessier. I think you'd need to add the mapping to the new command [here](https://github.com/napalm-automation/napalm/blob/develop/napalm/eos/utils/cli_syntax.py#L94) and [here](https://github.com/napalm-automation/napalm/blob/develop/napalm/eos/utils/cli_syntax.py#L246) (after the lines I linked). Can you test, and open a PR to fix this if it works?

**Comment by yzguy** [comment]
Put a PR in for this, seemed like a simple one for a first contribution

On EOS-4.22.3M

```
-> python
Python 3.8.5 (default, Jul 31 2020, 18:16:03)
[Clang 12.0.0 (clang-1200.0.26.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> d = napalm.get_network_driver('eos')
>>> e = d(hostname='sw1.lab.yzguy.io', username='yzguy', password='en2UBUIBME')
>>> e.open()
>>> e.get_environment()
{'fans': {'1': {'status': True}, '2': {'status': True}}, 'temperature': {'TempSensor1': {'temperature': 32.63371695786097, 'is_alert': False, 'is_critical': False}, 'TempSensor2': {'temperature': 26.0, 'is_alert': False, 'is_critical': False}, 'TempSensor3': {'temperature': 17.0, 'is_alert': False, 'is_critical': False}, 'TempSensor4': {'temperature': 12.75, 'is_alert': False, 'is_critical': False}, 'TempSensor5': {'temperature': 24.0, 'is_alert': False, 'is_critical': False}, 'TempSensor6': {'temperature': 18.375, 'is_alert': False, 'is_critical': False}, 'TempSensor7': {'temperature': 32.489599999999996, 'is_alert': False, 'is_critical': False}, 'TempSensor8': {'temperature': 32.489599999999996, 'is_alert': False, 'is_critical': False}, 'TempSensor9': {'temperature': 32.489599999999996, 'is_alert': False, 'is_critical': False}}, 'power': {'1': {'status': True, 'capacity': 65.0, 'output': -1.0}, '2': {'status': False, 'capacity': 65.0, 'output': -1.0}}, 'cpu': {0: {'%usage': 35.8}}, 'memory': {'available_ram': 3991300, 'used_ram': 3912524}}
```

On EOS-4.24.2.1F

```
-> python
Python 3.8.5 (default, Jul 31 2020, 18:16:03)
[Clang 12.0.0 (clang-1200.0.26.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> d = napalm.get_network_driver('eos')
>>> e = d(hostname='192.168.221.123', username='admin', password='password')
>>> e.open()
>>> e.get_environment()
{'fans': {}, 'temperature': {}, 'power': {}, 'cpu': {0: {'%usage': 9.9}}, 'memory': {'available_ram': 2012288, 'used_ram': 1970260}}
```

**Comment by yzguy** [comment]
I put a PR in for this, seemed like an easy first contribution

```
 -> python
Python 3.8.5 (default, Jul 31 2020, 18:16:03)
[Clang 12.0.0 (clang-1200.0.26.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> d = napalm.get_network_driver('eos')
>>> e = d(hostname='192.168.221.123', username='admin', password='password')
>>> e.open()
>>> e.get_environment()
{'fans': {}, 'temperature': {}, 'power': {}, 'cpu': {0: {'%usage': 9.9}}, 'memory': {'available_ram': 2012288, 'used_ram': 1970260}}
>>> e.get_facts()
{'hostname': 'testsw1', 'fqdn': 'testsw1', 'vendor': 'Arista', 'model': 'vEOS', 'serial_number': '', 'os_version': '4.24.2.1F-18613460.42421F', 'uptime': 15731, 'interface_list': ['Management1']}
```

**Comment by mirceaulinic** [comment]
That's great - thanks for the PR and testing it out @yzguy!
