### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: B2#

### ISSUE THREAD

**Issue by suhasbhoir** [napalm-automation/napalm#1277]
Only one router in topology getting this error while sending the load_merge_candidate **OSError: Search pattern never detected in send_command_expect: B2#** 

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [] No

### Setup

```
> from napalm import get_network_driver
> from netmiko import NetMikoAuthenticationException
> from netmiko.ssh_exception import NetMikoTimeoutException
> from paramiko.ssh_exception import SSHException
> from getpass import getpass
> import json
> from termcolor import colored
> import time
> 
> start = time.time()
> username = input('username: ')
> password = getpass('password:')
> driver = get_network_driver('ios')
> 
> with open('mydevices.txt', 'r') as router_ips:
>     for ip in router_ips:
>         print('connecting to', ip)
>         optional_args = {'secret': 'cisco'}
>         try:
>             ios = driver(ip, username, password,  optional_args={'global_delay_factor': 4})
>             ios.open()
>         except NetMikoAuthenticationException:
>             print(colored('Authentication Error!!!', 'red'))
>             username = input('username: ')
>             password = getpass('password:')
>             ios = driver(ip, username, password, optional_args={'global_delay_factor': 4})
>         except NetMikoTimeoutException:
>             username = input('username: ')
>             password = getpass('password:')
>             ios = driver(ip, username, password, optional_args={'global_delay_factor': 4})
>             print(colored('Time exceed!!!', 'red'))
>         except SSHException:
>             print(colored('Transport error with ssh or authentication', 'red'))
>         else:
>             ios.load_merge_candidate('nacl.txt')
>             diff = ios.compare_config()
>             print('Below configuration will be push on device')
>             print((diff))
>             while True:
>                 if len(diff) > 0:
>                     userinp = input('Do you want to commit changes on device, hit Y or  N: ').lower().strip()
>                     if userinp == 'y':
>                         ios.commit_config()
>                         print(colored('\nCommitting changes on devise', 'yellow'))
>                         print('#' * 50)
>                         print(colored('\nCommit confirm...', 'green'))
>                         break
>                     elif userinp == 'n':
>                         print(colored('\nDiscard the changes', 'red'))
>                         ios.discard_config()
>                         break
>                     else:
>                         print(colored('\ninvalid input detected', 'blue'))
> 
> 
>             ios.close()
> end = time.time()
> print(f'Total time during execution is:', colored(end - start, 'red'))
> 
```

### napalm version
(napalm==3.1.0)

```

```

### Network operating system version

```
Cisco IOS Software, 7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.2(4)S5, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Thu 20-Feb-14 06:51 by prod_rel_team

ROM: ROMMON Emulation Microcode
BOOTLDR: 7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.2(4)S5, RELEASE SOFTWARE (fc1)

**B2** uptime is 1 minute
System returned to ROM by unknown reload cause - suspect boot_data[BOOT_COUNT] 0x0, BOOT_COUNT 0, BOOTDATA 19
System image file is "tftp://255.255.255.255/unknown"
Last reload reason: Unknown reason
This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.
A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html
If you require further assistance please contact us by sending email to
export@cisco.com.
Cisco 7206VXR (NPE400) processor (revision A) with 491520K/32768K bytes of memory.
Processor board ID 4279256517
R7000 CPU at 150MHz, Implementation 39, Rev 2.1, 256KB L2 Cache
6 slot VXR midplane, Version 2.1
Last reset from power-on
PCI bus mb0_mb1 (Slots 0, 1, 3 and 5) has a capacity of 600 bandwidth points.
Current configuration on bus mb0_mb1 has a total of 1000 bandwidth points. 
The set of PA-2FE, PA-POS-2OC3, and I/O-2FE qualify for "half 
bandwidth points" consideration, when full bandwidth point counting 
results in oversubscription, under the condition that only one of the 
two ports is used. With this adjustment, current configuration on bus 
mb0_mb1 has a total of 600 bandwidth points. 
This configuration is within the PCI bus capacity and is supported 
under the above condition. 
PCI bus mb2 (Slots 2, 4, 6) has a capacity of 600 bandwidth points.
Current configuration on bus mb2 has a total of 400 bandwidth points 
This configuration is within the PCI bus capacity and is supported. 
Please refer to the following document "Cisco 7200 Series Port Adaptor
Hardware Configuration Guidelines" on Cisco.com <http://www.cisco.com>
for c7200 bandwidth points oversubscription and usage guidelines.
7 FastEthernet interfaces
509K bytes of NVRAM.
20480K bytes of ATA PCMCIA card at slot 0 (Sector size 512 bytes).
8192K bytes of Flash internal SIMM (Sector size 256K).
Configuration register is 0x2102

```

### Steps to Reproduce the Issue
use **optional_args={'global_delay_factor': 4}** but no luck

### Error Traceback

```
Traceback (most recent call last):
File "/home/suhasbhoir/Documents/Napalm/Napalm_merge_conf_excepH_multiplefile.py", line 34, in
ios.commit_config()
File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 555, in commit_config
output += self.device.save_config()
File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 37, in save_config
return super(CiscoIosBase, self).save_config(
File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 224, in save_config
output = self.send_command(command_string=cmd)
File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1335, in send_command
raise IOError(
OSError: Search pattern never detected in send_command_expect: B2#

```
Regards
Suhas Bhoir

**Comment by mirceaulinic** [comment]
Suhas, have you tried to increase the `global_delay_factor` more than 4? Say 10, and check if this would help. I believe you have followed the notes from https://napalm.readthedocs.io/en/latest/support/ios.html? Cheers.

**Comment by ktbyers** [comment]
It looks like it fails on doing the `write mem`. How long does write mem take on this device if you do it manually? Does it do anything odd if you manually do this i.e. `prompt` you to continue (this can happen after an OS-upgrade)?

**Comment by suhasbhoir** [comment]
I have  not tested yet.. i will check in coming two days.. and update you with the result.
