### ISSUE TITLE
get_users doesn't work at Juniper 

### ISSUE THREAD

**Issue by kimjw001** [napalm-automation/napalm#1294]
### Description of Issue/Question
getters=["get_users"] doesn't work on juniper platform

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [] Yes
- [x] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```PS C:\Users\jkim3\Pythonworkspace\network auto\Nornir> pip show napalm 
Name: napalm
Version: 2.5.0
Summary: Network Automation and Programmability Abstraction Layer with Multivendor support
Home-page: https://github.com/napalm-automation/napalm
Author: David Barroso, Kirk Byers, Mircea Ulinic
Author-email: dbarrosop@dravetech.com, ping@mirceaulinic.net, ktbyers@twb-tech.com
License: UNKNOWN
Location: c:\python38\lib\site-packages
Requires: pyYAML, pyeapi, setuptools, junos-eznc, ciscoconfparse, future, netaddr, pyIOSXR, cffi, scp, paramiko, jinja2, netmiko, textfsm, nxapi-plumbing
Required-by: nornir

```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```Model: ex9204
Junos: 18.4R2-S3


```

### Steps to Reproduce the Issue
#!/usr/bin/env python

from nornir import InitNornir
from nornir.plugins.functions.text import print_result
from nornir.plugins.tasks.networking import napalm_get
from nornir.core.filter import F

# Initialize nornir
nr = InitNornir(
    config_file="config.yaml", dry_run=True
)

# Let's just filter the hosts we want to operate on
cmh = nr.filter(F(platform='junos'))

# Let's retrieve the information and print them on screen
results = cmh.run(
    task=napalm_get, getters=["get_users"]
)

print_result(results)
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

``* AD1 ** changed : False *******************************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\nornir\core\task.py", line 85, in start
    r = self.task(self, **self.params)
  File "C:\Python38\lib\site-packages\nornir\plugins\tasks\networking\napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "C:\Python38\lib\site-packages\napalm\junos\junos.py", line 2116, in get_users
    root_user = self._get_root()
  File "C:\Python38\lib\site-packages\napalm\junos\junos.py", line 2081, in _get_root
    root_items = root_table.items()
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 174, in items
    return list(zip(self.keys(), self.values()))
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 150, in keys
    self._key_list = self._keys()
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 134, in _keys
    return self._keys_simple(xpath + '/' + key_value)
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 105, in _keys_simple
    return [x.text.strip() for x in self.xml.xpath(xpath)]
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 105, in <listcomp>
    return [x.text.strip() for x in self.xml.xpath(xpath)]
AttributeError: 'NoneType' object has no attribute 'strip'
`

```

**Comment by mirceaulinic** [comment]
I think that's rather a Nornir or Windows issue. Are you able to invoke other NAPALM methods successfully?

**Comment by ktbyers** [comment]
@kimjw001 Can you re-test it with NAPALM 3.2.0 (i.e. does it happen with the current version of NAPALM)?

**Comment by kimjw001** [comment]
@ktbyers 
I have upgrade napalm to 3.2.0 , I got same error.
 Test are OK ,
get_facts , 
get_lldp_neighbors
get_mac_address_table

Test are NOK
get_users
get_vlans

PS C:\Users\jkim3\Pythonworkspace\network auto\Nornir> pip show napalm
Name: napalm
Version: 3.2.0
Summary: Network Automation and Programmability Abstraction Layer with Multivendor support
Home-page: https://github.com/napalm-automation/napalm
Author: David Barroso, Kirk Byers, Mircea Ulinic
Author-email: dbarrosop@dravetech.com, ping@mirceaulinic.net, ktbyers@twb-tech.com
License: Apache 2.0
Location: c:\python38\lib\site-packages
Requires: textfsm, netmiko, pyeapi, requests, setuptools, future, ciscoconfparse, jinja2, scp, netaddr, junos-eznc, lxml, cffi, pyYAML, paramiko
Required-by: nornir

PS C:\Users\jkim3\Pythonworkspace\network auto\Nornir> & C:/Python38/python.exe "c:/Users/jkim3/Pythonworkspace/network auto/Nornir/filter.py"
napalm_get**********************************************************************
* AD1 ** changed : False *******************************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\nornir\core\task.py", line 85, in start
    r = self.task(self, **self.params)
  File "C:\Python38\lib\site-packages\nornir\plugins\tasks\networking\napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "C:\Python38\lib\site-packages\napalm\junos\junos.py", line 2140, in get_users
    root_user = self._get_root()
  File "C:\Python38\lib\site-packages\napalm\junos\junos.py", line 2108, in _get_root
    root_items = root_table.items()
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 174, in items
    return list(zip(self.keys(), self.values()))
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 150, in keys
    self._key_list = self._keys()
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 134, in _keys
    return self._keys_simple(xpath + '/' + key_value)
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 105, in _keys_simple
    return [x.text.strip() for x in self.xml.xpath(xpath)]
  File "C:\Python38\lib\site-packages\jnpr\junos\factory\table.py", line 105, in <listcomp>
    return [x.text.strip() for x in self.xml.xpath(xpath)]
AttributeError: 'NoneType' object has no attribute 'strip'

^^^^ END napalm_get ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PS C:\Users\jkim3\Pythonworkspace\network auto\Nornir> 


get_vlans error,

* AD1 ** changed : False *******************************************************
vvvv napalm_get ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\nornir\core\task.py", line 85, in start
    r = self.task(self, **self.params)
  File "C:\Python38\lib\site-packages\nornir\plugins\tasks\networking\napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "C:\Python38\lib\site-packages\napalm\base\base.py", line 1687, in get_vlans
    raise NotImplementedError
NotImplementedError

**Comment by yzguy** [comment]
The `get_vlans` error of NotImplementedError is expected per the [Getters Support Matrix](https://napalm.readthedocs.io/en/latest/support/index.html#getters-support-matrix)

**Comment by kimjw001** [comment]
@yzguy Thanks . I didn't check matrix
