### ISSUE TITLE
SCPException: Privilege denied.

### ISSUE THREAD

**Issue by sumitmcc** [napalm-automation/napalm#1296]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
- Connecting to an IOS device and loading config and trying to commit it

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS XE Software, Version 16.12.01
Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 16.12.1, RELEASE SOFTWARE (fc4)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2019 by Cisco Systems, Inc.
Compiled Tue 30-Jul-19 19:17 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2019 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: IOS-XE ROMMON
BOOTLDR: System Bootstrap, Version 16.12.1r[FC1], RELEASE SOFTWARE (P)

AM.11-CAT9300-3 uptime is 18 hours, 14 minutes
Uptime for this control processor is 18 hours, 15 minutes
System returned to ROM by Reload Command at 08:50:02 EDT Tue Sep 15 2020
System image file is "flash:cat9k_iosxe_npe.16.12.01.SPA.bin"
Last reload reason: Reload Command



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.


Technology Package License Information:

------------------------------------------------------------------------------
Technology-package                                     Technology-package
Current                        Type                       Next reboot
------------------------------------------------------------------------------
network-advantage   	Smart License                 	 network-advantage
dna-advantage       	Subscription Smart License    	 dna-advantage
AIR License Level: AIR DNA Advantage
Next reload AIR license Level: AIR DNA Advantage


Smart Licensing Status: UNREGISTERED/EVAL EXPIRED

cisco C9300-48U (X86) processor with 1351834K/6147K bytes of memory.
Processor board ID FCW2125L00A
1 Virtual Ethernet interface
52 Gigabit Ethernet interfaces
8 Ten Gigabit Ethernet interfaces
2 TwentyFive Gigabit Ethernet interfaces
2 Forty Gigabit Ethernet interfaces
2048K bytes of non-volatile configuration memory.
8388608K bytes of physical memory.
1638400K bytes of Crash Files at crashinfo:.
11264000K bytes of Flash at flash:.
0K bytes of WebUI ODM Files at webui:.

Base Ethernet MAC Address          : 70:d3:79:be:7e:00
Motherboard Assembly Number        : 73-17957-07
Motherboard Serial Number          : FOC21230MKC
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : C9300-48U
System Serial Number               : FCW2125L00A


Switch Ports Model              SW Version        SW Image              Mode
------ ----- -----              ----------        ----------            ----
*    1 65    C9300-48U          16.12.1           CAT9K_IOSXE           BUNDLE


Configuration register is 0x102
```

### Steps to Reproduce the Issue
- Connecting to an IOS device and loading config and trying to commit it
- Intermittent issue - does not occur every time

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
SCPException: Privilege denied.
Traceback (most recent call last):
  File "/home/cisco/cxta/workspace/Napalm.py", line 71, in load_config
    driver.load_replace_candidate(config=config)
  File "/venv/lib/python3.7/site-packages/napalm/ios/ios.py", line 304, in load_replace_candidate
    file_system=self.dest_file_system,
  File "/venv/lib/python3.7/site-packages/napalm/ios/ios.py", line 271, in _load_candidate_wrapper
    source_file=tmp_file, dest_file=dest_file, file_system=file_system
  File "/venv/lib/python3.7/site-packages/napalm/ios/ios.py", line 625, in _scp_file
    TransferClass=FileTransfer,
  File "/venv/lib/python3.7/site-packages/napalm/ios/ios.py", line 693, in _xfer_file
    transfer.transfer_file()
  File "/venv/lib/python3.7/site-packages/netmiko/scp_handler.py", line 360, in transfer_file
    self.put_file()
  File "/venv/lib/python3.7/site-packages/netmiko/scp_handler.py", line 373, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/venv/lib/python3.7/site-packages/netmiko/scp_handler.py", line 46, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/venv/lib/python3.7/site-packages/scp.py", line 158, in put
    self._recv_confirm()
  File "/venv/lib/python3.7/site-packages/scp.py", line 363, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
```

**Comment by ktbyers** [comment]
The user you login using must have privilege level 15 for Secure Copy to work (i.e. must login at level15...well technically elevated privileges with sufficient permissions). You cannot elevate privileges using `enable()` (this is a Cisco-IOS/XE limitation).

A workaround is to use inline_transfer.

That is what the error message you are posting indicates. Don't know why it would be intermittent--that part is strange.

**Comment by Ebenezer91** [comment]
Does the inline_transfer replace the command load. Merge?

**Comment by ktbyers** [comment]
The `inline_transfer` causes the file transfer to occur via the SSH control channel using TCL (instead of opening a separate SCP channel for the file transfer). 

The SSH control channel allows the privileges to be raised using an `enable()` call (the SCP channel doesn't allow this).

**Comment by BENBUNOR** [comment]
from napalm import get_network_driver
from getpass import getpass
driver = get_network_driver('ios')


device = driver(
    hostname='10.0.0.0,
    username='adm',
    password=getpass(),
)
device.open()


device.load_merge_candidate(filename='config.txt)

diffs = device.compare_config()
if len(diffs) > 0:
    print(diffs)
    device.commit_config()
else:
    print('no change is required')
    device.discard_config()

device.close()


where do i administer the "inline_transfer"? should it replace the load_merge_candidate?
