### ISSUE TITLE
Sample code with Napalm produced the bunch of error (Pycharm)

### ISSUE THREAD

**Issue by lupineye** [napalm-automation/napalm#1298]
### Description of Issue/Question

Hi, Gurus. I'm struggling to napalm work with Pycharm on Windows 10. I installed Napalm and related package and tested if this sample code was working. but it produced a bunch of errors with "ModuleNotFoundError: No module named 'fcntl' at the end.  I have to test and verify the code before pushing onto the production network. Please give advice to me. Thanks a lot.

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [v] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

napalm 3.2.0
```

```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)
Cisco IOSv 
```

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\Scripts\python.exe C:/Users/lupineye/PycharmProjects/Python_Programming/Network/Cisco/Napalm/napalm_get_facts.py
Traceback (most recent call last):
  File "C:/Users/lupineye/PycharmProjects/Python_Programming/Network/Cisco/Napalm/napalm_get_facts.py", line 9, in <module>
    from napalm import get_network_driver
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\napalm\__init__.py", line 12, in <module>
    import napalm.junos
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\napalm\junos\__init__.py", line 18, in <module>
    from napalm.junos.junos import JunOSDriver  # noqa
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\napalm\junos\junos.py", line 53, in <module>
    from napalm.junos.utils import junos_views
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\napalm\junos\utils\junos_views.py", line 6, in <module>
    from jnpr.junos.factory import FactoryLoader
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 19, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\ntc_templates\parse.py", line 3, in <module>
    from textfsm import clitable
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Users\lupineye\PycharmProjects\Python_Programming\venv1\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Process finished with exit code 1

```

**Comment by ktbyers** [comment]
You need to install the patch here:

https://github.com/google/textfsm/pull/82


Regards, Kirk
