### ISSUE TITLE
Cannot compare config on IOS

### ISSUE THREAD

**Issue by t2d** [napalm-automation/napalm#130]
Ansible task:
```
- name: Push configuration with napalm
  napalm_install_config:
    hostname: "{{ inventory_hostname }}.{{ domain }}"
    dev_os: ios
    username: "{{ user }}"
    password: "{{ password }}"
    config_file: cisco-configs/{{ inventory_hostname }}/configuration
    commit_changes: False
    replace_config: False
    diff_file: cisco-config/{{ inventory_hostname }}/diff
```
Ansible output:
```
TASK: [cisco-ios | Push configuration with napalm] **************************** 
failed: [host2] => {"failed": true, "parsed": false}
SSH connection established to host2.example.org:22
Interactive SSH session established
+ hostname host2
Traceback (most recent call last):
  File "/home/t/.ansible/tmp/ansible-tmp-1451918787.56-76835226695125/napalm_install_config", line 1790, in <module>
    main()
  File "/home/t/.ansible/tmp/ansible-tmp-1451918787.56-76835226695125/napalm_install_config", line 161, in main
    diff = device.compare_config().encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```
Same happens with `commit_changes: True`

**Comment by dbarrosop** [comment]
As you are probably aware by now there is some work going on that might fix this issue.

**Comment by dbarrosop** [comment]
With the release of NAPALM 0.51.0 this should now work. Open a new issue if it's not the case.

Thanks!
