### ISSUE TITLE
Add wildcard to set for detect_config_format

### ISSUE THREAD

**Issue by Trilogie** [napalm-automation/napalm#1316]
### Description of Issue/Question
You cannot push a set config with "wildcard" as the starting word only to Juniper.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
Nornir, Napalm, Juniper EX3400

### napalm version
```
napalm==3.2.0
```

### Network operating system version
```
Model: ex3400-48p
Junos: 15.1X53-D56
JUNOS OS Kernel 32-bit  [20170413.348470_builder_head]
JUNOS OS libs [20170413.348470_builder_head]
JUNOS OS runtime [20170413.348470_builder_head]
JUNOS OS time zone information [20170413.348470_builder_head]
JUNOS py extensions [20170413.101346_builder_junos_151_x53_d56]
JUNOS py base [20170413.101346_builder_junos_151_x53_d56]
JUNOS OS crypto [20170413.348470_builder_head]
JUNOS network stack and utilities [20170413.101346_builder_junos_151_x53_d56]
JUNOS libs [20170413.101346_builder_junos_151_x53_d56]
JUNOS runtime [20170413.101346_builder_junos_151_x53_d56]
JUNOS Web Management Platform Package [20170413.101346_builder_junos_151_x53_d56]
JUNOS ex libs [20170413.101346_builder_junos_151_x53_d56]
JUNOS ex runtime [20170413.101346_builder_junos_151_x53_d56]
JUNOS ex platform support [20170413.101346_builder_junos_151_x53_d56]
JUNOS modules [20170413.101346_builder_junos_151_x53_d56]
JUNOS ex modules [20170413.101346_builder_junos_151_x53_d56]
JUNOS Data Plane Crypto Support [20170413.101346_builder_junos_151_x53_d56]
JUNOS mtx Data Plane Crypto Support [20170413.101346_builder_junos_151_x53_d56]
JUNOS daemons [20170413.101346_builder_junos_151_x53_d56]
JUNOS Packet Forwarding Engine Support (EX34XX) [20170413.101346_builder_junos_151_x53_d56]
JUNOS jdocs ex [20170413.101346_builder_junos_151_x53_d56]
JUNOS jail runtime [20170413.348470_builder_head]
JUNOS FIPS mode utilities [20170413.101346_builder_junos_151_x53_d56]
```

### Steps to Reproduce the Issue
Push a set config format with wildcard as the only first word
```
wildcard range delete interfaces ge-0/0/[0-10]
wildcard range set interfaces ge-0/0/[0-5]
```

### Error Traceback
```
Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/3.9.0/lib/python3.9/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/Users/steve/.pyenv/versions/3.9.0/lib/python3.9/site-packages/nornir/plugins/tasks/networking/napalm_configure.py", line 32, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/Users/steve/.pyenv/versions/3.9.0/lib/python3.9/site-packages/napalm/junos/junos.py", line 270, in load_merge_candidate
    self._load_candidate(filename, config, False)
  File "/Users/steve/.pyenv/versions/3.9.0/lib/python3.9/site-packages/napalm/junos/junos.py", line 260, in _load_candidate
    raise MergeConfigException(e.errs)
napalm.base.exceptions.MergeConfigException: [{'severity': 'error', 'source': None, 'edit_path': None, 'bad_element': 'wildcard', 'message': 'syntax error'}]

```

I was able to fix this by changing the following to add wildcard:
napalm/junos/junos.py
```
    def _detect_config_format(self, config):
        fmt = "text"
        set_action_matches = [
            "set",
            "activate",
            "deactivate",
            "annotate",
            "copy",
            "delete",
            "insert",
            "protect",
            "rename",
            "unprotect",
            "edit",
            "top",
            "wildcard",
        ]
        if config.strip().startswith("<"):
            return "xml"
        elif config.strip().split(" ")[0] in set_action_matches:
            return "set"
        elif self._is_json_format(config):
            return "json"
        return fmt
```

**Comment by mirceaulinic** [comment]
Hi @Trilogie, the solution you suggest would work. Feel free to open a PR, cheers!

**Comment by Trilogie** [comment]
@mirceaulinic done!

**Comment by mirceaulinic** [comment]
Thanks @Trilogie.
