### ISSUE TITLE
Juniper SRX 320 - UTF-8 Error 

### ISSUE THREAD

**Issue by prime001** [napalm-automation/napalm#1327]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
CentOS Linux 7 (Core) Version 7
```

### Steps to Reproduce the Issue
device.get_route_to(destination='10.')
or
device.get_lldp_neighbors()

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
'Model: SRX320-POE'
'Version: 15.1X49-D70.3'
'Serial: CX2318AF0166'
'Vendor: Juniper'
'Uptime: 9690'
/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py:801: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/napalm/junos/junos.py", line 1666, in get_route_to
    routes_table.get(**rt_kargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/factory/optable.py", line 64, in get
    self.xml = getattr(self.RPC, self.GET_RPC)(**rpc_args)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 63, in wrapper
    result = function(*args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 777, in execute
    ignore_warning=ignore_warning)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 1339, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._error
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 488, in run
    self.parser.parse(data)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 118, in parse
    self._parse10()
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 130, in _parse10
    if MSG_DELIM in buf.read().decode('UTF-8'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 87: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ip_plan.py", line 297, in <module>
    main()
  File "ip_plan.py", line 101, in main
    supernet = device.get_route_to(destination=test1)
  File "/usr/local/lib/python3.6/site-packages/napalm/junos/junos.py", line 1685, in get_route_to
    "Cannot retrieve routes! Reason: {err}".format(err=err)
napalm.base.exceptions.CommandErrorException: Cannot retrieve routes! Reason: 'utf-8' codec can't decode byte 0x80 in position 87: invalid start byte

Another 

/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py:801: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
Traceback (most recent call last):
  File "ip_plan.py", line 297, in <module>
    main()
  File "ip_plan.py", line 176, in main
    neighbors = device.get_lldp_neighbors()
  File "/usr/local/lib/python3.6/site-packages/napalm/junos/junos.py", line 759, in get_lldp_neighbors
    lldp.get()
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/factory/optable.py", line 64, in get
    self.xml = getattr(self.RPC, self.GET_RPC)(**rpc_args)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 63, in wrapper
    result = function(*args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 777, in execute
    ignore_warning=ignore_warning)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/home/local/DYNUTIL/pam.dii.ea0033/ip_plan/python3-virtualenv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 1339, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 338, in _request
    self._reply.parse()
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 148, in parse
    root = self._root = to_ele(self._raw, huge_tree=self._huge_tree) # The <rpc-reply> element
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 2
lxml.etree.XMLSyntaxError: attributes construct error, line 2, column 111

```

**Comment by mirceaulinic** [comment]
Closing as this doesn't respect the first FAQ item:

> Make sure you have the latest release installed. We release very often, so upgrading to the latest version might help in many cases.

If the error persists after upgrading, feel free to reopen.
