### ISSUE TITLE
device.load_merge_candidate() failing on netmiko scp_handler.py Cisco C3850

### ISSUE THREAD

**Issue by vascojcm** [napalm-automation/napalm#1335]
### Description of Issue/Question

I generate a file with vlan configs and want to merge with the current switch running config.
```
driver = napalm.get_network_driver('ios')
device = driver(
hostname="hostname",
username="username",
password="password",
optional_args={"dest_file_system": "flash:/" , "global_delay_factor": 4}
)
device.open()
print(device.get_vlans())

```
The print of get_vlans() get_facts() or some other get method is OK. 
When I try to load the file into the flash (via load_merge_candidate method) I get the traceback described below in the traceback session.
`device.load_merge_candidate(filename="my_candidate_merge_file")`

I followed the FAQ:
```
my_switch# show run  | inc scp
ip scp server enable
```
If I try the same procedure with scp and I'm able to transfer the file:
```
$ scp my_candidate_merge_file username@my_switch:flash:/my_candidate_merge_file
Password: 
my_candidate_merge_file                                                                  100%   28     2.3KB/s   00:00    

```

```
myswitch#dir flash: | inc my_candidate
23243  -rw-          28  Dec 16 2020 02:52:22 +00:00  my_candidate_merge_file

```

The flash: drive has free space
```
#dir flash: | inc free 
1621966848 bytes total (1305686016 bytes free)
```

I tried to change the _dest_file_system_ var to "flash:/" or "flash:" always with the same failed result.

The user that is logging into the switch has full admin privilege level.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

napalm==3.2.0
napalm-ansible==1.1.0

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Switch Ports Model              SW Version        SW Image              Mode   
------ ----- -----              ----------        ----------            ----   
*    2 56    WS-C3850-48T       03.07.02E         cat3k_caa-universalk9 INSTALL
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "./vlan.py", line 85, in <module>
    device.load_merge_candidate(filename="my_candidate_merge_file")
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 621, in _scp_file
    return self._xfer_file(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 677, in _xfer_file
    if not transfer.verify_space_available():
  File "/usr/local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 192, in verify_space_available
    space_avail = self.remote_space_available(search_pattern=search_pattern)
  File "/usr/local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 136, in remote_space_available
    if "kbytes" in match.group(0) or "Kbytes" in match.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by vascojcm** [comment]
dear @mirceaulinic, 
Can you please let me know what type of info is needed in order to unblock this issue ?

**Comment by ktbyers** [comment]
@vascojcm Which version of Netmiko are you using?

It looks like it is failing on this code here:

```python
    def remote_space_available(self, search_pattern=r"(\d+) \w+ free"):
        """Return space available on remote device."""
        remote_cmd = f"dir {self.file_system}"
        remote_output = self.ssh_ctl_chan.send_command_expect(remote_cmd)
        match = re.search(search_pattern, remote_output)
        if "kbytes" in match.group(0) or "Kbytes" in match.group(0):
            return int(match.group(1)) * 1000
        return int(match.group(1))
```

Particularly the `match`=re.search` that is returning None. You might need to go into the Python debugger here and see what the `remote_output` is at this point.

**Comment by vascojcm** [comment]
Dear @ktbyers,

```
$pip3 freeze | grep netmiko
netmiko==3.2.0
$
```

I just saw that the latest release of netmiko is 3.3.2, I will update it and will let you know about the outcome.

Thanks

**Comment by vascojcm** [comment]
Dear @ktbyers,
Now:
```
$/pip3 freeze | grep netmiko
netmiko==3.3.2
```
Same issue is happening but now in different lines (probably due to the new netmiko version)
```
Traceback (most recent call last):
  File "./vlan.py", line 92, in <module>
    device.load_merge_candidate(filename="zg2sw101-4.txt")
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 283, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 621, in _scp_file
    return self._xfer_file(
  File "/usr/local/lib/python3.8/site-packages/napalm/ios/ios.py", line 677, in _xfer_file
    if not transfer.verify_space_available():
  File "/usr/local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 199, in verify_space_available
    space_avail = self.remote_space_available(search_pattern=search_pattern)
  File "/usr/local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 143, in remote_space_available
    if "kbytes" in match.group(0) or "Kbytes" in match.group(0):
AttributeError: 'NoneType' object has no attribute 'group'
```
I will try to debug further and will let you know.

Thanks

**Comment by ktbyers** [comment]
Okay probably need to go into the debugger and see what is going on there. On the face of it, it looks like it should be working on that regex parsing.

**Comment by vascojcm** [comment]
After running into the debugger I finally found what was happening:
a bug in the code. 🤦 
thank you for the help
cheers
