### ISSUE TITLE
IOS-XR NETCONF driver fails on get_facts()

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1345]
get_facts() fails with the following exception:

```
Traceback (most recent call last):
  File "iosxr_netconf.py", line 28, in <module>
    device_facts = device.get_facts()
  File "/home/kbyers/NAPALM/napalm/napalm/iosxr_netconf/iosxr_netconf.py", line 385, in get_facts
    basic_info_tree = facts_rpc_reply_etree.xpath(
IndexError: list index out of range
```

facts_rpc_reply_etree is the following:

```
ipdb> print(ETREE.tostring(facts_rpc_reply_etree).decode())                                                                                   
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:3d3dcff5-41eb-4e7f-8d65-baa0222731f6">
 <data>
  <system-time xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-oper">
   <clock>
    <year>2020</year>
    <month>12</month>
    <day>17</day>
    <hour>1</hour>
    <minute>54</minute>
    <second>37</second>
    <millisecond>334</millisecond>
    <wday>4</wday>
    <time-zone>UTC</time-zone>
    <time-source>calendar</time-source>
   </clock>
   <uptime>
    <host-name>iosxr3</host-name>
    <uptime>6043158</uptime>
   </uptime>
  </system-time>
  <interfaces xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-pfi-im-cmd-oper">
   <interfaces>
    <interface>
     <interface-name>MgmtEth0/RP0/CPU0/0</interface-name>
    </interface>
    <interface>
     <interface-name>Null0</interface-name>
    </interface>
   </interfaces>
  </interfaces>
 </data>
</rpc-reply>
```

```
#show version
Thu Dec 17 01:56:56.115 UTC
Cisco IOS XR Software, Version 6.5.3
Copyright (c) 2013-2019 by Cisco Systems, Inc.

Build Information:
 Built By     : ahoang
 Built On     : Tue Mar 26 06:52:25 PDT 2019
 Built Host   : iox-ucs-019
 Workspace    : /auto/srcarchive13/prod/6.5.3/xrv9k/ws
 Version      : 6.5.3
 Location     : /opt/cisco/XR/packages/

cisco IOS-XRv 9000 () processor
System uptime is 9 weeks 6 days 22 hours 41 minutes
```

**Comment by ktbyers** [comment]
@neelimap

**Comment by ktbyers** [comment]
`get_environment()` will also fail as it calls `get_facts`

**Comment by neelimapp** [comment]
Will look into it. Thanks.

**Comment by 111pontes** [comment]
Took a quick look.  Needs more investigation, but it seems potentially a defect in the XR version where the proper inventory info isn't provided by the device.  If that's the scenario, what is consider the proper robust implementation?  Should themethod return empty data for the info missing?  Should an exception be raised?  If so, what exception? Just `NapalmException` with an error string?

**Comment by ktbyers** [comment]
If some particular data is impossible to get via XML and get_facts() I would just leave that field as empty/null (so generally a null-string for that field).

**Comment by neelimapp** [comment]
@ktbyers, Could you please provide the configuration of the device you are using, to test get_facts()?

**Comment by ktbyers** [comment]
```
Mon Feb  1 21:23:13.709 UTC
Building configuration...
!! IOS XR Configuration version = 6.5.3
!! Last configuration change at Mon Feb  1 19:49:24 2021 by pyclass
!
hostname iosxr3
logging buffered 4000010
logging buffered notifications
username admin
 group root-lr
 group cisco-support
 secret 5 $1$sOIq$M6OvZBlxdY5E47PMeHyVi/
!
username pyclass
 group root-lr
 secret 5 $1$qaMu$ulZN/jY.KPBp2WyL/mc4r.
!
ntp
 server 130.126.24.24
 server 152.2.21.1
!
call-home
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method http
 !
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address dhcp
!
interface preconfigure GigabitEthernet0/0/0/0
 description g0/0/0/0
!         
interface preconfigure GigabitEthernet0/0/0/1
 description g0/0/0/1
!
interface preconfigure GigabitEthernet0/0/0/2
 description g0/0/0/2
!
interface preconfigure GigabitEthernet0/0/0/3
 description g0/0/0/3
!
interface preconfigure GigabitEthernet0/0/0/4
 description g0/0/0/4
!
interface preconfigure GigabitEthernet0/0/0/5
 description g0/0/0/5
!
route-policy ALLOW
  pass
end-policy
!
router static
 address-family ipv4 unicast
  0.0.0.0/0 10.0.2.2
 !
!
router bgp 65044
 bgp router-id 10.0.2.15
 address-family ipv4 unicast
 !
 neighbor 10.0.2.99
  remote-as 65044
  description *** fictional peer ***
  address-family ipv4 unicast
   route-policy ALLOW in
   route-policy ALLOW out
  !
 !
!
xml agent tty
 iteration off
!
netconf agent tty
!
netconf-yang agent
 ssh
!
ssh server enable cipher aes-cbc
ssh server algorithms key-exchange diffie-hellman-group1-sha1
ssh server v2
ssh server netconf vrf default
end
```

**Comment by neelimapp** [comment]
Thanks, @ktbyers. Could you please remove this tag  <name>Rack 0</name> from the below constant FACTS_RPC_REQ of  https://github.com/napalm-automation/napalm/blob/iosxr_new2/napalm/iosxr_netconf/constants.py and see if the issue still exists?

# GET RPC to retrieve device facts
FACTS_RPC_REQ = """<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.1">
  <filter>
    <system-time xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-oper"/>
    <interfaces xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-pfi-im-cmd-oper">
      <interfaces>
        <interface>
          <interface-name/>
        </interface>
      </interfaces>
    </interfaces>
    <inventory xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-invmgr-oper">
      <entities>
        <entity>
          <name>Rack 0</name>
          <attributes>
            <inv-basic-bag>
              <software-revision/>
              <model-name/>
              <serial-number/>
            </inv-basic-bag>
          </attributes>
        </entity>
      </entities>
    </inventory>
  </filter>
</get>"""

**Comment by neelimapp** [comment]
Thanks, @ktbyers. Could you please remove this tag ``` <name>Rack 0</name>``` from the below constant FACTS_RPC_REQ of https://github.com/napalm-automation/napalm/blob/iosxr_new2/napalm/iosxr_netconf/constants.py and see if the issue still exists?

```
# GET RPC to retrieve device facts
FACTS_RPC_REQ = """<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.1">
  <filter>
    <system-time xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-oper"/>
    <interfaces xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-pfi-im-cmd-oper">
      <interfaces>
        <interface>
          <interface-name/>
        </interface>
      </interfaces>
    </interfaces>
    <inventory xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-invmgr-oper">
      <entities>
        <entity>
          <name>Rack 0</name>
          <attributes>
            <inv-basic-bag>
              <software-revision/>
              <model-name/>
              <serial-number/>
            </inv-basic-bag>
          </attributes>
        </entity>
      </entities>
    </inventory>
  </filter>
</get>"""
```

**Comment by ktbyers** [comment]
Same error:

```diff
$ git diff
diff --git a/napalm/iosxr_netconf/constants.py b/napalm/iosxr_netconf/constants.py
index 9a41a2bc..11deeeb6 100644
--- a/napalm/iosxr_netconf/constants.py
+++ b/napalm/iosxr_netconf/constants.py
@@ -60,7 +60,6 @@ FACTS_RPC_REQ = """<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.1">
     <inventory xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-invmgr-oper">
       <entities>
         <entity>
-          <name>Rack 0</name>
           <attributes>
             <inv-basic-bag>
               <software-revision/>
```

```
<napalm.iosxr_netconf.iosxr_netconf.IOSXRNETCONFDriver object at 0x7f628c035b70>
Traceback (most recent call last):
  File "iosxr_netconf.py", line 29, in <module>
    facts = device.get_facts()
  File "/home/kbyers/NAPALM/napalm/napalm/iosxr_netconf/iosxr_netconf.py", line 388, in get_facts
    )[0]
IndexError: list index out of range
```

**Comment by neelimapp** [comment]
Thanks, @ktbyers. I am able to retrieve the facts from the 6.5.3 xrv9k device.  Please find the output and device version below.  Can I access your device and check?
```
{
    "fqdn": "pavarotti",
    "hostname": "pavarotti",
    "interface_list": [
        "GigabitEthernet0/0/0/0",
        "GigabitEthernet0/0/0/1",
        "Loopback0",
        "Loopback1000",
        "MgmtEth0/RP0/CPU0/0",
        "Null0"
    ],
    "model": "R-IOSXRV9000-CC",
    "os_version": "6.5.3",
    "serial_number": "E3FDA081DAC",
    "uptime": 1991194,
    "vendor": "Cisco"
}
```

```
RP/0/RP0/CPU0:pavarotti#show version
Mon Feb  1 23:16:07.761 UTC
Cisco IOS XR Software, Version 6.5.3
Copyright (c) 2013-2019 by Cisco Systems, Inc.

Build Information:
 Built By     : ahoang
 Built On     : Tue Mar 26 06:52:25 PDT 2019
 Built Host   : iox-ucs-019
 Workspace    : /auto/srcarchive13/prod/6.5.3/xrv9k/ws
 Version      : 6.5.3
 Location     : /opt/cisco/XR/packages/

cisco IOS-XRv 9000 () processor
System uptime is 3 weeks 2 days 1 hour 10 minutes
```

**Comment by ktbyers** [comment]
@neelimapp Can you send me your source IP address so I can add it to my firewall policy to allow you this access? You can just email it to me.

Thanks, Kirk

**Comment by ktbyers** [comment]
I think this was fixed here:

https://github.com/napalm-automation/napalm/pull/1336/commits/a3f02075b28a8b77230f5036fe5c1237fbb524cd
