### ISSUE TITLE
get_network_instances     del instances["default"]["interfaces"]["interface"][item] on IOS-XE KeyError

### ISSUE THREAD

**Issue by muhammad-rafi** [napalm-automation/napalm#1350]
### Description of Issue/Question

I have been using the napalm '`get_network_instances(name='')'` to pull the details of all VRFs on the IOSXE device but it is given me the similar key error below no matter what device I try, however it works really good for IOS devices, not sure if I am missing something in my function or it is bug ? 

### napalm version
napalm==3.2.0

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```Traceback (most recent call last):
  File "ios_interface_tabulate.py", line 188, in <module>
    get_vrfs()
  File "ios_interface_tabulate.py", line 115, in get_vrfs
    vrf_table = device_conn.get_network_instances()
  File "C:\Users\rafim1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\napalm\ios\ios.py", line 3431, in get_network_instances
    del instances["default"]["interfaces"]["interface"][item]
KeyError: 'GigabitEthernet0/0/2.1302'
```

### my code
```
def get_vrf(port=22):
    """ Return the VRFs configured on the device along 
    with their attributes, by default all VRFs will be return, 
    for specific vrf (e.g: management), 'vrf='management' """
    
    try: 
        for device in devices:
            print(Fore.LIGHTGREEN_EX + "*" * 75)
            print('Connecting to ' + device + ' ...')
            print(Fore.LIGHTGREEN_EX + "*" * 75 + Style.RESET_ALL)
        
            # Setting the network driver for naplam to detect the device type
            driver = get_network_driver('ios')
            
            # Building a network connnection to the device 
            device_conn = driver(device, username, password, optional_args={"port": port})
            #device_conn = driver(device, username, password)
            device_conn.open()
            
            print(Fore.LIGHTGREEN_EX + "*" * 75)
            print('Successfully connected! waiting for the output ...')
            print(Fore.LIGHTGREEN_EX + "*" * 75 + Style.RESET_ALL)
        
            vrf_table = device_conn.get_network_instances(name='')
            vrf_json = json.dumps(vrf_table, indent=2)
            print(vrf_json)
        
    except Exception as e:
        print(Fore.RED + str(e) + Style.RESET_ALL)
```

**Comment by deiliet** [comment]
My version of fixing bug - handle canonical_interface_name() to form long names of interfaces int both dictionaries:
-interface_dict
-instances

def get_network_instances(self, name=""):

        instances = {}
        sh_vrf_detail = self._send_command("show vrf detail")
        show_ip_int_br = self._send_command("show ip interface brief")

        # retrieve all interfaces for the default VRF
        interface_dict = {}
        show_ip_int_br = show_ip_int_br.strip()
        for line in show_ip_int_br.splitlines():
            if "Interface " in line:
                continue
            # interface = line.split()[0]
            # Bug for IOS-XE fixing + adding interfaces in canonical_map.py for canonical_interface_name()
            **interface = canonical_interface_name(line.split()[0]) # See in helpers.py**
            interface_dict[interface] = {}

        instances["default"] = {
            "name": "default",
            "type": "DEFAULT_INSTANCE",
            "state": {"route_distinguisher": ""},
            "interfaces": {"interface": interface_dict},
        }

        # No vrf is defined return default one
        if len(sh_vrf_detail) == 0:
            if name:
                raise ValueError("No vrf is setup on router")
            else:
                return instances

        for vrf in sh_vrf_detail.split("\n\n"):

            first_part = vrf.split("Address family")[0]

            # retrieve the name of the VRF and the Route Distinguisher
            vrf_name, RD = re.match(r"^VRF (\S+).*RD (.*);", first_part).groups()
            if RD == "<not set>":
                RD = ""

            # retrieve the interfaces of the VRF
            if_regex = re.match(r".*Interfaces:(.*)", first_part, re.DOTALL)
            if "No interfaces" in first_part:
                interfaces = {}
            else:
                interfaces = {
                    canonical_interface_name(itf, {"Vl": "Vlan"}): {}
                    for itf in if_regex.group(1).split()
                }

            # remove interfaces in the VRF from the default VRF
            for item in interfaces:
                del instances["default"]["interfaces"]["interface"][item]

            instances[vrf_name] = {
                "name": vrf_name,
                "type": "L3VRF",
                "state": {"route_distinguisher": RD},
                "interfaces": {"interface": interfaces},
            }
        try:
            return instances if not name else instances[name]
        except AttributeError:
            raise ValueError("The vrf %s does not exist" % name)

Also in our enterprise we use Catalysts 9k and I recommend to add some additional interfaces in canonical_map.py:
base_interfaces = {
...
    "TwentyFiveGigabitEthernet": "TwentyFiveGigabitEthernet",   #Manual addition
    "TwentyFiveGigEthernet": "TwentyFiveGigabitEthernet",   #Manual addition
    "TwentyFiveGigEth": "TwentyFiveGigabitEthernet", #Manual addition
    "TwentyFiveGigE": "TwentyFiveGigabitEthernet",    #Manual addition
    "TwentyFiveGig": "TwentyFiveGigabitEthernet",   #Manual addition
    "Twe": "TwentyFiveGigabitEthernet", #Manual addition
    "FiveGigabitEthernet": "FiveGigabitEthernet",   #Manual addition
    "FiveGigEthernet": "FiveGigabitEthernet",   #Manual addition
    "FiveGigEth": "FiveGigabitEthernet", #Manual addition
    "FiveGigE": "FiveGigabitEthernet",    #Manual addition
    "FiveGig": "FiveGigabitEthernet",   #Manual addition
    "Fi": "FiveGigabitEthernet",    #Manual addition
...
}

**Comment by deiliet** [comment]
> My version of fixing bug - handle canonical_interface_name() to form long names of interfaces int both dictionaries:
> -interface_dict
> -instances
> 
> def get_network_instances(self, name=""):
> 
> ```
>     instances = {}
>     sh_vrf_detail = self._send_command("show vrf detail")
>     show_ip_int_br = self._send_command("show ip interface brief")
> 
>     # retrieve all interfaces for the default VRF
>     interface_dict = {}
>     show_ip_int_br = show_ip_int_br.strip()
>     for line in show_ip_int_br.splitlines():
>         if "Interface " in line:
>             continue
>         # interface = line.split()[0]
>         # Bug for IOS-XE fixing + adding interfaces in canonical_map.py for canonical_interface_name()
>         interface = canonical_interface_name(line.split()[0]) # See in helpers.py
>         interface_dict[interface] = {}
> 
>     instances["default"] = {
>         "name": "default",
>         "type": "DEFAULT_INSTANCE",
>         "state": {"route_distinguisher": ""},
>         "interfaces": {"interface": interface_dict},
>     }
> 
>     # No vrf is defined return default one
>     if len(sh_vrf_detail) == 0:
>         if name:
>             raise ValueError("No vrf is setup on router")
>         else:
>             return instances
> 
>     for vrf in sh_vrf_detail.split("\n\n"):
> 
>         first_part = vrf.split("Address family")[0]
> 
>         # retrieve the name of the VRF and the Route Distinguisher
>         vrf_name, RD = re.match(r"^VRF (\S+).*RD (.*);", first_part).groups()
>         if RD == "<not set>":
>             RD = ""
> 
>         # retrieve the interfaces of the VRF
>         if_regex = re.match(r".*Interfaces:(.*)", first_part, re.DOTALL)
>         if "No interfaces" in first_part:
>             interfaces = {}
>         else:
>             interfaces = {
>                 canonical_interface_name(itf, {"Vl": "Vlan"}): {}
>                 for itf in if_regex.group(1).split()
>             }
> 
>         # remove interfaces in the VRF from the default VRF
>         for item in interfaces:
>             del instances["default"]["interfaces"]["interface"][item]
> 
>         instances[vrf_name] = {
>             "name": vrf_name,
>             "type": "L3VRF",
>             "state": {"route_distinguisher": RD},
>             "interfaces": {"interface": interfaces},
>         }
>     try:
>         return instances if not name else instances[name]
>     except AttributeError:
>         raise ValueError("The vrf %s does not exist" % name)
> ```
> 
> Also in our enterprise we use Catalysts 9k and I recommend to add some additional interfaces in canonical_map.py:
> base_interfaces = {
> ...
> "TwentyFiveGigabitEthernet": "TwentyFiveGigabitEthernet", #Manual addition
> "TwentyFiveGigEthernet": "TwentyFiveGigabitEthernet", #Manual addition
> "TwentyFiveGigEth": "TwentyFiveGigabitEthernet", #Manual addition
> "TwentyFiveGigE": "TwentyFiveGigabitEthernet", #Manual addition
> "TwentyFiveGig": "TwentyFiveGigabitEthernet", #Manual addition
> "Twe": "TwentyFiveGigabitEthernet", #Manual addition
> "FiveGigabitEthernet": "FiveGigabitEthernet", #Manual addition
> "FiveGigEthernet": "FiveGigabitEthernet", #Manual addition
> "FiveGigEth": "FiveGigabitEthernet", #Manual addition
> "FiveGigE": "FiveGigabitEthernet", #Manual addition
> "FiveGig": "FiveGigabitEthernet", #Manual addition
> "Fi": "FiveGigabitEthernet", #Manual addition
> ...
> }

But now on Catalyst 9k I have another issue:

Traceback (most recent call last):
  File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
  File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\napalm\ios\ios.py", line 3433, in get_network_instances
    del instances["default"]["interfaces"]["interface"][item]
KeyError: 'LI10/2'

I think I need to make a condition to delete it from dictionary.

![image](https://user-images.githubusercontent.com/41358737/104957111-94439180-59de-11eb-938f-8541763457e9.png)

**Comment by deiliet** [comment]
> > My version of fixing bug - handle canonical_interface_name() to form long names of interfaces int both dictionaries:
> > -interface_dict
> > -instances
> 
> But now on Catalyst 9k I have another issue. I see one service interface "LI10/2" in "show vrf detail", that I don't need to handle.
> 
> Traceback (most recent call last):
> File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\nornir\core\task.py", line 98, in start
> r = self.task(self, **self.params)
> File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_get.py", line 44, in napalm_get
> result[g] = method(**options)
> File "C:\Users\Deiliet\Documents\GitHub\PycharmProjects\Nornir_Netbox\venv\lib\site-packages\napalm\ios\ios.py", line 3433, in get_network_instances
> del instances["default"]["interfaces"]["interface"][item]
> KeyError: 'LI10/2'
> 
> I think I need to make a condition to delete it from dictionary because I don't see it in "show ip interface brief".
> 
> ![image](https://user-images.githubusercontent.com/41358737/104957111-94439180-59de-11eb-938f-8541763457e9.png)

I think we can do this througt if-condition:

            for item in interfaces:
                if "LI" in item:
                    continue
                del instances["default"]["interfaces"]["interface"][item]
