### ISSUE TITLE
NAPALM didn''t catch this exception.

### ISSUE THREAD

**Issue by privatefire** [napalm-automation/napalm#1383]
Hey im quite new to using napalm and is trying to run it in stackstorm, however this error keeps cropping up when i try the Napalm.ping action. Can you help explain whether is it a host issue or something else

File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/jnpr/junos/device.py", line 1264, in open
    self.__class__.ON_JUNOS})
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/ncclient/manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/ncclient/manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 275, in connect
    for res in socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 334, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 193, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/ping.py", line 10, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/napalm/base/base.py", line 50, in __enter__
    self.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/napalm/junos/junos.py", line 126, in open
    self.device.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python3.6/site-packages/jnpr/junos/device.py", line 1298, in open
    raise EzErrors.ConnectUnknownHostError(self)
jnpr.junos.exception.ConnectUnknownHostError: ConnectUnknownHostError(w109ys23z2)
"
  stdout: 'NAPALM didn''t catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
    Don''t forget to include this traceback.

**Comment by ktbyers** [comment]
I looks like you are trying to connect to a hostname that doesn't exist in DNS (or are providing the arguments improperly such that you are not passing in the hostname properly).

**Comment by privatefire** [comment]
Hey @ktbyers  ive resolve that issue but im now facing with this error "jnpr.junos.exception.ConnectError: ConnectError(host: xxx.xxx.xxx.com, msg: Unexpected session close)" can you confirm if this is due to some missing dependencies or some network issue?
