### ISSUE TITLE
napalm merge_config on nxos_ssh driver failing with generic "Error while applying config!"

### ISSUE THREAD

**Issue by dzitzels1** [napalm-automation/napalm#1384]
### Description of Issue/Question

merge_config returns generic error: **"Error while applying config!"**

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
ubuntu@salt:/$ pip3 freeze | grep napalm
napalm==3.2.0
ubuntu@salt:/$

```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
switch1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2019, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Nexus 9000v is a demo version of the Nexus Operating System

Software
  BIOS: version
 NXOS: version 9.2(4)
  BIOS compile time:
  NXOS image file is: bootflash:///nxos.9.2.4.bin
  NXOS compile time:  8/20/2019 7:00:00 [08/20/2019 15:52:22]


Hardware
  cisco Nexus9000 9000v Chassis
  Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz with 8161760 kB of memory.
  Processor Board ID 9QYFFDX3X2Y

  Device name: switch1
  bootflash:    3509454 kB
Kernel uptime is 2 day(s), 0 hour(s), 45 minute(s), 38 second(s)

Last reset
  Reason: Unknown
  System version:
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

switch1# 

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
================= Traceback =================

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/nxos/nxos.py", line 152, in _commit_merge
    raise MergeConfigException("Error while applying config!")
napalm.base.exceptions.MergeConfigException: Error while applying config!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 293, in run_tests
    configuration_change(device, args.config_file, args.strategy, args.dry_run)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 244, in configuration_change
    call_commit_config(device)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 230, in call_commit_config
    return device.commit_config(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/nxos/nxos.py", line 229, in commit_config
    self._commit_merge()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/nxos/nxos.py", line 158, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'Error while applying config!'
ubuntu@salt:/srv/salt/templates$

```
This is my complete list of pip3 installed modules:

ubuntu@salt:/$ pip3 list
Package                Version
---------------------- --------------------
apache-libcloud        2.8.0
attrs                  19.3.0
Automat                0.8.0
bcrypt                 3.2.0
blinker                1.4
certifi                2019.11.28
cffi                   1.14.5
chardet                3.0.4
CherryPy               8.9.1
ciscoconfparse         1.5.29
Click                  7.0
cloud-init             20.4
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
croniter               0.3.29
cryptography           2.8
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
dnspython              2.1.0
entrypoints            0.3
future                 0.18.2
gitdb2                 2.0.6
GitPython              3.0.7
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
junos-eznc             2.5.4
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
lockfile               0.12.2
lxml                   4.6.2
MarkupSafe             1.1.0
more-itertools         4.2.0
msgpack                0.6.2
napalm                 3.2.0
ncclient               0.6.9
netaddr                0.7.19
netifaces              0.10.4
netmiko                3.3.3
ntc-templates          1.6.0
oauthlib               3.1.0
paramiko               2.7.2
passlib                1.7.4
pexpect                4.6.0
pip                    20.0.2
psutil                 5.5.1
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycparser              2.20
pycrypto               2.6.1
pycryptodomex          3.6.1
pyeapi                 0.8.4
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pynxos                 0.0.5
pyOpenSSL              19.0.0
pyparsing              2.4.7
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.4
python-dateutil        2.7.3
python-debian          0.1.36ubuntu1
python-gnupg           0.4.5
pytz                   2019.3
PyYAML                 5.3.1
pyzmq                  18.1.1
repoze.lru             0.7
requests               2.22.0
requests-unixsocket    0.2.0
Routes                 2.4.1
salt                   3002.2
scp                    0.13.3
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
smmap2                 2.0.5
sos                    4.0
ssh-import-id          5.10
systemd-python         234
tenacity               6.3.1
textfsm                1.1.0
transitions            0.8.7
Twisted                18.9.0
ubuntu-advantage-tools 20.3
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
wadllib                1.3.3
WebOb                  1.8.5
wheel                  0.34.2
yamlordereddictloader  0.4.0
zipp                   1.0.0
zope.interface         4.7.1
ubuntu@salt:/$

And here is my installed Python version:

ubuntu@salt:/$ python3 --version
Python 3.8.5
ubuntu@salt:/$

Here is my list of enabled NXOS features:

switch1# show feature
Feature Name          Instance  State
--------------------  --------  --------
nxapi                  1          enabled   <===== Required
scpServer              1          enabled   <===== Required
sshServer              1          enabled
switch1#

And I can do a 'get_facts' with my switch:
ubuntu@salt:/$ napalm --vendor nxos_ssh --user <my_username> --password <my_password> --optional_args "port=<my_ssh_port>" <my_hostname> call get_facts
{
    "uptime": 174516,
    "vendor": "Cisco",
    "os_version": "9.2(4)",

... output cut for brevity

}

Note: I originally attempted this in Salt however to simply the issue and rule out Salt as a contributor, I ran the commands natively on the napalm command-line.

**Comment by dzitzels1** [comment]
I found that this was an ssh/scp configuration issue.  My switch is older so I had to create an ssh profile with the proper Kex and cipher negotiations.

ubuntu@host:~$ sudo cat /root/.ssh/config
Host myhost
        Hostname myhost.mydomain.com
        User myuser
        Port 22
        Protocol 2
        Ciphers aes256-cbc
        KexAlgorithms diffie-hellman-group14-sha1
        IdentityFile /etc/salt/mydevice_id_rsa

**Comment by dzitzels1** [comment]
[https://community.cisco.com/t5/network-management/open-ssh/td-p/3930558](url)

That was link was also helpful in understanding this issu.
