### ISSUE TITLE
Control Plane Interface on 6509 "show interfaces" throws ValueError

### ISSUE THREAD

**Issue by rnwolfe** [napalm-automation/napalm#1410]
### Description of Issue/Question

Certain IOS Platforms have begun showing the control plane as an interface in `show interfaces` output and the NAPALM IOS Driver doesn't know how to handle this interface causing an exit as it doesn't match the existing interface patterns in the IOS driver. 

This is news to me and the first time I've ever seen it before on a switch. In this specific case it is a **WS-6509-E** running **Version 12.2(18)SXD4**. Haven't come across it otherwise.

Here's the problem interface:

```
Control Plane Interface is down, line protocol is down
  Hardware is Control-Plane, address is 0000.0000.0000 (bia 0000.0000.0000)
  MTU 0 bytes, BW 10000000 Kbit, DLY 0 usec,
     reliability 0/255, txload 1/255, rxload 1/255
  Encapsulation UNKNOWN, loopback not set
  ARP type: ARPA, ARP Timeout 00:00:00
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
  L2 Switched: ucast: 0 pkt, 0 bytes - mcast: 0 pkt, 0 bytes
  L3 in Switched: ucast: 0 pkt, 0 bytes - mcast: 0 pkt, 0 bytes mcast
  L3 out Switched: ucast: 0 pkt, 0 bytes mcast: 0 pkt, 0 bytes
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicast)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 interface resets
     0 output buffer failures, 0 output buffers swapped out
```

and the platform it showed up on:

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
$ pip freeze | grep napalm
napalm==3.2.0
nornir-napalm==0.1.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
device#show inv
NAME: "WS-C6509-E", DESCR: "Cisco Systems Catalyst 6500 9-slot Chassis System"
PID: WS-C6509-E        , VID: V02, SN: SMG0920N07C
<snipped>

device#show ver
Cisco Internetwork Operating System Software
IOS (tm) s72033_rp Software (s72033_rp-JK9SV-M), Version 12.2(18)SXD4, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2005 by cisco Systems, Inc.
Compiled Tue 22-Mar-05 14:45 by yiyan
Image text-base: 0x4002100C, data-base: 0x42690000

ROM: System Bootstrap, Version 12.2(17r)S2, RELEASE SOFTWARE (fc1)
BOOTLDR: s72033_rp Software (s72033_rp-JK9SV-M), Version 12.2(18)SXD4, RELEASE SOFTWARE (fc1)

Device uptime is 8 years, 38 weeks, 3 days, 12 hours, 3 minutes
Time since device switched to active is 8 years, 38 weeks, 3 days, 12 hours, 15 minutes
System returned to ROM by unknown reload cause - suspect boot_data[BOOT_COUNT] 0x0, BOOT_COUNT 0, BOOTDATA 19 (SP by power-on)
System restarted at 01:24:48 EDT Sat Jun 30 2012
System image file is "sup-bootflash:s72033-jk9sv-mz.122-18.SXD4.bin"

cisco WS-C6509-E (R7000) processor (revision 1.1) with 458720K/65536K bytes of memory.
Processor board ID SMG0920N07C
SR71000 CPU at 600Mhz, Implementation 0x504, Rev 1.2, 512KB L2 Cache
Last reset from power-on
Bridging software.
X.25 software, Version 3.0.0.
SuperLAT software (copyright 1990 by Meridian Technology Corp).
TN3270 Emulation software.
4 Ethernet/IEEE 802.3 interface(s)
60 Virtual Ethernet/IEEE 802.3  interface(s)
98 Gigabit Ethernet/IEEE 802.3 interface(s)
4 Gigabit Ethernet/IEEE 802.3 interface(s)
1917K bytes of non-volatile configuration memory.
8192K bytes of packet buffer memory.

65536K bytes of Flash internal SIMM (Sector size 512K).
Configuration register is 0x2102
```

### Steps to Reproduce the Issue
On a platform showing a `Control Plane Interface`, run `get_interfaces()`.

I realize this is a specific case and likely not reproducible without hardware, but it's simply where I came across it. 
### Error Traceback
(Paste the complete traceback of the exception between quotes below)
I was using NAPALM via the `nornir-napalm` plugin for `nornir` but you can see the error originates in the NAPALM IOS drivers (`\site-packages\napalm\ios\ios.py`). 
```
Traceback (most recent call last):
  File "C:\Users\aholl\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\aholl\AppData\Local\Programs\Python\Python39\lib\site-packages\nornir_napalm\plugins\tasks\napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
  File "C:\Users\aholl\AppData\Local\Programs\Python\Python39\lib\site-packages\napalm\ios\ios.py", line 1131, in get_interfaces
    raise ValueError(
ValueError: ('Interface attributes were                                       found without any known interface', '  MTU 0 bytes, BW 10000000 Kbit, DLY 0 usec, ')
```

There code that handles this is here: 
https://github.com/napalm-automation/napalm/blob/a84793b963de44df1fc40cd34cb6d9c6db0a7c8a/napalm/ios/ios.py#L1089-L1108
and can be fixed by adding a third regex to match this interface.

**Comment by rnwolfe** [comment]
I'm going to open a PR for this shortly, but for anyone looking for a quick fix to this you can modify the `napalm/napalm/ios/ios.py` file (around line 1082 in release 3.2.0) to this:

```python
        for line in output.splitlines():
            interface_regex_1 = r"^(\S+?)\s+is\s+(.+?),\s+line\s+protocol\s+is\s+(\S+)"
            interface_regex_2 = r"^(\S+)\s+is\s+(up|down)"
            # >>>> Add the below line and modify the following for loop to add interface_regex_3
            interface_regex_3 = r"^(Control Plane Interface)\s+is\s+(.+?),\s+line\s+protocol\s+is\s+(\S+)"
            for pattern in (interface_regex_1, interface_regex_2, interface_regex_3):
                interface_match = re.search(pattern, line)
                if interface_match:
                    interface = interface_match.group(1)
                    status = interface_match.group(2)
                    try:
                        protocol = interface_match.group(3)
                    except IndexError:
                        protocol = ""
                    if "admin" in status.lower():
                        is_enabled = False
                    else:
                        is_enabled = True
                    if protocol:
                        is_up = bool("up" in protocol)
                    else:
                        is_up = bool("up" in status)
                    break
```
