### ISSUE TITLE
scp.SCPException: Privilege denied.

### ISSUE THREAD

**Issue by tennd0** [napalm-automation/napalm#1517]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.3.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, C3560E Software (C3560E-UNIVERSALK9-M), Version 15.0(1)SE, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2011 by Cisco Systems, Inc.
Compiled Wed 20-Jul-11 09:21 by prod_rel_team

ROM: Bootstrap program is C3560E boot loader
BOOTLDR: C3560E Boot Loader (C3560E-HBOOT-M) Version 12.2(40r)EX9, RELEASE SOFTWARE (fc1)

scrapliSW uptime is 1 day, 15 hours, 42 minutes
System returned to ROM by power-on
System image file is "flash:c3560e-universalk9-mz.150-1.SE.bin"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Level: ipbase
License Type: Permanent
Next reload license Level: ipbase

cisco WS-C3560E-12D (PowerPC405) processor (revision A0) with 262144K bytes of memory.
Processor board ID FOC1334X0AA
Last reset from power-on
1 Virtual Ethernet interface
1 FastEthernet interface
24 Gigabit Ethernet interfaces
12 Ten Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 00:1F:6D:CF:91:80
Motherboard assembly number     : 73-11147-08
Motherboard serial number       : FOC13342KF1
Model revision number           : A0
Motherboard revision number     : A0
Model number                    : WS-C3560E-12D-S
Daughterboard assembly number   : 73-11149-03
Daughterboard serial number     : FOC132855XE
System serial number            : FOC1334X0AA
SFP Module assembly part number : 73-11148-04
SFP Module revision Number      : B0
Top Assembly Part Number        : 800-28906-01
Top Assembly Revision Number    : E0
Version ID                      : V01
CLEI Code Number                : COUIANJCAA
Daughterboard revision number   : A0
Hardware Board Revision Number  : 0x07


Switch Ports Model              SW Version            SW Image
------ ----- -----              ----------            ----------
*    1 36    WS-C3560E-12D      15.0(1)SE             C3560E-UNIVERSALK9-M


Configuration register is 0xF
```

### Steps to Reproduce the Issue
Trying to merge configurations on IOS device. I have AAA model with local authentication and authorization. I have also set privilege 15 on vty lines. 
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/root/napalmTest.py", line 18, in <module>
    device.load_merge_candidate(config='new_conf.cfg')
  File "/usr/local/lib/python3.9/dist-packages/napalm/ios/ios.py", line 316, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/napalm/ios/ios.py", line 270, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/usr/local/lib/python3.9/dist-packages/napalm/ios/ios.py", line 626, in _scp_file
    return self._xfer_file(
  File "/usr/local/lib/python3.9/dist-packages/napalm/ios/ios.py", line 698, in _xfer_file
    transfer.transfer_file()
  File "/usr/local/lib/python3.9/dist-packages/netmiko/scp_handler.py", line 363, in transfer_file
    self.put_file()
  File "/usr/local/lib/python3.9/dist-packages/netmiko/scp_handler.py", line 376, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/usr/local/lib/python3.9/dist-packages/netmiko/scp_handler.py", line 46, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/usr/local/lib/python3.9/dist-packages/scp.py", line 175, in put
    self._recv_confirm()
  File "/usr/local/lib/python3.9/dist-packages/scp.py", line 386, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Privilege denied.
```

**Comment by ktbyers** [comment]
Are you logging in with a privilege 15 user (alternatively you can pass in a `secret` and use `inline_transfer=True`
