### ISSUE TITLE
OSError: Search pattern never detected in send_command: (?:[>##]\s*$|.*all username.*confirm)

### ISSUE THREAD

**Issue by jaredmauck** [napalm-automation/napalm#1540]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.3.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.0(2)SE11, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2017 by Cisco Systems, Inc.
Compiled Sat 19-Aug-17 09:34 by prod_rel_team

ROM: Bootstrap program is C2960 boot loader
BOOTLDR: C2960 Boot Loader (C2960-HBOOT-M) Version 12.2(35r)SE2, RELEASE SOFTWARE (fc1)

SW1 uptime is 1 week, 1 day, 7 hours, 45 minutes
System returned to ROM by power-on
System restarted at 06:31:10 pacific Tue Dec 21 2021
System image file is "flash:c2960-lanbasek9-mz.150-2.SE11.bin"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.
          
cisco WS-C2960G-8TC-L (PowerPC405) processor (revision E0) with 65536K bytes of memory.
Processor board ID FOC1702Z45L
Last reset from power-on
2 Virtual Ethernet interfaces
8 Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

64K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : F0:29:29:19:7C:00
Motherboard assembly number     : 73-10613-08
Power supply part number        : 341-0208-02
Motherboard serial number       : FOC1702454B
Power supply serial number      : LIT16500SEL
Model revision number           : E0
Motherboard revision number     : C0
Model number                    : WS-C2960G-8TC-L
System serial number            : FOC1702Z45L
Top Assembly Part Number        : 800-28133-02
Top Assembly Revision Number    : G0
Version ID                      : V02
CLEI Code Number                : COM7S00ARB
Hardware Board Revision Number  : 0x01


Switch Ports Model              SW Version            SW Image                 
------ ----- -----              ----------            ----------               
*    1 8     WS-C2960G-8TC-L    15.0(2)SE11           C2960-LANBASEK9-M        
          

Configuration register is 0xF
```

### Steps to Reproduce the Issue
```
Using the python sample from: https://napalm.readthedocs.io/en/latest/tutorials/samples.html

I changed the driver from "eos" to "ios"
driver = napalm.get_network_driver("ios")

I changed the device variable
device = driver(
        hostname="sw1",
        username="cisco",
        password="cisco123",
        # optional_args={"port": 12443},

I then ran this command:
(3.9.7) jared@ansible-1:~/github/Ansible-Github/python$ python napalm_load_replace.py ../playbooks/configurations/napalm-configs/sw1.conf 

I'm able to see the Diff: and press y on commit.

After it tries to commit for a few moments, I get the traceback below.
```
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/home/jared/github/Ansible-Github/python/napalm_load_replace.py", line 67, in <module>
    main(config_file)
  File "/home/jared/github/Ansible-Github/python/napalm_load_replace.py", line 52, in main
    device.commit_config()
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/napalm/ios/ios.py", line 531, in commit_config
    output = self._commit_handler(cmd)
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/napalm/ios/ios.py", line 470, in wrapper
    return f(self, *args, **kwargs)
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/napalm/ios/ios.py", line 487, in _commit_handler
    output = self.device.send_command_expect(cmd, expect_string=patterns)
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/netmiko/base_connection.py", line 1582, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/jared/.venv/3.9.7/lib/python3.9/site-packages/netmiko/base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: (?:[>##]\s*$|.*all username.*confirm)
```

**Comment by jaredmauck** [comment]
This is now working, it was an issue with my config file.
