### ISSUE TITLE
Iosxr - calling a napalm method gets stucked

### ISSUE THREAD

**Issue by Kani999** [napalm-automation/napalm#1586]
### Description of Issue/Question

I've run into an error when calling `napalm` methods as `get_facts` or other, that getting the information from device get stuck. 
I tried to change the timeout, but even after 10 minutes, no response is returned.
I tried other `cisco iosxr` devices and it works fine, but the problem occurs only with the device described below.

Connecting to the device via `netmiko` went ok
```
from netmiko import ConnectHandler
dev = {
     'device_type': 'cisco_xr',
     'host':   IP_ADDRESS,
     'username': USERNAME,
     'password': PASSWORD,
}

net_connect = ConnectHandler(**dev)
net_connect.send_command('show version')

"""
Cisco IOS XR Software, Version 6.6.3[Default]
Copyright (c) 2019 by Cisco Systems, Inc.
...
"""
```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### napalm version
```
napalm==3.3.1
```

### Network operating system version
```
Cisco IOS XR Software, Version 6.6.3[Default]
Copyright (c) 2019 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 2.12(20170128:070504) [CRS ROMMON],

System image file is "disk0:hfr-os-mbi-6.6.3/0x100008/mbihfr-rp-x86e.vm"

cisco CRS-4/S (Intel 686 F6M14S4) processor with 6291456K bytes of memory.
Intel 686 F6M14S4 processor at 1728Mhz, Revision 2.174
Cisco CRS Series 4 Slots Line Card Chassis
```

### Steps to Reproduce the Issue
1. run `napalm --debug  --user USERNAME--password PASSWORD --vendor iosxr --optional_args "fast_cli=False"  IP_ADDRESS  call get_facts`

### Error Traceback

```
2022-03-16 08:54:00,870 - napalm - DEBUG - Starting napalm's debugging tool
2022-03-16 08:54:00,870 - napalm - DEBUG - Gathering napalm packages
2022-03-16 08:54:00,871 - napalm - DEBUG - napalm-asa==0.1.4
2022-03-16 08:54:00,871 - napalm - DEBUG - napalm-sros==0.1.0
2022-03-16 08:54:00,871 - napalm - DEBUG - napalm==3.3.1
2022-03-16 08:54:00,871 - napalm - DEBUG - get_network_driver - Calling with args: ('iosxr',), {}
2022-03-16 08:54:00,871 - napalm - DEBUG - get_network_driver - Successful
2022-03-16 08:54:00,871 - napalm - DEBUG - __init__ - Calling with args: (<class 'napalm.iosxr.iosxr.IOSXRDriver'>, 'IP_ADDRESS', 'USERNAME'), {'password': '*******', 'timeout': 60, 'optional_args': {'fast_cli': False}}
2022-03-16 08:54:00,871 - napalm - DEBUG - __init__ - Successful
2022-03-16 08:54:00,871 - napalm - DEBUG - pre_connection_tests - Calling with args: (<napalm.iosxr.iosxr.IOSXRDriver object at 0x7f72747bd220>,), {}
2022-03-16 08:54:00,871 - napalm - DEBUG - open - Calling with args: (<napalm.iosxr.iosxr.IOSXRDriver object at 0x7f72747bd220>,), {}
2022-03-16 08:54:12,914 - napalm - DEBUG - open - Successful
2022-03-16 08:54:12,915 - napalm - DEBUG - connection_tests - Calling with args: (<napalm.iosxr.iosxr.IOSXRDriver object at 0x7f72747bd220>,), {}
2022-03-16 08:54:12,915 - napalm - DEBUG - get_facts - Calling with args: (<napalm.iosxr.iosxr.IOSXRDriver object at 0x7f72747bd220>,), {}
2022-03-16 08:56:18,096 - napalm - ERROR - get_facts - Failed: Timeout exceeded!

================= Traceback =================

Traceback (most recent call last):
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/pyIOSXR/iosxr.py", line 309, in _send_command
    last_read = self.device.send_command_expect(
  File "/home/jankrupa/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1582, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: XML>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jankrupa/.local/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 287, in run_tests
    call_facts(device)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/base/clitools/cl_napalm.py", line 195, in call_facts
    facts = device.get_facts()
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/iosxr/iosxr.py", line 175, in get_facts
    facts_rpc_reply = ETREE.fromstring(self.device.make_rpc_call(facts_rpc_request))
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/pyIOSXR/iosxr.py", line 174, in make_rpc_call
    result = self._execute_rpc(rpc_command)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/pyIOSXR/iosxr.py", line 419, in _execute_rpc
    response = self._send_command(xml_rpc_command, delay_factor=delay_factor)
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/pyIOSXR/iosxr.py", line 344, in _send_command
    if not self._timeout_exceeded(start=start):
  File "/home/jankrupa/.local/lib/python3.8/site-packages/napalm/pyIOSXR/iosxr.py", line 221, in _timeout_exceeded
    raise TimeoutError(msg, self)
napalm.pyIOSXR.exceptions.TimeoutError: Timeout exceeded!

```

**Comment by ktbyers** [comment]
Do you have `xml agent tty` configured on the device?

What happens if you try to enter the `xml` shell manually (using the same account as your automation script uses):

```
RP/0/RP0/CPU0:iosxr3#xml
Wed Mar 16 16:01:31.784 UTC
XML>
```

Note, `exit` should get you out of the XML shell.

**Comment by Kani999** [comment]
`xml agent tty` is properly set up like `pyIOSXR` says (https://github.com/fooelisa/pyiosxr#usage).

You found the problem:
```
RP/0/RP0/CPU0:R-lab#xml
Thu Mar 17 07:39:27.708 MET
ERROR: 0xa3679c00 'XML Service Library' detected the 'fatal' condition 'The router is low on memory. Please retry the request after memory consumption has gone down.'
```

After freeing up the memory on the device, everything works fine.

Thank you
