### ISSUE TITLE
Failed to omport napalm module in CentOS 7

### ISSUE THREAD

**Issue by simo735** [napalm-automation/napalm#1614]
### Description of Issue/Question
Failed to import napalm module in centos7 server.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup

```
napalm==3.4.0
```

### Network operating system version

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
```

### Steps to Reproduce the Issue
pip install napalm
sudo yum install -y python-pip gcc openssl openssl-devel libffi-devel python-devel
sudo yum install -y python-pip gcc openssl openssl-devel libffi-devel python-devel
sudo yum install -y python-pip python-devel libxml2-devel libxslt-devel gcc openssl openssl-devel libffi-devel
python3.6 or python3.7 or python3.9
import napalm 

### Error Traceback

```
>>> import napalm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/srv-res-ansible/.local/lib/python3.6/site-packages/napalm/__init__.py", line 9, in <module>
    import napalm.eos
  File "/home/srv-res-ansible/.local/lib/python3.6/site-packages/napalm/eos/__init__.py", line 16, in <module>
    from napalm.eos.eos import EOSDriver
  File "/home/srv-res-ansible/.local/lib/python3.6/site-packages/napalm/eos/eos.py", line 34, in <module>
    import pyeapi
  File "/usr/local/lib/python3.6/site-packages/pyeapi/__init__.py", line 36, in <module>
    from .client import load_config, connect, connect_to, config_for
  File "/usr/local/lib/python3.6/site-packages/pyeapi/client.py", line 107, in <module>
    from pyeapi.utils import load_module, make_iterable, debug
  File "/usr/local/lib/python3.6/site-packages/pyeapi/utils.py", line 56, in <module>
    _syslog_handler = logging.handlers.SysLogHandler()
  File "/usr/lib64/python3.6/logging/handlers.py", line 831, in __init__
    ress = socket.getaddrinfo(host, port, 0, socktype)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by ktbyers** [comment]
Is `localhost` defined in the /etc/hosts on your system?

Can you `ping localhost` from the command line?

**Comment by simo735** [comment]
`localhost` wasn't defined in `/etc/hosts` and i can't `ping localhost` .
I correct that and the error has been resolved. Thanks for your help.
