### ISSUE TITLE
SSH key/passphrase support is broken Napalm 4.0 and EOS driver

### ISSUE THREAD

**Issue by jbotello7381** [napalm-automation/napalm#1748]
### Description of Issue/Question

New Napalm 4.0 support SSH transport on EOS driver, however when using ssh keys/passphrase, authentication fail.   After further debugging, it seems `optional args` are not mapped to `netmiko_optional_args`.

There are multiple ways to address the issue, one is import `netmiko_args` helper function

`from napalm.base.netmiko_helpers import netmiko_args` and include it as part of 

`class EOSDriver(NetworkDriver):` init function

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==4.0.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
arista-router#sh ver
Arista DCS-7280SR2-48YC6-F
Hardware version: 12.00
Serial number: JPE20362375
Hardware MAC address: d4af.f76c.0537
System MAC address: d4af.f76c.0537

Software image version: 4.26.3M
Architecture: i686
Internal build version: 4.26.3M-24689762.4263M
Internal build ID: 08dd4ce5-2990-47e1-a868-0eda9f88c763
Image format version: 1.0

Uptime: 42 weeks, 2 days, 3 hours and 28 minutes
Total memory: 8098984 kB
Free memory: 5693948 kB
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
(.venv) jbotello@netsalt-blv1:~/projects/napalm_testing$ /home/jbotello/projects/napalm_testing/.venv/bin/python /home/jbotello/projects/napalm_testing/arista.py
Traceback (most recent call last):
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/transport.py", line 1583, in auth_password
    return self.auth_interactive(username, handler)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/transport.py", line 1688, in auth_interactive
    return self.auth_handler.wait_for_response(my_event)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 1046, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/client.py", line 753, in _auth
    self._transport.auth_password(username, password)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/transport.py", line 1586, in auth_password
    raise e
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/transport.py", line 1564, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbotello/projects/napalm_testing/arista.py", line 26, in <module>
    main()
  File "/home/jbotello/projects/napalm_testing/arista.py", line 21, in main
    device.open()
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/napalm/eos/eos.py", line 203, in open
    self.device = self._netmiko_open(
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/napalm/base/base.py", line 113, in _netmiko_open
    self._netmiko_device = ConnectHandler(
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 365, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 439, in __init__
    self._open()
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 444, in _open
    self.establish_connection()
  File "/home/jbotello/projects/napalm_testing/.venv/lib/python3.8/site-packages/netmiko/base_connection.py", line 1083, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: arista_eos 10.10.10.10:22


Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']
```

**Comment by jbotello7381** [comment]
Running following code for testing
```
import napalm
from pprint import pprint
import logging
import sys

def main():

    driver = napalm.get_network_driver("eos")

    device = driver(
        hostname="10.10.10.10",
        username="jbotello",
        password="p@ssw0rd",
        optional_args= {
        "key_file": "/home/jbotello/.ssh/id_rsa",
        "use_keys": True,
        "transport": "ssh",
    },
    )

    import pdb; pdb.set_trace()
    
    device.open()
    pprint(device.get_facts())


if __name__ == "__main__":
    main()

```

Exploring `netmiko_optional_args`
```
(Pdb) device.netmiko_optional_args
{}
```

For testing purpose, i added `from napalm.base.netmiko_helpers import netmiko_args` on `eos.py` code

```
class EOSDriver(NetworkDriver):
    """Napalm driver for Arista EOS."""
   ### Removed some lines for clarity
    def __init__(self, hostname, username, password, timeout=60, optional_args=None):
        """
        Initialize EOS Driver.

        Optional args:
            * lock_disable (True/False): force configuration lock to be disabled (for external lock
                management).
            * enable_password (True/False): Enable password for privilege elevation
            * eos_autoComplete (True/False): Allow for shortening of cli commands
            * transport (string): pyeapi transport, defaults to eos_transport if set
                - socket
                - http_local
                - http
                - https
                - https_certs
                - A subclass of EapiConnection
                - a string that identifies a module and class that is a subclass of EapiConnection
                (from: https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/client.py#L115)

                transport is the preferred method
            * eos_transport (string): pyeapi transport, defaults to https
                eos_transport for backwards compatibility

        """
        self.device = None
        self.hostname = hostname
        self.username = username
        self.password = password
        self.timeout = timeout
        self.config_session = None
        self.locked = False
        self.cli_version = 1

        self.platform = "eos"
        self.profile = [self.platform]

        self._process_optional_args(optional_args or {})
        self.netmiko_optional_args = netmiko_args(optional_args) ### Added this as workaround and testing
```

Adding pdb breakpoint and running same code with `eos.py` workaround

```
-> device.open()
(Pdb) device.netmiko_optional_args
{'use_keys': True, 'key_file': '/home/jbotello/.ssh/id_rsa'}
(Pdb) 
```

Validation of workaround fix the ssh key authentication
```
(.venv) jbotello@netsalt-blv1:~/projects/napalm_testing$ /home/jbotello/projects/napalm_testing/.venv/bin/python /home/jbotello/projects/napalm_testing/arista.py
{'fqdn': 'arista-router',
 'hostname': '10.10.10.10',
 'interface_list': ['Ethernet1',
                    'Ethernet2',
                    'Ethernet3',
                    'Ethernet4',
                    'Ethernet5',
                    'Ethernet6',
                    'Ethernet7',
                    'Ethernet8',
                    'Ethernet9',
                    'Ethernet10',
                    'Ethernet11',
                    'Ethernet12',
                    'Ethernet13',
                    'Ethernet14',
                    'Ethernet15',
                    'Ethernet16',
                    'Ethernet17',
                    'Ethernet18',
                    'Ethernet19',
                    'Ethernet20',
                    'Ethernet21',
                    'Ethernet22',
                    'Ethernet23',
                    'Ethernet24',
                    'Ethernet25',
                    'Ethernet26',
                    'Ethernet27',
                    'Ethernet28',
                    'Ethernet29',
                    'Ethernet30',
                    'Ethernet31',
                    'Ethernet32',
                    'Ethernet33',
                    'Ethernet34',
                    'Ethernet35',
                    'Ethernet36',
                    'Ethernet37',
                    'Ethernet38',
                    'Ethernet39',
                    'Ethernet40',
                    'Ethernet41',
                    'Ethernet42',
                    'Ethernet43',
                    'Ethernet44',
                    'Ethernet45',
                    'Ethernet46',
                    'Ethernet47',
                    'Ethernet48',
                    'Ethernet49/1',
                    'Ethernet50/1',
                    'Ethernet51/1',
                    'Ethernet52/1',
                    'Ethernet53/1',
                    'Ethernet54/1',
                    'Loopback0',
                    'Management1',
                    'Vlan1000',
                    'Vlan1015',
                    'Vlan1100',
                    'Vlan1102',
                    'Vlan1110'],
 'model': 'DCS-7280SR2-48YC6-F',
 'os_version': '4.26.3M-24689762.4263M',
 'serial_number': 'JPE20362375',
 'uptime': 25588238.799216747,
 'vendor': 'Arista'}
 ```

**Comment by bewing** [comment]
Closed via #1750
