### ISSUE TITLE
NAPALM didn't catch this exception

### ISSUE THREAD

**Issue by davehs30** [napalm-automation/napalm#182]
Traceback (most recent call last):
  File "/usr/bin/cl_napalm_configure", line 9, in <module>
    load_entry_point('napalm==0.51.0', 'console_scripts', 'cl_napalm_configure')()
  File "/usr/lib/python2.7/site-packages/napalm/clitools/cl_napalm_configure.py", line 139, in main
    args.optional_args, args.config_file, args.dry_run))
  File "/usr/lib/python2.7/site-packages/napalm/clitools/cl_napalm_configure.py", line 111, in run
    with driver(hostname, user, password, optional_args=optional_args) as device:
  File "/usr/lib/python2.7/site-packages/napalm/base.py", line 40, in __enter__
    self.__raise_clean_exception(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/napalm/base.py", line 37, in __enter__
    self.open()
  File "/usr/lib/python2.7/site-packages/napalm/fortios.py", line 37, in open
    self.device.open()
  File "/usr/lib/python2.7/site-packages/pyFG/fortios.py", line 94, in open
    self.ssh.connect(**cfg)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 325, in connect
    t.start_client()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 492, in start_client
    raise e
socket.error: [Errno 104] Connection reset by peer

Command line execution:  cl_napalm_configure --user admin --vendor fortios --strategy merge --optional_args 'fortios_vdom=root' homefw_20160211_1053.conf howefw

Not seeing any connection attempts from the cl_napalm_configure in the firewall logs.

**Comment by dbarrosop** [comment]
There seems to be something wrong with paramiko. I have heard reports of people complaining lately about paramiko being broken. I will see if I can find more information about it.

**Comment by davehs30** [comment]
Thanks, paramiko version 1.7.7.1 is what I have installed.

**Comment by davehs30** [comment]
I think I see what is happening.  Ansible is sending /bin/sh  at the start of the connection,  The Fortigate firewall does not allow the user to start a shell.  How does one not have a shell called?

id 2\r\ndebug1: Sending command: /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'\r\ndebug2: channel 2:

**Comment by dbarrosop** [comment]
Ansible shouldn't be interacting with the device at all when using napalm. Did you add `connection: local` to your playbook?

**Comment by davehs30** [comment]
Thanks the "connection: local"  corrected that issue.  closing this issue
