### ISSUE TITLE
bgp nlri evpn not supported (junos)

### ISSUE THREAD

**Issue by fooelisa** [napalm-automation/napalm#191]
>>> print device.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/junos.py", line 307, in get_bgp_neighbors
    peer['address_family'] = self._parse_route_stats(neighbor_data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/junos.py", line 266, in _parse_route_stats
    family = self._get_address_family(table)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm-0.51.0-py2.7.egg/napalm/junos.py", line 258, in _get_address_family
    return address_family_mapping[family]
KeyError: 'evpn'

**Comment by dbarrosop** [comment]
This issue has been 'moved' to napalm-automation/napalm-junos#39
