### ISSUE TITLE
Caught exception still printed to stderr

### ISSUE THREAD

**Issue by ichilton** [napalm-automation/napalm#1950]
### Description of Issue/Question

Exception is still printed to stderr, even when it's caught by an exception handler.

### napalm version

```
$ pip freeze | grep napalm
napalm==4.1.0
```

### Steps to Reproduce the Issue

```
$ cat test.py
#!/usr/bin/env python3

import napalm

driver = napalm.get_network_driver("eos")

device = driver(
  hostname='192.168.1.1',
  username='',
  password=''
)

try:
  device.open()
  device.close()
except Exception as e:
  print('error')
```

```
$ ./test.py
[Errno 113] No route to host
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyeapi/eapilib.py", line 440, in send
    self.transport.endheaders(message_body=data)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
error
```

The output should just be "error".

**Comment by bewing** [comment]
This is an upstream library issue.

https://github.com/arista-eosplus/pyeapi/blob/bf9976fa840070360857c7fb7f637da2285407fa/pyeapi/eapilib.py#L472

Since they define a logger, but don't add a handler, a default handler sends the logged message to `stderr`.  You can redirect `stderr` to /dev/null, change the logging settings for the library's logger, or add a null handler to it:

```python
import logging

logging.getLogger('pyeapi.eapilib').setLevel(logging.CRITICAL + 1)
# or
logging.getLogger('pyeapi.eapilib').addHandler(logging.NullHandler())
```
