### ISSUE TITLE
NAPALM fails to install on python 3.12

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm#2020]
```
$ docker run -it --entrypoint /bin/bash python:3.12
Unable to find image 'python:3.12' locally
3.12: Pulling from library/python
8457fd5474e7: Pull complete
13baa2029dde: Pull complete
325c5bf4c2f2: Pull complete
7e18a660069f: Pull complete
98a59f0ffede: Pull complete
72c7f17f2221: Pull complete
2f40b346325a: Pull complete
f3f08e04e337: Pull complete
Digest: sha256:7b8d65a924f596eb65306214f559253c468336bcae09fd575429774563460caf
Status: Downloaded newer image for python:3.12
root@ed9a62ca64f3:/# pip install napalm
Collecting napalm
  Obtaining dependency information for napalm from https://files.pythonhosted.org/packages/aa/3f/2e286573ee75f742cc03ff19022bf121361871e71db2b7048e8d6cf22e4d/napalm-4.1.0-py2.py3-none-any.whl.metadata
  Downloading napalm-4.1.0-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: setuptools>=38.4.0 in /usr/local/lib/python3.12/site-packages (from napalm) (68.2.2)
Collecting cffi>=1.11.3 (from napalm)
  Obtaining dependency information for cffi>=1.11.3 from https://files.pythonhosted.org/packages/09/d4/8759cc3b2222c159add8ce3af0089912203a31610f4be4c36f98e320b4c6/cffi-1.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading cffi-1.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting paramiko>=2.6.0 (from napalm)
  Obtaining dependency information for paramiko>=2.6.0 from https://files.pythonhosted.org/packages/bb/8f/3cef65d3fe76e59f320405027d594a0332e44852fef722f0ee4e81e2e7e3/paramiko-3.3.1-py3-none-any.whl.metadata
  Downloading paramiko-3.3.1-py3-none-any.whl.metadata (4.4 kB)
Collecting requests>=2.7.0 (from napalm)
  Obtaining dependency information for requests>=2.7.0 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting future (from napalm)
  Downloading future-0.18.3.tar.gz (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 43.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting textfsm (from napalm)
  Downloading textfsm-1.1.3-py2.py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.7/44.7 kB 15.3 MB/s eta 0:00:00
Collecting jinja2 (from napalm)
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 43.5 MB/s eta 0:00:00
Collecting netaddr (from napalm)
  Obtaining dependency information for netaddr from https://files.pythonhosted.org/packages/68/4a/aa1a61a8cdfc533020012594b006bbb3e7680326e1c247f63e711be5ab76/netaddr-0.9.0-py3-none-any.whl.metadata
  Downloading netaddr-0.9.0-py3-none-any.whl.metadata (5.1 kB)
Collecting pyYAML (from napalm)
  Obtaining dependency information for pyYAML from https://files.pythonhosted.org/packages/b4/33/720548182ffa8344418126017aa1d4ab4aeec9a2275f04ce3f3573d8ace8/PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting pyeapi>=0.8.2 (from napalm)
  Downloading pyeapi-1.0.2.tar.gz (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.9/146.9 kB 48.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting netmiko>=4.1.0 (from napalm)
  Downloading netmiko-4.2.0-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 kB 51.9 MB/s eta 0:00:00
Collecting junos-eznc>=2.6.3 (from napalm)
  Obtaining dependency information for junos-eznc>=2.6.3 from https://files.pythonhosted.org/packages/17/cd/ddca585634433f9cbb21ddbb83d261816dd5c8b954763f9c35b1850c4d2a/junos_eznc-2.6.8-py2.py3-none-any.whl.metadata
  Downloading junos_eznc-2.6.8-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting scp (from napalm)
  Downloading scp-0.14.5-py2.py3-none-any.whl (8.7 kB)
Collecting lxml>=4.3.0 (from napalm)
  Obtaining dependency information for lxml>=4.3.0 from https://files.pythonhosted.org/packages/d8/e4/80ed0b5ac164fe452ceffb6733f008770e34878bc6f1104bb0f2266c1cb8/lxml-4.9.3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata
  Downloading lxml-4.9.3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting ncclient (from napalm)
  Downloading ncclient-0.6.15.tar.gz (634 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.9/634.9 kB 71.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ttp (from napalm)
  Obtaining dependency information for ttp from https://files.pythonhosted.org/packages/03/38/d475e7bde8d192ca5d64ccc0988f3d58f36211bd68c32b6c5883332a8abf/ttp-0.9.5-py2.py3-none-any.whl.metadata
  Downloading ttp-0.9.5-py2.py3-none-any.whl.metadata (9.6 kB)
Collecting ttp-templates (from napalm)
  Downloading ttp_templates-0.3.5-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 31.4 MB/s eta 0:00:00
Collecting netutils>=1.0.0 (from napalm)
  Obtaining dependency information for netutils>=1.0.0 from https://files.pythonhosted.org/packages/62/e2/14d63c32766f08bc5b02b4855148b035d99410e258589f347a16a691fcb8/netutils-1.6.0-py3-none-any.whl.metadata
  Downloading netutils-1.6.0-py3-none-any.whl.metadata (4.0 kB)
Collecting typing-extensions>=4.3.0 (from napalm)
  Obtaining dependency information for typing-extensions>=4.3.0 from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pycparser (from cffi>=1.11.3->napalm)
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 38.8 MB/s eta 0:00:00
Collecting ncclient (from napalm)
  Downloading ncclient-0.6.13.tar.gz (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.7/105.7 kB 38.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-86p2_xy9/ncclient_c5712c6215b241e9b3cff090e3ed6a35/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86p2_xy9/ncclient_c5712c6215b241e9b3cff090e3ed6a35/setup.py", line 45, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-86p2_xy9/ncclient_c5712c6215b241e9b3cff090e3ed6a35/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-86p2_xy9/ncclient_c5712c6215b241e9b3cff090e3ed6a35/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-86p2_xy9/ncclient_c5712c6215b241e9b3cff090e3ed6a35/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bewing** [comment]
pip is collecting `ncclient 0.6.13`, which is not compatible with Python 3.12.  I am not sure why `ncclient 0.6.15` is not being collected.  Will continue to dig.

**Comment by bewing** [comment]
found it: 

```
root@c0d9c0396c9c:/# pip install 'junos-eznc>=2.6.3'
Collecting junos-eznc>=2.6.3
  Downloading junos_eznc-2.6.8-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting lxml>=3.2.4 (from junos-eznc>=2.6.3)
  Downloading lxml-4.9.3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting ncclient==0.6.13 (from junos-eznc>=2.6.3)
  Downloading ncclient-0.6.13.tar.gz (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.7/105.7 kB 7.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-mz33hjkj/ncclient_becc83fa17c4471d8ed978aa1666ff4e/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mz33hjkj/ncclient_becc83fa17c4471d8ed978aa1666ff4e/setup.py", line 45, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-mz33hjkj/ncclient_becc83fa17c4471d8ed978aa1666ff4e/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-mz33hjkj/ncclient_becc83fa17c4471d8ed978aa1666ff4e/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-mz33hjkj/ncclient_becc83fa17c4471d8ed978aa1666ff4e/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bewing** [comment]
https://github.com/Juniper/py-junos-eznc/issues/1276

**Comment by bewing** [comment]
temporary workaround:
`pip install ncclient==0.6.15 napalm`
