### ISSUE TITLE
Verify that get_network_drivers works fine if install with `python setup.py install`

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#234]
There seems to be issue as reported in #232 where installing napalm with `python setup.py install` doesn't work properly.

**Comment by ktbyers** [comment]
FYI, I don't think I had any issue with this when I tried it earlier today (in a new virtualenv)?

**Comment by mirceaulinic** [comment]
@ktbyers When I saw your comment I just supposed that 13th of April was not my day.

So I tried again, on a completely new platform. Same behaviour:

```
Searching for napalm-junos
Reading https://pypi.python.org/simple/napalm-junos/
Best match: napalm-junos 0.1.1
Downloading https://pypi.python.org/packages/source/n/napalm-junos/napalm-junos-0.1.1.tar.gz#md5=a60fabc75907faa0a7537d62ff72e9d8
Processing napalm-junos-0.1.1.tar.gz
Writing /tmp/easy_install-fEtEmj/napalm-junos-0.1.1/setup.cfg
Running napalm-junos-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fEtEmj/napalm-junos-0.1.1/egg-dist-tmp-dQr26n
warning: no files found matching 'napalm_junos/utils/textfsm_templates/*.tpl'
zip_safe flag not set; analyzing archive contents...
napalm_junos.utils.junos_views: module references __file__
creating /usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_junos-0.1.1-py2.7.egg
Extracting napalm_junos-0.1.1-py2.7.egg to /usr/home/mircea/15apr/lib/python2.7/site-packages
Adding napalm-junos 0.1.1 to easy-install.pth file

Installed /usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_junos-0.1.1-py2.7.egg
Searching for napalm-iosxr
Reading https://pypi.python.org/simple/napalm-iosxr/
Best match: napalm-iosxr 0.1.1
Downloading https://pypi.python.org/packages/source/n/napalm-iosxr/napalm-iosxr-0.1.1.tar.gz#md5=4b4a600c495200fa550ad8cfabf4011f
Processing napalm-iosxr-0.1.1.tar.gz
Writing /tmp/easy_install-hpgLY7/napalm-iosxr-0.1.1/setup.cfg
Running napalm-iosxr-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hpgLY7/napalm-iosxr-0.1.1/egg-dist-tmp-ZPAnF8
zip_safe flag not set; analyzing archive contents...
Moving napalm_iosxr-0.1.1-py2.7.egg to /usr/home/mircea/15apr/lib/python2.7/site-packages
Adding napalm-iosxr 0.1.1 to easy-install.pth file

Installed /usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_iosxr-0.1.1-py2.7.egg
```


```
(15apr) [mircea@netops17 /usr/home/mircea/15apr/lib/python2.7/site-packages]$ ls -la | grep napalm
-rw-r--r--   1 mircea  mircea    2221 Apr 15 00:38 napalm-1.0.0-py2.7.egg
drwxr-xr-x   4 mircea  mircea     512 Apr 15 00:39 napalm_base-0.11.0-py2.7.egg
-rw-r--r--   1 mircea  mircea   24882 Apr 15 00:39 napalm_eos-0.1.1-py2.7.egg
-rw-r--r--   1 mircea  mircea   13577 Apr 15 00:39 napalm_fortios-0.1.1-py2.7.egg
-rw-r--r--   1 mircea  mircea    5918 Apr 15 00:39 napalm_ibm-0.1.1-py2.7.egg
-rw-r--r--   1 mircea  mircea   30147 Apr 15 00:38 napalm_ios-0.1.2-py2.7.egg
-rw-r--r--   1 mircea  mircea   27764 Apr 15 00:38 napalm_iosxr-0.1.1-py2.7.egg
drwxr-xr-x   4 mircea  mircea     512 Apr 15 00:38 napalm_junos-0.1.1-py2.7.egg
-rw-r--r--   1 mircea  mircea   15418 Apr 15 00:38 napalm_nxos-0.1.1-py2.7.egg
-rw-r--r--   1 mircea  mircea    7995 Apr 15 00:38 napalm_pluribus-0.1.1-py2.7.egg
```

```
>>> import napalm
>>> napalm.get_network_driver('junos')
<class napalm_junos.junos.JunOSDriver at 0x805d95600>
>>> napalm.get_network_driver('iosxr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 167, in get_network_driver
    mod = _load_module(_napalm_namespace(module))
  File "/usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 94, in _load_module
    mod = _import_module(name)
  File "/usr/home/mircea/15apr/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 52, in _import_module
    fhandle, path, descr = imp.find_module(part, path)
ImportError: No module named napalm_iosxr
>>> import napalm_iosxr
>>> napalm.get_network_driver('iosxr')
<class napalm_iosxr.iosxr.IOSXRDriver at 0x805ef2c18>
```

I just might be the lucky one :-|

**Comment by ktbyers** [comment]
Okay, let me check again and see what I see.

**Comment by ktbyers** [comment]
@mirceaulinic @dbarrosop Okay, this also fails on Cisco IOS. 

import napalm works, but when I try to use a napalm program, I get:

```python
Traceback (most recent call last):
  File "./napalm_ios_test.py", line 77, in <module>
    main()
  File "./napalm_ios_test.py", line 18, in main
    driver = get_network_driver('ios')
  File "/home/gituser/VENV/napalm_meta3/local/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 167, in get_network_driver
    mod = _load_module(_napalm_namespace(module))
  File "/home/gituser/VENV/napalm_meta3/local/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 94, in _load_module
    mod = _import_module(name)
  File "/home/gituser/VENV/napalm_meta3/local/lib/python2.7/site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/__init__.py", line 52, in _import_module
    fhandle, path, descr = imp.find_module(part, path)
ImportError: No module named napalm_ios
```

The error looks like it is in this code:

napalm_base/__init__.py
```python
    parts = name.split('.')
    path = None
    module_name = ''
    fhandle = None

    for index, part in enumerate(parts):
        module_name = part if index == 0 else '%s.%s' % (module_name, part)
        path = [path] if path is not None else path
        if path is not None:
            path = [path]
        else:
            path

        try:
            fhandle, path, descr = imp.find_module(part, path)
            if module_name in sys.modules:
                # since imp.load_module works like reload, need to be sure not
                # to reload a previously loaded module
                mod = sys.modules[module_name]
            else:
                mod = imp.load_module(module_name, fhandle, path, descr)
        finally:
            # lets be sure to clean up after ourselves
            if fhandle:
                fhandle.close()

    return mod
```

PATH is always None so I am guessing it fails if napalm_base and napalm_ios do not share the same common directory. python setup.py install (in my case tries to use the following):

./site-packages/napalm_base-0.11.0-py2.7.egg/napalm_base/


FYI, this fixed the problem on in both cases pip install and python setup.py install.

In get_network_driver:

```python
    #mod = _load_module(_napalm_namespace(module))
    mod = __import__("napalm_{}".format(module))
```

Of course that bypasses all the dynamic loading code that @privateip added.

Do we need the dynamic loading code? What is an example use case for it? Will it work with the new separate repositories?

**Comment by privateip** [comment]
The problem you are seeing is related to zip (egg) files.  The dynamic import library wasn't designed with that in mind; however, its not a difficult addition to make.   Using __import__ is okay but it only imports the __init__.py file so if you have a package it could cause unintended behavior and is relatively frowned upon by PEP302.  Of course all of this goes away in py3 as the import libraries are *substantially* better.

Taken from __import__ docstring

```
Import a module. Because this function is meant for use by the Python interpreter and 
not for general use it is better to use importlib.import_module() to programmatically 
import a module.
```

I can update the loader to support zip files hopefully soon, but wanted to document here so every one knows what the problem is and if someone can tackle it sooner great.

ref: https://www.python.org/dev/peps/pep-0302/
ref: http://stackoverflow.com/questions/28962344/imp-find-module-which-supports-zipped-eggs

**Comment by mirceaulinic** [comment]
Proposed fix: https://github.com/napalm-automation/napalm-base/pull/24

**Comment by dbarrosop** [comment]
Now it works fine with the proposed fix : )
