### ISSUE TITLE
Changes to FortiOS fails.

### ISSUE THREAD

**Issue by davehs30** [napalm-automation/napalm#253]
python cl_napalm_configure.py --user dsmith --password ***** --strategy replace --vendor fortios --strategy replace  --optional_args "fortios_vdom=root" --debug /root/fortigate/compiled/homefw/new.conf homefw
2016-05-17 08:42:05,717 - cl-napalm-config.py - DEBUG - Getting driver for OS "fortios"
2016-05-17 08:42:05,830 - cl-napalm-config.py - DEBUG - Connecting to device "homefw" with user "dsmith" and optional_args={'fortios_vdom': 'root'}
2016-05-17 08:42:06,246 - cl-napalm-config.py - DEBUG - Strategy for loading configuration is "replace"
2016-05-17 08:42:06,246 - cl-napalm-config.py - DEBUG - Loading configuration file "/root/fortigate/compiled/homefw/new.conf"
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "cl_napalm_configure.py", line 144, in <module>
    main()
  File "cl_napalm_configure.py", line 139, in main
    args.optional_args, args.config_file, args.dry_run))
  File "cl_napalm_configure.py", line 131, in run
    return diff
  File "/usr/lib/python2.7/site-packages/napalm_base/base.py", line 51, in __exit__
    self.__raise_clean_exception(exc_type, exc_value, exc_traceback)
  File "cl_napalm_configure.py", line 119, in run
    strategy_method(filename=config_file)
  File "/usr/lib/python2.7/site-packages/napalm_fortios/fortios.py", line 93, in load_replace_candidate
    self.device.load_config(empty_candidate=True)
  File "/usr/lib/python2.7/site-packages/pyFG/fortios.py", line 217, in load_config
    config_text = self.execute_command(command)
  File "/usr/lib/python2.7/site-packages/pyFG/fortios.py", line 134, in execute_command
    for e in error_chan.read():
  File "/usr/lib/python2.7/site-packages/paramiko/file.py", line 192, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1246, in _read
    return self.channel.recv_stderr(size)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 663, in recv_stderr
    raise socket.timeout()
socket.timeout

**Comment by dbarrosop** [comment]
Issue moved to [napalm-automation/napalm-fortios #2](https://github.com/napalm-automation/napalm-fortios/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by dbarrosop** [comment]
Sorry, was testing the `move` feature but I think it's not worth as it's just a hack. Reopening here.

**Comment by dbarrosop** [comment]
This issue has been 'moved' to napalm-automation/napalm-fortios#6
