### ISSUE TITLE
cl_napalm_configure iosxr error

### ISSUE THREAD

**Issue by thorko** [napalm-automation/napalm#351]
cl_napalm_configure --vendor iosxr  --debug -o 'port=830' -s replace --user <user> <host> /tmp/config 
Enter password: 
2017-02-24 14:35:42,568 - cl-napalm-config.py - DEBUG - Getting driver for OS "iosxr"
2017-02-24 14:35:42,627 - cl-napalm-config.py - DEBUG - Connecting to device "172.16.102.6" with user "peter" and optional_args={u'port': u'830'}
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "/usr/bin/cl_napalm_configure", line 9, in <module>
    load_entry_point('napalm-base==0.23.0', 'console_scripts', 'cl_napalm_configure')()
  File "/usr/lib/python2.7/site-packages/napalm_base/clitools/cl_napalm_configure.py", line 59, in main
    args.optional_args, args.config_file, args.dry_run))
  File "/usr/lib/python2.7/site-packages/napalm_base/clitools/cl_napalm_configure.py", line 32, in run
    with driver(hostname, user, password, optional_args=optional_args) as device:
  File "/usr/lib/python2.7/site-packages/napalm_base/base.py", line 54, in __enter__
    self.__raise_clean_exception(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/napalm_base/base.py", line 82, in __raise_clean_exception
    raise exc_value
paramiko.ssh_exception.SSHException: Channel closed.

All versions of napalm are the latest

**Comment by dbarrosop** [comment]
Two comments:

1. We will look into catching the exception to return a "standard one".
2. Don't connect using the netconf port. Netconf support in ios-xr is very limited so `napalm-iosxr` is using the xml agent within the standard ssh interface.

**Comment by ktbyers** [comment]
I am going to close this as it looks invalid (using NETCONF port and not `xml agent`).
