### ISSUE TITLE
CentOS7 Install Error

### ISSUE THREAD

**Issue by PackeTsar** [napalm-automation/napalm#380]
### Description of Issue/Question

Received the below when trying to install napalm on CentOS7

```
[root@CENT7 napalm]# pip install napalm
Collecting napalm
  Using cached napalm-1.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): napalm-base in /usr/lib/python2.7/site-packages (from napalm)
Collecting napalm-eos (from napalm)
  Using cached napalm-eos-0.5.6.tar.gz
Collecting napalm-fortios (from napalm)
  Using cached napalm-fortios-0.4.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): napalm-ios in /usr/lib/python2.7/site-packages (from napalm)
Collecting napalm-iosxr (from napalm)
  Using cached napalm-iosxr-0.4.8.tar.gz
Collecting napalm-junos (from napalm)
  Using cached napalm-junos-0.6.6.tar.gz
Collecting napalm-nxos (from napalm)
  Using cached napalm-nxos-0.5.2.tar.gz
Collecting napalm-pluribus (from napalm)
  Using cached napalm-pluribus-0.5.1.tar.gz
Collecting napalm-panos (from napalm)
  Using cached napalm-panos-0.4.0.tar.gz
Collecting napalm-ros (from napalm)
  Using cached napalm-ros-0.2.2.tar.gz
Collecting napalm-vyos (from napalm)
  Using cached napalm-vyos-0.1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): jtextfsm in /usr/lib/python2.7/site-packages (from napalm-base->napalm)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/lib/python2.7/site-packages (from napalm-base->napalm)
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/site-packages (from napalm-base->napalm)
Requirement already satisfied (use --upgrade to upgrade): pyYAML in /usr/lib64/python2.7/site-packages (from napalm-base->napalm)
Collecting pyeapi (from napalm-eos->napalm)
  Using cached pyeapi-0.8.0.tar.gz
Collecting pyFG>=0.49_1 (from napalm-fortios->napalm)
  Using cached pyfg-0.50.tar.gz
Collecting future (from napalm-fortios->napalm)
  Using cached future-0.16.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): netmiko>=1.4.0 in /usr/lib/python2.7/site-packages (from napalm-ios->napalm)
Collecting pyIOSXR>=0.20 (from napalm-iosxr->napalm)
  Using cached pyIOSXR-0.41.tar.gz
Collecting junos-eznc (from napalm-junos->napalm)
  Using cached junos-eznc-2.1.3.tar.gz
Collecting pynxos (from napalm-nxos->napalm)
  Using cached pynxos-0.0.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): scp in /usr/lib/python2.7/site-packages (from napalm-nxos->napalm)
Collecting pyPluribus (from napalm-pluribus->napalm)
  Using cached pyPluribus-0.3.1.tar.gz
Collecting pan-python (from napalm-panos->napalm)
  Using cached pan-python-0.12.0.tar.gz
Collecting requests-toolbelt (from napalm-panos->napalm)
  Using cached requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting xmltodict (from napalm-panos->napalm)
  Using cached xmltodict-0.11.0-py2.py3-none-any.whl
Collecting chainmap (from napalm-ros->napalm)
  Using cached chainmap-1.0.2-py2.py3-none-any.whl
Collecting librouteros>1.0.0 (from napalm-ros->napalm)
  Using cached librouteros-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_gbVc3/librouteros/setup.py", line 61, in <module>
        'Topic :: Software Development :: Libraries'
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=12.0.5'))
```

**Comment by PackeTsar** [comment]
Was able to work around it after running `pip install --upgrade setuptools --user python`

**Comment by ktbyers** [comment]
@PackeTsar You probably also should use a virtual environment (so you decouple from the system Python).

This will make it less likely for you to break the system and for the system upgrades to break your NAPALM install (as well as having different virtual environments when you upgrade and for other testing).

See here for some examples:

http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/
