### ISSUE TITLE
get_lldp_neighbors_detailed borked on Junos 15, MX series

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#428]
### Description of Issue/Question

Because F$%^&ng vendors and the RPC has been changed yet again. On MX series used to be `get-lldp-interface-neighbors-information`, now it's `get-lldp-interface-neighbors`.

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
0.12.0
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
15.1F7.3
```
MX series.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 154, in call
            kwargs.pop(karg)
          File "/usr/local/lib/python2.7/dist-packages/napalm_junos/junos.py", line 659, in get_lldp_neighbors_detail
            lldp_table.get(interface_name=interface)
          File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/factory/optable.py", line 64, in get
            self.xml = getattr(self.RPC, self.GET_RPC)(**rpc_args)
          File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 336, in _exec_rpc
            return self._junos.execute(rpc, **dec_args)
          File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 63, in wrapper
            result = function(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
            return function(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 736, in execute
            errs=ex)
        RpcError: RpcError(severity: error, bad_element: get-lldp-interface-neighbors-information, message: error: syntax error
        error: syntax error)
```

**Comment by ktbyers** [comment]
I think this is probably fixed. If it is still an issue, please re-open.
