### ISSUE TITLE
device connects successfully but methods give timeout error

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#433]
### Description of Issue/Question
I'm able to connect to a device successfully but when I issue a method like get_bgp_neighbors or get_facts I get a timeout error. The connection to the device remains active though.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[x ] Yes
[ ] No

### napalm-iosxr version
(Paste verbatim output from `pip freeze | grep napalm-iosxr` between quotes below)

```
napalm-iosxr==0.5.4
```

### IOS-XR version and platform details
(Paste the complete verbatim output from `show version brief` between quotes below)

```
#sh version brief
Wed Oct 11 16:18:04.270 EDT

Cisco IOS XR Software, Version 5.1.3[Default]
Copyright (c) 2016 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 0.73(c) 1994-2012 by Cisco Systems,  Inc.

gw1.fnc1 uptime is 4 weeks, 1 day, 8 hours, 50 minutes
System image file is "disk0:asr9k-os-mbi-5.1.3.sp10-1.0.0/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 6291456K bytes of memory.
Intel 686 F6M14S4 processor at 2127MHz, Revision 2.174
ASR 9006 AC Chassis with PEM Version 2

2 Management Ethernet
2 TenGigE
2 DWDM controller(s)
2 WANPHY controller(s)
503k bytes of non-volatile configuration memory.
6111M bytes of hard disk.
12510192k bytes of disk0: (Sector size 512 bytes).
12510192k bytes of disk1: (Sector size 512 bytes).
```

### Steps to Reproduce the Issue

```
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> dr = napalm.get_network_driver('iosxr')
>>> gw = dr('dev', 'user', 'passwd')
>>> gw.open()
>>> n = gw.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_iosxr/iosxr.py", line 351, in get_bgp_neighbors
    result_tree = ETREE.fromstring(self.device.make_rpc_call(rpc_command))
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 151, in make_rpc_call
    result = self._execute_rpc(rpc_command)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 365, in _execute_rpc
    response = self._send_command(xml_rpc_command, delay_factor=delay_factor)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 301, in _send_command
    if not self._timeout_exceeded(start=start):
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 190, in _timeout_exceeded
    raise TimeoutError(msg, self)
pyIOSXR.exceptions.TimeoutError: Timeout exceeded!
>>> gw.close()
>>> gw.open()
>>> facts = gw.get_facts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_iosxr/iosxr.py", line 193, in get_facts
    facts_rpc_reply = ETREE.fromstring(self.device.make_rpc_call(facts_rpc_request))
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 151, in make_rpc_call
    result = self._execute_rpc(rpc_command)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 365, in _execute_rpc
    response = self._send_command(xml_rpc_command, delay_factor=delay_factor)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 301, in _send_command
    if not self._timeout_exceeded(start=start):
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 190, in _timeout_exceeded
    raise TimeoutError(msg, self)
pyIOSXR.exceptions.TimeoutError: Timeout exceeded!
>>> gw.is_alive()
{u'is_alive': True}
>>>
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_iosxr/iosxr.py", line 193, in get_facts
    facts_rpc_reply = ETREE.fromstring(self.device.make_rpc_call(facts_rpc_request))
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 151, in make_rpc_call
    result = self._execute_rpc(rpc_command)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 365, in _execute_rpc
    response = self._send_command(xml_rpc_command, delay_factor=delay_factor)
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 301, in _send_command
    if not self._timeout_exceeded(start=start):
  File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 190, in _timeout_exceeded
    raise TimeoutError(msg, self)
pyIOSXR.exceptions.TimeoutError: Timeout exceeded!
```

---

Issue moved from https://github.com/napalm-automation/napalm-iosxr/issues/151

**Comment by ktbyers** [comment]
I am going to close this as there looks to be no active work on this issue.
