### ISSUE TITLE
`get_facts` fails on Junos

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#498]
`get_facts` fails on Junos, even though running `junos-eznc==2.1.7`:

```python
>>> j.get_facts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/junos/junos.py", line 258, in get_facts
    uptime = self.device.uptime or -1
AttributeError: 'Device' object has no attribute 'uptime'
```

**Comment by mirceaulinic** [comment]
I have revisited this, that's actually not the case, everything is alright.
