### ISSUE TITLE
Telnet option in optional_args not accepted

### ISSUE THREAD

**Issue by mk311d** [napalm-automation/napalm#551]
Hello,

I am trying to set up a telnet connection towards our cisco IOS devices. When I specify in the `optional_args` to use telnet or SSH the option is not accepted.

The command I use:
`napalm --vendor ios --user USER_NAME --password MY_PASSWORD --optional_args 'transport=ssh' 123.123.123.123`

The error message I get is:
```
Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 9, in <module>
    load_entry_point('napalm==2.1.0', 'console_scripts', 'napalm')()
  File "/usr/local/lib/python3.5/dist-packages/napalm/base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/usr/local/lib/python3.5/dist-packages/napalm/base/clitools/cl_napalm.py", line 252, in run_tests
    optional_args = helpers.parse_optional_args(args.optional_args)
  File "/usr/local/lib/python3.5/dist-packages/napalm/base/clitools/helpers.py", line 125, in parse_optional_args
    for x in optional_args.split(',')}
  File "/usr/local/lib/python3.5/dist-packages/napalm/base/clitools/helpers.py", line 125, in <dictcomp>
    for x in optional_args.split(',')}
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7f316fbee588>
```
When I put for example into the `--optional_args 'port=22'` the command is accepted. So it looks like the problem is with the `transport` argument.

I followed the this [link](http://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments) for setup.

Can someone advice?

Thanks.

Matt

**Comment by afourmy** [comment]
Hello Matt,

that's because of ast.literal_eval. You need to give him an actual string to parse:
`"transport='telnet'"`

**Comment by mk311d** [comment]
Thanks @afourmy worked!

Closing this one.

**Comment by lingfish** [comment]
I have to say, this makes zero sense to me (having to quote like that)... but either way, shouldn't the doco be updated?
