### ISSUE TITLE
How to use a custom driver?

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm#595]
Recently trying to develop something useful for cisco_wlc, but how can I import it to napalm? The document does not explain a lot there.

e.g., I have a folder name `cisco_wlc` with two files under it:
`__init__.py`:
```
"""napalm.wlcos package."""
from napalm.cisco_wlc.cisco_wlc import WLCOSDriver

__all__ = ('WLCOSDriver',)
```

`cisco_wlc.py`:
```
class WLCOSDriver(NetworkDriver):
    """NAPALM Cisco WLCOS Handler."""
    some methods...
```

then in a `test.py` file, I want to use this as

```
from napalm import get_network_driver

driver = get_network_driver('cisco_wlc')
```

How can I put this driver to use? if it's fine with the community, I can also open a PR (but probably buggy)but just want to see how easily we can use a custom driver.

**Comment by dbarrosop** [comment]
We fixed that recently in #589 so you will have to wait until we release a new version. Basically, you will have to call your module `custom_cisco_wlc` and call it as `get_network_driver("custom_cisco_wlc")`.

**Comment by sincerywaing** [comment]
@dbarrosop Thanks for the heads up! how about `__init__.py`? should it be something similar to 
```
"""napalm.wlcos package."""
from custom_cisco_wlc import WLCOSDriver

__all__ = ('WLCOSDriver',)
```

and change file name `cisco_wlc.py` to `custom_cisco_wlc.py`

then in `test.py` 
```
from napalm import get_network_driver

driver = get_network_driver('custom_cisco_wlc')
```

something same to above?

**Comment by dbarrosop** [comment]
correct, that should work.

**Comment by sincerywaing** [comment]
fantastic. then I'll be waiting for `2.2.1` I guess.
I'll also see if I can share that with community soon.

**Comment by dbarrosop** [comment]
Next version will be 2.3.0. I actually wanted to release today so hopefully you won't have to wait for long :P

**Comment by dbarrosop** [comment]
Sorry this is getting delayed but I wanted to include #590 in the release and the holidays have kept me busy.

**Comment by sincerywaing** [comment]
@dbarrosop no worries, please take your time. Happy new year!

**Comment by sincerywaing** [comment]
@dbarrosop I tried with develop branch and added the fix of #589 to `__init__.py` in base directory but still throw below error - 

```
>>> from napalm import get_network_driver
>>> driver = get_network_driver('custom_cisco_wlc')
>>> dev = driver('r180-wlc.rtl.apple.com', 'user', 'pass')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm/base/base.py", line 43, in __init__
    raise NotImplementedError
NotImplementedError
``` 

my `__init__.py`:
```
from custom_cisco_wlc import WLCOSDriver
```

is there anything I'm missing?

**Comment by dbarrosop** [comment]
looks like your class doesn't implement `__init__`.

**Comment by sincerywaing** [comment]
@dbassrosop is there any example I can refer to? my class also has a __init__, a very close one to ios class.

**Comment by dbarrosop** [comment]
well, I'd start by inspecting the `driver` object to make sure you got the class you were expecting and if you did then verify the `__init__` method has the correct name; that's two underscores before and after the word `init`.

**Comment by dbarrosop** [comment]
by the way, we released a few days ago a new version of napalm with the fix already.

**Comment by sincerywaing** [comment]
I upgraded to 2.3.0 but it seems there is still issue - looking at below code, it seems what napalm is trying to find is a folder with name 'custom_napalm' and a file, e.g. 'wlc.py'?

```
 module_install_name = module_name.replace('-', '')
    community_install_name = "napalm_{name}".format(name=module_install_name)
    custom_install_name = "custom_napalm.{name}".format(name=module_install_name)
    # Can also request using napalm_[SOMETHING]
    if 'napalm' not in module_install_name and prepend is True:
        module_install_name = 'napalm.{name}'.format(name=module_install_name)
    # Order is custom_napalm_os (local only) ->  napalm.os (core) ->  napalm_os (community)
    for module_name in [custom_install_name, module_install_name, community_install_name]:
        try:
            module = importlib.import_module(module_name)
            break
        except ImportError:
            pass
    else:
        raise ModuleImportError(
            'Cannot import "{install_name}". Is the library installed?'.format(
                install_name=module_install_name
            )
        )
```

I have below directory - 

```
custom_napalm/
├── __init__.py
└── wlc.py
```

in __init__.py:
```
from wlc import WLCOSDriver
```

in wlc.py:

```
class WLCOSDriver(NetworkDriver):
    """NAPALM Cisco WLCOS Handler."""

    def __init__(self, hostname, username, password, timeout=60, optional_args=None):
        """NAPALM Cisco WLCOS Handler."""
        if optional_args is None:
            optional_args = {}
        self.hostname = hostname
        self.username = username
        self.password = password
        self.timeout = timeout

        self.transport = optional_args.get('transport', 'ssh')

        # Netmiko possible arguments
        netmiko_argument_map = {
            'port': None,
            'secret': '',
            'verbose': False,
            'keepalive': 30,
            'global_delay_factor': 2,
            'use_keys': False,
            'key_file': None,
            'ssh_strict': False,
            'system_host_keys': False,
            'alt_host_keys': False,
            'alt_key_file': '',
            'ssh_config_file': None,
            'allow_agent': False,
        }

        # Build dict of any optional Netmiko args
        self.netmiko_optional_args = {}
        for k, v in netmiko_argument_map.items():
            try:
                self.netmiko_optional_args[k] = optional_args[k]
            except KeyError:
                pass

        default_port = {
            'ssh': 22,
        }
        self.port = optional_args.get('port', default_port[self.transport])

        self.device = None
        self.config_replace = False
        self.profile = ["wlc"]
```
and when I trying to use it, it throw below error - 

```
>>> dev = driver('10.1.1.1', 'fdsfw', 'dfwf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm/base/base.py", line 43, in __init__
    raise NotImplementedError
NotImplementedError
```

**Comment by sincerywaing** [comment]
I used community driver to make it running. Thanks guys!
