### ISSUE TITLE
NTP set/get fails for non-CFS Nexus

### ISSUE THREAD

**Issue by cspeidel** [napalm-automation/napalm#644]
Commit 7bb33ee9a061264bba297ae08abd74b95cb4b65e breaks templated NTP configs for Nexus devices not running CFS for NTP. In this example the N9K did not have CFS enabled for NTP by default.

Example code:
```
device.load_template('set_ntp_servers',
                              servers=['216.239.35.0'],
                              test=False,
                              commit=True)
print (device.compare_config())
device.commit_config()
```
Results:
```
ntp server 216.239.35.0
ntp commit
Traceback (most recent call last):
  File "./del.py", line 19, in <module>
    device.commit_config()
  File "/usr/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 338, in commit_config
    raise MergeConfigException(str(e))
napalm.base.exceptions.MergeConfigException: The command "ntp commit" gave the error "% Invalid command
```
The CFS application status:
```
nx01# show cfs application 

----------------------------------------------
 Application    Enabled   Scope
----------------------------------------------
 ntp            No        Physical-fc-ip
 stp            Yes       Physical-eth
 l2fm           Yes       Physical-eth
 role           No        Physical-fc-ip
 radius         No        Physical-fc-ip
 syslogd        No        Physical-fc-ip
 callhome       No        Physical-fc-ip
 session-mgr    Yes       Physical-ip
 eth_port_chann Yes       Physical-eth

Total number of entries = 9
```

From the N9K:
```
nx01(config)# ntp ?
  access-group        NTP access-group
  allow               Enable/Disable the packets
  authenticate        Enable/Disable authentication
  authentication-key  NTP authentication key
  logging             Enable/Disable logging of NTPD Events
  master              Act as NTP master clock
  passive             NTP passive command
  peer                NTP Peer address
  server              NTP server address
  source              Source of NTP packets
  source-interface    Source interface sending NTP packets
  trusted-key         NTP trusted-key

nx01(config)# ntp commit
                  ^
% Invalid command at '^' marker.
```

'show version' details:
```
Software
  BIOS: version 07.59
  NXOS: version 7.0(3)I6(1)
  BIOS compile time:  08/26/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I6.1.bin
  NXOS compile time:  5/16/2017 22:00:00 [05/17/2017 06:21:28]


Hardware
  cisco Nexus9000 C92160YC-X chassis 
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401224 kB of memory.
```

**Comment by cspeidel** [comment]
@mirceaulinic 'ntp commit' is not a valid command when CFS is not enabled for NTP (the default behavior for the platform/version above).
