### ISSUE TITLE
get_lldp_neighbors_detail error on Juniper PTX

### ISSUE THREAD

**Issue by bplimp** [napalm-automation/napalm#646]
Hello

We recently encountered this error when calling get_lldp_neighbors_detail against a PTX5K.
$ napalm --user user --password pass --vendor junos 127.0.0.2 call get_lldp_neighbors_detail

```
2018-02-09 14:10:53,449 - napalm - ERROR - method - Failed: RpcError(severity: error, bad_element: get-lldp-interface-neighbors-information, message: error: syntax error
error: syntax error)

================= Traceback =================

Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    load_entry_point('napalm==2.3.0', 'console_scripts', 'napalm')()
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 268, in run_tests
    call_getter(device, args.method, **method_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 238, in call_getter
    r = func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/napalm/junos/junos.py", line 718, in get_lldp_neighbors_detail
    lldp_table.get(interface_name=interface)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/factory/optable.py", line 64, in get
    self.xml = getattr(self.RPC, self.GET_RPC)(**rpc_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 63, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 790, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: get-lldp-interface-neighbors-information, message: error: syntax error
error: syntax error)
```

We were able to fix the error by making the following adjustments to:
/usr/local/lib/python2.7/dist-packages/napalm/junos/junos.py
```

 708         lldp_table.GET_RPC = 'get-lldp-interface-neighbors'
 709       -  if self.device.facts.get('personality') not in ('MX', 'M', 'T')\
 709       +  if self.device.facts.get('personality') not in ('PTX', 'MX', 'M', 'T')\
 710            and self.device.facts.get('model') not in ('EX9208', 'QFX10008'):
 711             # Still need to confirm for QFX10002 and other EX series
 712             lldp_table.GET_RPC = 'get-lldp-interface-neighbors-information'
 713
 714         for interface in interfaces:
 715             if 'EX9208' in self.device.facts.get('model'):
 716                 lldp_table.get(interface_device=interface)
 717          -  elif self.device.facts.get('personality') not in ('MX', 'M', 'T'):
 717          +  elif self.device.facts.get('personality') not in ('PTX', 'MX', 'M', 'T'):
 718                 lldp_table.get(interface_name=interface)
 719             else:

```
Not sure if this has been previously submitted or not but wanted to make a request. 

Thank you

**Comment by dbarrosop** [comment]
Oh, nice. Could you send a PR?

**Comment by mirceaulinic** [comment]
Hey @bplimp thanks for reporting this. What @dbarrosop said: can you please put you patch in a PR? Cheers.

**Comment by bplimp** [comment]
PR has been submitted.  Thank you for the reminder.

**Comment by sjtarik** [comment]
@dbarrosop Working on a new EX model EX4300-48MP giving the same error. Instead of adding model to this list:
```

            'SWITCH': {
                'default': rpc_call_with_information,
                'EX9208': rpc_call_without_information,
                'EX3400': rpc_call_without_information,
                'EX4300-48P': rpc_call_without_information,
                'EX4600-40F': rpc_call_without_information,
                'QFX5100-48S-6Q': rpc_call_without_information,
                'QFX5110-48S-4C': rpc_call_without_information,
                'QFX10002-36Q': rpc_call_without_information,
                'QFX10008': rpc_call_without_information,
                'EX2300-24P': rpc_call_without_information,
                'EX2300-C-12P': rpc_call_without_information
            },
```

in /usr/local/lib/python2.7/dist-packages/napalm/junos/junos.py, do you think I should just create a pattern EX/QFX and make it all "rpc_call_without_information" or it is not safe to assume for all EX/QFX?

**Comment by dbarrosop** [comment]
is it a problem because you don't have lldp enabled or because the platform doesn't support it? I find it odd the platform doesn't.

**Comment by ktbyers** [comment]
@sjtarik LLDP was completely overhauled thanks to @jobec. 

So this whole table is now gone in the `develop` branch. Consequently, I would re-test this in develop and see if you have an issue (and if so, create a new issue on it).

**Comment by sjtarik** [comment]
thanks @ktbyers. Verified and it is working on  EX4300-48MP with develop branch code.
