### ISSUE TITLE
The get_interfaces() speed crash with no IP address

### ISSUE THREAD

**Issue by FloLaco** [napalm-automation/napalm#672]
The `get_interfaces()` function crash when a SVI does not have IP address.

Problem seen on Nexus N9K-C93180LC-EX
Driver : NXOS_SSH
Traceback : 
```
Traceback (most recent call last):
  File "script_switch.py", line 308, in <module>
    main(sys.argv[1:])
  File "script_switch.py", line 303, in main
    test_migration(ip, login, pwd, driver, fex)
  File "script_switch.py", line 206, in test_migration
    new_intf_table = device.get_interfaces()
  File "/home/florian_lacommare/GitHub/napalm/napalm/nxos_ssh/nxos_ssh.py", line 862, in get_interfaces
    interfaces.update(parse_intf_section(entry))
  File "/home/florian_lacommare/GitHub/napalm/napalm/nxos_ssh/nxos_ssh.py", line 149, in parse_intf_section
    speed = int(match.group('speed'))
AttributeError: 'NoneType' object has no attribute 'group'
```

The interface that trigger the crash : 
```
Vlan600 is up, line protocol is up, autostate enabled
  Hardware is EtherSVI, address is  6cb2.aeb5.9f59
  Description: *** L3VNI-PROD ***  MTU 9216 bytes, BW 1000000 Kbit, DLY 10 usec,
   reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  ARP type: ARPA
  Last clearing of "show interface" counters never
  L3 in Switched:
    ucast: 0 pkts, 0 bytes
```

As we see, the `description `part is on the same line as `MTU/SPEED `
And here is the regex for the speed :     `re_speed = r"^\s+MTU .*, BW (?P<speed>\S+) (?P<speed_unit>\S+), "`

We just need to remove the regex "beginning of new line".
I'll provide a PR for that because there is some other issue with VXLAN

**Comment by dbarrosop** [comment]
Great, thanks for the report. Waiting for the PR :D

**Comment by FloLaco** [comment]
I'm going to be crazy with the cisco scrapping data ...
New N9K is different to N3K, N7K etc ...
