### ISSUE TITLE
EOS - Fix remote_as with Local/Internal asPathType

### ISSUE THREAD

**Issue by cuong-nguyenduy** [napalm-automation/napalm#694]
I have an iBGP route, originated from local peer. The result of `show ip bgp 10.0.201.25 vrf all` is as below:
```

{
  "jsonrpc": "2.0",
  "id": "EapiExplorer-1",
  "result": [
    {
      "vrfs": {
        "default": {
          "routerId": "10.255.0.11",
          "vrf": "default",
          "bgpRouteEntries": {
            "10.0.201.0/24": {
              "totalPaths": 3,
              "bgpAdvertisedPeerGroups": {},
              "maskLength": 24,
              "bgpRoutePaths": [
                {
                  "asPathEntry": {
                    "asPathType": "Internal"
                  },
                  "med": 0,
                  "localPreference": 100,
                  "weight": 0,
                  "reasonNotBestpath": "noReason",
                  "timestamp": 1522401885,
                  "nextHop": "10.255.0.14",
                  "routeType": {
                    "atomicAggregator": false,
                    "origin": "Incomplete",
                    "suppressed": false,
                    "queued": false,
                    "valid": true,
                    "ecmpContributor": true,
                    "luRoute": false,
                    "active": true,
                    "stale": false,
                    "ecmp": true,
                    "backup": false,
                    "ecmpHead": true,
                    "ucmp": false
                  },
                  "routeDetail": {
                    "origin": "Incomplete",
                    "peerEntry": {
                      "peerRouterId": "10.255.0.14",
                      "peerAddr": "10.255.0.14"
                    },
                    "tunnelRibEligible": false,
                    "extCommunityList": [],
                    "igpMetric": 10,
                    "communityList": [],
                    "rxSafi": "Unicast",
                    "bgpContributors": [],
                    "recvdFromRRClient": true,
                    "labelStack": []
                  }
                },
                {
                  "asPathEntry": {
                    "asPathType": "Internal"
                  },
                  "med": 0,
                  "localPreference": 100,
                  "weight": 0,
                  "reasonNotBestpath": "ecmpFast",
                  "timestamp": 1522401838,
                  "nextHop": "10.255.0.13",
                  "routeType": {
                    "atomicAggregator": false,
                    "origin": "Incomplete",
                    "suppressed": false,
                    "queued": false,
                    "valid": true,
                    "ecmpContributor": true,
                    "luRoute": false,
                    "active": false,
                    "stale": false,
                    "ecmp": true,
                    "backup": false,
                    "ecmpHead": false,
                    "ucmp": false
                  },
                  "routeDetail": {
                    "origin": "Incomplete",
                    "peerEntry": {
                      "peerRouterId": "10.255.0.13",
                      "peerAddr": "10.255.0.13"
                    },
                    "tunnelRibEligible": false,
                    "extCommunityList": [],
                    "igpMetric": 10,
                    "communityList": [],
                    "rxSafi": "Unicast",
                    "bgpContributors": [],
                    "recvdFromRRClient": true,
                    "labelStack": []
                  }
                },
                {
                  "asPathEntry": {
                    "asPathType": "Internal"
                  },
                  "med": 0,
                  "localPreference": 100,
                  "weight": 0,
                  "reasonNotBestpath": "ecmpFast",
                  "timestamp": 1523138823,
                  "nextHop": "10.255.0.13",
                  "routeType": {
                    "atomicAggregator": false,
                    "origin": "Incomplete",
                    "suppressed": false,
                    "queued": false,
                    "valid": true,
                    "ecmpContributor": true,
                    "luRoute": false,
                    "active": false,
                    "stale": false,
                    "ecmp": true,
                    "backup": false,
                    "ecmpHead": false,
                    "ucmp": false
                  },
                  "routeDetail": {
                    "origin": "Incomplete",
                    "originator": "Originator: 10.255.0.13",
                    "tunnelRibEligible": false,
                    "extCommunityList": [],
                    "communityList": [],
                    "rxSafi": "Unicast",
                    "bgpContributors": [],
                    "recvdFromRRClient": false,
                    "peerEntry": {
                      "peerRouterId": "10.255.0.12",
                      "peerAddr": "10.255.0.12"
                    },
                    "igpMetric": 10,
                    "clusterList": "Cluster list: 10.255.0.12",
                    "labelStack": []
                  }
                }
              ],
              "address": "10.0.201.0"
            }
          },
          "asn": 65001
        }
      }
    }
  ]
}

```
When executing `get_route_to('10.0.201.25')`, I got Exception:

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    pp.pprint(router.get_route_to('10.0.201.25'))
  File "C:\Users\NGUYEN Duy Cuong\AppData\Local\Programs\PyEnv\py3.6.4\lib\site-packages\napalm\eos\eos.py", line 1142, in get_route_to
    remote_as = int(as_path.split()[-1])
IndexError: list index out of range
```

It seems that in the above output, **```asPathType```** is **```Internal```**, hence the **```asPath```** is empty. This causes the exception when an empty list is indexed to the last item.

I changed ```eos.py```, line **1142**, to the below to solve the issue:

```
                        as_path = bgp_route_details.get('asPathEntry', {}).get('asPath', u'')
                        as_path_type = bgp_route_details.get('asPathEntry', {}).get('asPathType', u'')
                        if as_path_type in ['Internal', 'Local']:
                            remote_as = local_as
                        else:
                            remote_as = int(as_path.split()[-1])
```

I  believe the original code assumes BGP routes are eBGP. I haven't tested thoroughly, though. It only fixed in my case

**Comment by dbarrosop** [comment]
That's an interesting one. Would you mind sending a PR and linking it here?

**Comment by cuong-nguyenduy** [comment]
Takes me something to learn how to use git and github. I've created PR as shown here
[https://github.com/napalm-automation/napalm/pull/794](https://github.com/napalm-automation/napalm/pull/794)
