### ISSUE TITLE
Unable to connect to nxos device via salt

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#740]
I am connecting to a nxos device, my minion proxy config is very simple:
proxy:
  proxytype: napalm
  driver: nxos
  host: *********************
  username: ******************
  password: ********************

But the proxy is erroring out as:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 991, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1182, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 3578, in _post_master_init
    proxy_init_fn(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/proxy/napalm.py", line 183, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 332, in get_device
    network_device.get('DRIVER').open()
  File "/usr/local/lib/python2.7/dist-packages/napalm_nxos/nxos.py", line 80, in open
    self.device.show('show hostname')
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 49, in show
    list_result = self.show_list(commands, raw_text)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 63, in show_list
    response_list = self._cli_command(commands)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 38, in _cli_command
    rpc_response = self.rpc.send_request(commands, method=method, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/lib/rpc_client.py", line 49, in send_request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='**********', port=443): Max retries exceeded with url: /ins (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6aea5d0>: **Failed to establish a new connection: [Errno 111] Connection refused',))**

Version:
napalm-base==1.0.0
napalm-ios==0.8.1
napalm-iosxr==0.5.6
napalm-junos==0.12.1
napalm-nxos==0.7.1

**Comment by AmbicaY** [comment]
For our switches, port 443 is blocked. Only SSH is allowed. Is there any way I can specify this in the pillar file?

**Comment by DiogoAndre** [comment]
You may have better luck using the ```nxos_ssh``` driver.

**Comment by AmbicaY** [comment]
Awesome!!!!! I dint know that such a driver was there. Thanks @DiogoAndre 

Is there any location/documentation that I can refer for the list of drivers?

**Comment by DiogoAndre** [comment]
NP! 
There is a list here https://napalm.readthedocs.io/en/latest/support/index.html and there are also some community drivers  you may want to check: https://github.com/napalm-automation-community/

**Comment by AmbicaY** [comment]
Thanks a lot @DiogoAndre
