### ISSUE TITLE
Error with load_merge_candidate / load_replace_candidate with Cisco IOS device

### ISSUE THREAD

**Issue by tybruno** [napalm-automation/napalm#779]
I am getting the an uncaught exception when trying to perform a load_merge_candidate or load_replace_candidate action on a device. I also get the same error without using a context manager.  I am able to connect to the device and perform the get functions such as get_facts and get_running but I get an error when doing the load_merge_candidate and load_replace_candidate commands.

Traceback:
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "tester.py", line 12, in <module>
    d.load_merge_candidate(filename=config_file)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\napalm\ios\ios.py", line 259, in load_merge_candidate
    file_system=self.dest_file_system)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\napalm\ios\ios.py", line 226, in _load_candidate_wrapper
    file_system=file_system)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\napalm\ios\ios.py", line 504, in _scp_file
    file_system=file_system, TransferClass=FileTransfer)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\napalm\ios\ios.py", line 533, in _xfer_file
    with TransferClass(**kwargs) as transfer:
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\netmiko\scp_handler.py", line 85, in __enter__
    self.establish_scp_conn()
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\netmiko\scp_handler.py", line 94, in establish_scp_conn
    self.scp_conn = SCPConn(self.ssh_ctl_chan)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\netmiko\scp_handler.py", line 28, in __init__
    self.establish_scp_conn()
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\netmiko\scp_handler.py", line 35, in establish_scp_conn
    self.scp_conn.connect(**ssh_connect_params)
  File "C:\Users\tybruno\.virtualenvs\napalm-tool-hRMpbX5k\lib\site-packages\paramiko\client.py", line 360, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on {ip} 

CODE:

from napalm import get_network_driver

args = {'keepalive': 2, 'allow_agent': True,
            'alt_host_keys': False,'secret':''}
config_file = 'config_file.conf'
driver = get_network_driver('ios')
with driver(hostname='hostname', username='username', password='pw', timeout=10, optional_args=args) as d:
    
 
    print(d.get_facts())

    d.load_merge_candidate(filename=config_file)

**Comment by ktbyers** [comment]
@tybruno Opening of the Secure Copy connection failed:

```
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on {ip}
```

What privilege level is the account that you login as (before the secret i.e. without any enable call)?

**Comment by tybruno** [comment]
@ktbyers  Any progress on resolving this issue?

**Comment by ktbyers** [comment]
So did you get this working or are you still having issues. I think you will probably need to use:

```
optional_args={'inline_transfer': True}
```

As an additional argument into NAPALM. This is from memory so please double check the syntax.

**Comment by tybruno** [comment]
Yes that optional arg fixed the issue. Thank you for your help!

**Comment by Laurel-rao** [comment]
I had to try set inline_transfer = True , but still don't work
My environment,  cisco  router,   trying to change password of user,
There is  my code.
```
    driver = get_network_driver(driver_type)
    if args_dict is None:
        args_dict = {
            "hostname": "",
            "username": "",
            "password": "",
            "secret": "",
        }
    device_obj = driver(**args_dict)
    cmd = "username %s secret %s"%(change_user, new_passwd)
    device_obj.load_merge_candidate(config=cmd)
```
The error show up when haven't set inline_transfer = True,
    
```
    file_system=file_system, TransferClass=FileTransfer
    transfer.transfer_file()
    self.put_file()
    self.scp_conn.scp_transfer_file(self.source_file, destination)
    self.scp_client.put(Source_file, dest_file)
    self._recv_confirm()
    raise SCPException(asunicode(msg[1:]))
    scp.SCPException: Privilege denied.
```
The error show up when have set inline_transfer = True,
```
     file_system=file_system, TransferClass=FileTransfer
     if  transfer.check_file_exists() and transfer.compare_md5():
     remote_out = self.ssh_ctl_chan.send_command_expect(remote_cmd)
     return self.send_command(*args, **kwargs)
     OSError  Search pattern never detected in send_command_expect： SZFF01U33\-OP2\-C49Z\(tcl\)\#
```
Help me fix the problem ,please!
Otherwise I  can only find  the other way to accomplish my purpose.

**Comment by surendrasinghtanwar2002** [comment]
from napalm import get_network_driver

driver = get_network_driver('ios')
device = driver(hostname='192.168.1.105', username='admin', password='xyz',optional_args={'inline_transfer': True})

device.open()



device.load_merge_candidate(config='interface FastEthernet2/0\n ip address 10.0.0.1 255.255.255.0\n no shutdown\n end\n')

print(device.compare_config())

device.close()


i am getting error in this code when i tried to run load_merge_candidate




No space information available
PS E:\Dev_Net\Napalm\Napalm_Practise_Lab\Napalm_Configuration_Function\load_replace_candidate_method_practise> & C:/Users/suren/AppData/Local/Programs/Python/Python312/python.exe e:/Dev_Net/Napalm/Napalm_Practise_Lab/Napalm_Configuration_Function/load_replace_candidate_method_practise/load_replace_candidate_practise_1.py
Traceback (most recent call last):
  File "e:\Dev_Net\Napalm\Napalm_Practise_Lab\Napalm_Configuration_Function\load_replace_candidate_method_practise\load_replace_candidate_practise_1.py", line 19, in <module>
    device.load_merge_candidate(config=new_config)
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\napalm\ios\ios.py", line 320, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\napalm\ios\ios.py", line 266, in _load_candidate_wrapper
    (return_status, msg) = self._inline_tcl_xfer(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\napalm\ios\ios.py", line 720, in _inline_tcl_xfer
    return self._xfer_file(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\napalm\ios\ios.py", line 791, in _xfer_file
    if not transfer.verify_space_available():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\netmiko\scp_handler.py", line 214, in verify_space_available
    space_avail = self.remote_space_available(search_pattern=search_pattern)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suren\AppData\Local\Programs\Python\Python312\Lib\site-packages\netmiko\scp_handler.py", line 160, in remote_space_available
    raise ValueError(msg)
ValueError: pattern: (\d+) \w+ free not detected in output:

**Comment by ktbyers** [comment]
@tybruno It looks like `dir` on the device failed?

**Comment by surendrasinghtanwar2002** [comment]
i have checked but still not working

**Comment by ktbyers** [comment]
@surendrasinghtanwar2002 Can you show the `dir` output from the device that is failing.
