### ISSUE TITLE
nxos_ssh get_lldp_neighbors using TextFSM template is unlikely to be correct

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#834]
I am basing this on IOS, but that first field in IOS is a fixed length field (20 characters) and can have spaces in it:

```
$ cat ./nxos_ssh/utils/textfsm_templates/lldp_neighbors.tpl
Value NEIGHBOR (\S+)
Value LOCAL_INTERFACE (\S+)
Value NEIGHBOR_INTERFACE (\S+)

Start
  ^Device.*ID -> LLDP

LLDP
  ^${NEIGHBOR}\s+${LOCAL_INTERFACE}\s+\d+\s+[\w+\s]+\S+\s+${NEIGHBOR_INTERFACE} -> Record

```

**Comment by ktbyers** [comment]
Looks like NXOS is different here:

```
show lldp neighbors 
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID                                         Local Intf          Hold-time   Capability  Port ID     
nxos2_nxos2_nxos2_nxos2_nxos2_nxos2.twb-tech.com  Eth2/1              120          BR          Eth2/1      
nxos2_nxos2_nxos2_nxos2_nxos2_nxos2.twb-tech.com  Eth2/2              120          BR          Eth2/2      
nxos2_nxos2_nxos2_nxos2_nxos2_nxos2.twb-tech.com  Eth2/3              120          BR          Eth2/3      
nxos2_nxos2_nxos2_nxos2_nxos2_nxos2.twb-tech.com  Eth2/4              120          BR          Eth2/4      
Total entries displayed: 4
```

Names with whitespace could still be an issue though

**Comment by jobec** [comment]
I've found other issues with the LLDP stuff on nxos_ssh. When the chassis ID isn't a mac address (for example, an F5 Load Balancer sends it's serial number) then the code explodes with this erros:

```
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/home/vagrant/.venv/lib/python3.6/site-packages/napalm/nxos_ssh/nxos_ssh.py", line 735, in get_lldp_neighbors_detail
    'remote_chassis_id': napalm.base.helpers.mac(chassis_rgx.groups()[1])
  File "/home/vagrant/.venv/lib/python3.6/site-packages/napalm/base/helpers.py", line 224, in mac
    return py23_compat.text_type(EUI(raw, dialect=_MACFormat))
  File "/home/vagrant/.venv/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 387, in __init__
    self.value = addr
  File "/home/vagrant/.venv/lib/python3.6/site-packages/netaddr/eui/__init__.py", line 437, in _set_value
    % value)
netaddr.core.AddrFormatError: failed to detect EUI version: 'chs123456s'
```
@ktbyers @mirceaulinic 
Shall I send a PR to review this and rewrite it the same way as I did for IOS?

**Comment by jobec** [comment]
To bypass the original problem of this issue, the LLDP neighbor output in PR #872 was switched to using the `show lldp neighbors detail` output. The standard `show lldp neighbors` output cannot be reliably be parsed with long neighbor system names.
