### ISSUE TITLE
IOS get_bgp_neighbors() fails on None neighbor_entry

### ISSUE THREAD

**Issue by jtishey** [napalm-automation/napalm#843]
For IOS getter get_bgp_neighbors(), if a neighbor shows up with a supported AFI, but no info under that AFI, a ValueError is raised, which causes a TypeError since the neighbor_entry is None.  Skipping the neighbor/afi seems like an acceptable solution.

Example CLI Output:
```
router1#show bgp all neighbors 10.0.0.1
For address family: IPv4 Unicast

For address family: IPv6 Unicast

For address family: IPv4 MDT
BGP neighbor is 10.0.0.1,  remote AS 65001, internal link
 Description: router2
 Member of peer-group VRR for session parameters
```

Tries to raise a ValueError on None:
```
>>> dev.get_bgp_neighbors() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ENV/lib/python3.6/site-packages/napalm/ios/ios.py", line 1284, in get_bgp_neighbors
    (remote_addr, afi))
TypeError: ValueError does not take keyword arguments
```

Check for None before doing the isinstance check.?
```
1282+    # check for proper session data for the afi
1283+    if neighbor_entry is None:
1284+        continue
1285+    elif not isinstance(neighbor_entry, dict):
1286         raise ValueError(msg="Couldn't find neighbor data for %s in afi %s" %
1287                              (remote_addr, afi))
```

**Comment by mirceaulinic** [comment]
Solved via #844. Thanks @jtishey!
