### ISSUE TITLE
NXOS_SSH: get_interfaces fails with AttributeError

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#855]
We have couple of nexus devices with tunnel interfaces, where get_interfaces is failing with the error:

```
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm/nxos_ssh/nxos_ssh.py", line 836, in get_interfaces
            interfaces.update(parse_intf_section(entry))
          File "/usr/local/lib/python2.7/dist-packages/napalm/nxos_ssh/nxos_ssh.py", line 154, in parse_intf_section
            speed = int(match.group('speed'))
        AttributeError: 'NoneType' object has no attribute 'group'
```

On checking further, this happens for the tunnel interface whose output is as below in the "show interface" command':

```
Tunnel901 is up
    Description: Visitor to *****
    Admin State: up
    Internet address is ***.**.**.***/30
    MTU 1476 bytes, BW 1000 Kbit
    Tunnel protocol/transport GRE/IP
    Tunnel source ***.***.***.*** (loopback0), destination ***.***.***.***
    Transport protocol is in VRF "default"
    Rx
    578091 packets input, 1 minute input rate 0 packets/sec
    Tx
    0 packets output, 1 minute output rate 0 packets/sec
    Last clearing of "show interface" counters never
```

**Comment by AmbicaY** [comment]
@mirceaulinic, any idea about this error?

**Comment by ktbyers** [comment]
@AmbicaY Okay, this is a bug. We are expecting there to be a DLY also on the MTU, BW line, but the above output doesn't have that:

```
  MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec,
```

So our regex parsing is failing.
