### ISSUE TITLE
get_lldp_neighbors_detail() on junos does not honor interface parameter

### ISSUE THREAD

**Issue by sjtarik** [napalm-automation/napalm#906]
On version 2.3.3, get_lldp_neighbors_detail returns all neighbors instead of the particular interface passed by user.

**Comment by ktbyers** [comment]
@sjtarik I am pretty sure that is fixed in the 'develop' branch. Can you re-test it using that branch?

**Comment by sjtarik** [comment]
@ktbyers I got the following error with latest from develop branch:

```
>>> net_con.get_lldp_neighbors_detail(interface='ge-3/0/2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/junos/junos.py", line 804, in get_lldp_neighbors_detail
    lldp_table.GET_RPC = "get-lldp-interface-neighbors"
UnboundLocalError: local variable 'lldp_table' referenced before assignment
```

**Comment by ktbyers** [comment]
@sjtarik Okay, that looks like a bug.

**Comment by sjtarik** [comment]
@ktbyers it seems like a minor issue. Could you review this change?
