### ISSUE TITLE
get_bgp_neighbors() gets corrupted if 6PE is enabled in eos

### ISSUE THREAD

**Issue by Mabuchin** [napalm-automation/napalm#944]
In the case of processing of these lines, if ipv6 is invalid, there will be a gap in the number of processing lines.
As a result, local_asn regex different lines.

https://github.com/napalm-automation/napalm/blob/2e98a86bc8f967256fdc38255a856d2fae40fd68/napalm/eos/eos.py#L484-L509

In my eos environment, I confirmed neighbors where ipv6 stats like below are not displayed.

```
['BGP neighbor is 10.8.176.1, remote AS 64540, internal link', '  BGP version 4, remote router ID 10.8.176.1, VRF default', '  BGP state is Established, up for 172d03h', '    IPv4 Unicast:           0        58', 'Local AS is 38651, local router ID 10.8.176.11']
```

`v6_stats` should also be branched like `desc`'s `next_line`.

**Comment by Mabuchin** [comment]
Error Info
```
2019-03-18 11:27:47,429 - napalm - ERROR - method - Failed: 'NoneType' object has no attribute 'group'

================= Traceback =================

Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/clitools/cl_napalm.py", line 309, in main
    run_tests(args)
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/clitools/cl_napalm.py", line 292, in run_tests
    call_getter(device, args.method, **method_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/clitools/cl_napalm.py", line 31, in wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/napalm/base/clitools/cl_napalm.py", line 256, in call_getter
    r = func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/napalm/eos/eos.py", line 518, in get_bgp_neighbors
    "local_as": int(local_as.group("as")),
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Mabuchin** [comment]
The cause was using 6PE on EOS's router.
If you use 6PE, it will be the following form before using Regexp.
```
  Prefix Statistics:
                         Sent      Rcvd
    IPv4 Unicast:           0        58
    IPv6 6PE:               1         1
```

Before the code is omitted, 6PE is omitted at the command level.
following parts.
https://github.com/napalm-automation/napalm/blob/2e98a86bc8f967256fdc38255a856d2fae40fd68/napalm/eos/eos.py#L429

Even in the case of 6 PE, we consider that it should be included in sent / received in ipv6, or ipv6 should be omitted (sent, received should be -1), or either action should be taken.
