### ISSUE TITLE
newest iosxr (6.5.3) causes pyIOSXR.exceptions.XMLCLIError with get_route_to function

### ISSUE THREAD

**Issue by jbotello7381** [napalm-automation/napalm#958]
During my testing with Cisco NCS5500 and there latest IOSXR (6.5.3) I notice issues with commands that depend on the function **get_route_to** on iosxr.py module.  

Validation

```
>>> from pyIOSXR import IOSXR
>>>
>>> device = IOSXR(hostname='pr04.lab01', username='user', password='password', port=22, timeout=120)
>>> device.open()
>>> route = '''<Get>
  <Operational>
    <RIB>
      <VRFTable>
        <VRF>
          <Naming>
            <VRFName>default</VRFName>
          </Naming>
          <AFTable>
            <AF>
              <Naming>
                <AFName>IPv4</AFName>
              </Naming>
              <SAFTable>
                <SAF>
                  <Naming>
                    <SAFName>Unicast</SAFName>
                  </Naming>
                  <IP_RIBRouteTable>
                    <IP_RIBRoute>
                      <Naming>
                        <RouteTableName>default</RouteTableName>
                      </Naming>
                      <RouteTable>
                        <Route>
                          <Naming>
                            <Address>6.6.6.6</Address>
                            <PrefixLength>32</PrefixLength>
                          </Naming>
                        </Route>
                      </RouteTable>
                    </IP_RIBRoute>
                  </IP_RIBRouteTable>
                </SAF>
              </SAFTable>
            </AF>
          </AFTable>
        </VRF>
      </VRFTable>
    </RIB>
  </Operational>
</Get>'''
>>> device.make_rpc_call(route)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pyIOSXR/iosxr.py", line 151, in make_rpc_call
  File "build/bdist.linux-x86_64/egg/pyIOSXR/iosxr.py", line 416, in _execute_rpc
pyIOSXR.exceptions.XMLCLIError:
Original call was: <?xml version="1.0" encoding="UTF-8"?><Request MajorVersion="1" MinorVersion="0"><Get><Operational><RIB><VRFTable><VRF><Naming><VRFName>default</VRFName></Naming><AFTable><AF><Naming><AFName>IPv4</AFName></Naming><SAFTable><SAF><Naming><SAFName>Unicast</SAFName></Naming><IP_RIBRouteTable><IP_RIBRoute><Naming><RouteTableName>default</RouteTableName></Naming><RouteTable><Route><Naming><Address>6.6.6.6</Address><PrefixLength>32</PrefixLength></Naming></Route></RouteTable></IP_RIBRoute></IP_RIBRouteTable></SAF></SAFTable></AF></AFTable></VRF></VRFTable></RIB></Operational></Get></Request>
>>>
```

The new RPC call should look like this by replacing <IP_RIBRoute> with <IP_RIBRouteTableName>
```
>>> route = '''<Get>
  <Operational>
    <RIB>
      <VRFTable>
        <VRF>
          <Naming>
            <VRFName>default</VRFName>
          </Naming>
          <AFTable>
            <AF>
              <Naming>
                <AFName>IPv4</AFName>
              </Naming>
              <SAFTable>
                <SAF>
                  <Naming>
                    <SAFName>Unicast</SAFName>
                  </Naming>
                  <IP_RIBRouteTable>
                    <IP_RIBRouteTableName>
                      <Naming>
                        <RouteTableName>default</RouteTableName>
                      </Naming>
                      <RouteTable>
                        <Route>
                          <Naming>
                            <Address>6.6.6.6</Address>
                            <PrefixLength>32</PrefixLength>
                          </Naming>
                        </Route>
                      </RouteTable>
                    </IP_RIBRouteTableName>
                  </IP_RIBRouteTable>
                </SAF>
              </SAFTable>
            </AF>
          </AFTable>
        </VRF>
      </VRFTable>
    </RIB>
  </Operational>
</Get>'''
>>>
>>> device.make_rpc_call(route)

<Response MajorVersion="1" MinorVersion="0">
  <Get>
    <Operational>
      <RIB MajorVersion="4" MinorVersion="11">
        <VRFTable>
          <VRF>
            <Naming>
              <VRFName>default</VRFName>
            </Naming>
            <AFTable>
              <AF>
                <Naming>
                  <AFName>IPv4</AFName>
                </Naming>
                <SAFTable>
                  <SAF>
                    <Naming>
                      <SAFName>Unicast</SAFName>
                    </Naming>
                    <IP_RIBRouteTable>
                      <IP_RIBRouteTableName>
                        <Naming>
                          <RouteTableName>default</RouteTableName>
                        </Naming>
                        <RouteTable>
                          <Route>
                            <Naming>
                              <Address>6.6.6.6</Address>
                              <PrefixLength>32</PrefixLength>
                            </Naming>
                            <Prefix>6.6.6.6</Prefix>
                            <PrefixLength>32</PrefixLength>
                            <RouteVersion>1</RouteVersion>
                            <ProtocolID>2</ProtocolID>
                            <ProtocolName>static</ProtocolName>
                            <ClientID>16</ClientID>
                            <RouteType>1</RouteType>
                            <Priority>8</Priority>
                            <SVDType>1</SVDType>
                            <Flags>4096</Flags>
                            <ExtendedFlags>0</ExtendedFlags>
                            <Tag>0</Tag>
                            <Distance>1</Distance>
                            <DiversionDistance>0</DiversionDistance>
                            <Metric>0</Metric>
                            <PathsCount>1</PathsCount>
                            <AttributeIdentity>0</AttributeIdentity>
                            <TrafficIndex>0</TrafficIndex>
                            <RoutePrecedence>255</RoutePrecedence>
                            <QosGroup>255</QosGroup>
                            <FlowTag>0</FlowTag>
                            <FwdClass>0</FwdClass>
                            <PICCount>0</PICCount>
                            <Active>true</Active>
                            <Diversion>false</Diversion>
                            <RouteAge>600585</RouteAge>
                            <RouteLabel>1048577</RouteLabel>
                            <Version>1</Version>
                            <TblVersion>1</TblVersion>
                            <RouteModifyTime>1554161175773074464</RouteModifyTime>
                            <RoutePath>
                              <Entry>
                                <Address>0.0.0.0</Address>
                                <InformationSource>0.0.0.0</InformationSource>
                                <V6Nexthop>::</V6Nexthop>
                                <V6InformationSource>::</V6InformationSource>
                                <InterfaceName>Null0</InterfaceName>
                                <Metric>0</Metric>
                                <LoadMetric>1</LoadMetric>
                                <Flags64>2</Flags64>
                                <Flags>2</Flags>
                                <PrivateFlags>0</PrivateFlags>
                                <Looped>false</Looped>
                                <NextHopTableID>0</NextHopTableID>
                                <NextHopAFI>0</NextHopAFI>
                                <NextHopSAFI>0</NextHopSAFI>
                                <RouteLabel>1048577</RouteLabel>
                                <TunnelID>0</TunnelID>
                                <Pathid>0</Pathid>
                                <BackupPathid>0</BackupPathid>
                                <RefCntOfBackup>0</RefCntOfBackup>
                                <NumberOfExtendedCommunities>0</NumberOfExtendedCommunities>
                                <MVPNPresent>false</MVPNPresent>
                                <PATHRTPresent>false</PATHRTPresent>
                                <VRFIMPORTRTPresent>false</VRFIMPORTRTPresent>
                                <SOURCEASRTPresent>false</SOURCEASRTPresent>
                                <SOURCERDPresent>false</SOURCERDPresent>
                                <SegmentedNexthopPresent>false</SegmentedNexthopPresent>
                                <NumberOfNNH>0</NumberOfNNH>
                                <NextNextHop/>
                                <NextHopID>0</NextHopID>
                                <NextHopIDRefcount>0</NextHopIDRefcount>
                                <RemoteBackupAddr>
                                  <Entry>0.0.0.0</Entry>
                                  <Entry>0.0.0.0</Entry>
                                </RemoteBackupAddr>
                                <has_labelstk>false</has_labelstk>
                                <num_labels>0</num_labels>
                                <labelstk/>
                                <binding_label>1048577</binding_label>
                                <nhid_feid>18446744073709551614</nhid_feid>
                                <mpls_feid>18446744073709551614</mpls_feid>
                                <HasVXLANNetworkID>false</HasVXLANNetworkID>
                                <VXLANNetworkID>0</VXLANNetworkID>
                                <HasXCID>false</HasXCID>
                                <XCID>0</XCID>
                                <HasSPANDiagInterface>false</HasSPANDiagInterface>
                                <SPANDiagInterface>None</SPANDiagInterface>
                                <HasSubscriberParentInterface>false</HasSubscriberParentInterface>
                                <SubscriberParentInterface>None</SubscriberParentInterface>
                                <InterfaceIndexPresent>false</InterfaceIndexPresent>
                                <InterfaceIndexAttribute>0</InterfaceIndexAttribute>
                              </Entry>
                            </RoutePath>
                          </Route>
                        </RouteTable>
                      </IP_RIBRouteTableName>
                    </IP_RIBRouteTable>
                  </SAF>
                </SAFTable>
              </AF>
            </AFTable>
          </VRF>
        </VRFTable>
      </RIB>
    </Operational>
  </Get>
  <ResultSummary ErrorCount="0"/>
</Response>
```
root@test# python --version
Python 2.7.15rc1
root@test:~# pip list | grep napalm
napalm (2.4.0)
napalm-base (1.0.0)
napalm-iosxr (0.5.6)
napalm-junos (0.12.1)
napalm-salt (0.0.2)

**Comment by mirceaulinic** [comment]
Hi @jbotello7381 - I recall you were asking this in Slack, then you've manage to make it work with a different XML request. Would you be able to patch this? Thanks!

**Comment by jbotello7381** [comment]
how would you suggest @mirceaulinic we handle backward compatibility? I'm trying to get some information from Cisco to understand when this XML change

btw, I manually change it in my test environment and it works, but I haven't tested with older iosxr version

**Comment by chonty** [comment]
Same problem on ASR9000 with IOS-XR 6.1.4.

Would this be an acceptable approach to backward-compatibility? 

get_facts() during a get_route_to() call or upon initialisation*, check version and adjust XML path accordingly.

*this would require an extra variable to store the version or some flag value unless facts are already stored and means you won't have to call get_facts() every time you ask for a route.  get_facts() takes a few seconds on the real devices I've tested.

I'm not sure which version brought in the change so the check could start from 6.1.4.

**Comment by chonty** [comment]
PR for option b https://github.com/napalm-automation/napalm/pull/1267

**Comment by mirceaulinic** [comment]
Solved via https://github.com/napalm-automation/napalm/pull/1267.
