### ISSUE TITLE
"Timeout waiting for scp response" Error with load_merge_candidate / load_replace_candidate with cisco router on GNS3.

### ISSUE THREAD

**Issue by akkaluri** [napalm-automation/napalm#960]
Hi All,

I have created Napalm setup with cisco router on GNS3. I was able to get the configuration from router to VM with following steps.

```
>>>from napalm import get_network_driver
>>>driver = get_network_driver('ios')
>>>device = driver('192.168.0.1','cisco','cisco')
>>>device.open()

>>> device.get_facts()
{u'os_version': u'7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.2(4)S5, RELEASE SOFTWARE (fc1)', u'uptime': 1200, u'interface_list': [u'FastEthernet0/0', u'GigabitEthernet1/0', u'GigabitEthernet2/0'], u'vendor': u'Cisco', u'serial_number': u'4279256517', u'model': u'7206VXR', u'hostname': u'R1', u'fqdn': u'R1.cciepython.com'}
>>> 
>>> device.get_interfaces()
{u'GigabitEthernet1/0': {u'is_enabled': True, u'description': u'', u'last_flapped': -1.0, u'is_up': True, u'mac_address': u'CA:01:16:B0:00:1C', u'speed': 1000}, u'FastEthernet0/0': {u'is_enabled': False, u'description': u'', u'last_flapped': -1.0, u'is_up': False, u'mac_address': u'CA:01:16:B0:00:00', u'speed': 100}, u'GigabitEthernet2/0': {u'is_enabled': False, u'description': u'', u'last_flapped': -1.0, u'is_up': False, u'mac_address': u'CA:01:16:B0:00:38', u'speed': 1000}}
>>> 
>>> device.get_interfaces_ip()
{u'GigabitEthernet1/0': {u'ipv4': {u'192.168.0.1': {u'prefix_length': 24}}}}
```

But i couldn't  able to configure the router with following steps,

Even i configured "ip scp server enable" on router.

```
>>> device.load_replace_candidate(filename='new_config.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 285, in load_replace_candidate
    file_system=self.dest_file_system,
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 267, in _load_candidate_wrapper
    file_system=file_system,
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 606, in _scp_file
    TransferClass=FileTransfer,
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 674, in _xfer_file
    transfer.transfer_file()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py", line 304, in transfer_file
    self.put_file()
  File "/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py", line 317, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py", line 40, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 158, in put
    self._recv_confirm()
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 358, in _recv_confirm
     **raise SCPException('Timeout waiting for scp response')
scp.SCPException: Timeout waiting for scp response**
```

Could you please let us know how can we fix it?.

**Router configuration:**

RR1#dir
Directory of disk0:/

No files in directory

2199023147008 bytes total (104853504 bytes free)

RR1#copy running-config tftp:
Address or name of remote host []? 192.168.0.2
Destination filename [rr1-confg]? rr3-confg
!!
2615 bytes copied in 1.484 secs (1762 bytes/sec)

RR1#copy tftp: disk0:
Address or name of remote host []? 192.168.0.2
Source filename []? rr3-confg
Destination filename [rr3-confg]? 
Accessing tftp://192.168.0.2/rr3-confg...
Loading rr3-confg from 192.168.0.2 (via FastEthernet0/0): !
[OK - 2615 bytes]

%Error opening disk0:/rr3-confg (Bad service code)

Thanks,
Jagadeesh

**Comment by ktbyers** [comment]
Are you able to manually copy a file into disk0?

For example, something similar to this except with disk0

```
cisco1#   copy flash:filename flash:test1.txt
Destination filename [test1.txt]? 
Copy in progress...C
18 bytes copied in 0.452 secs (40 bytes/sec)

cisco1#more fl
cisco1#more flash:t
cisco1#more flash:test1.t
cisco1#more flash:test1.txt

whatever
"{"
}

```

**Comment by ktbyers** [comment]
The above error looks probably like a GNS3 issue with the filesystem.

```
%Error opening disk0:/rr3-confg (Bad service code)
```

**Comment by ktbyers** [comment]
I am going to close as it doesn't look like a napalm issue. If you see more data that indicates this is a napalm issue, just re-open.
