### ISSUE TITLE
Exception not caught "Socket exception: Connection reset by peer (104)"

### ISSUE THREAD

**Issue by TomCos** [napalm-automation/napalm#963]
So been wresting with this one for a while.  Just saw the note in the repo about opening a ticket for exceptions not caught, so figured this would be the best place to start.  My application is fairly large, but the issue is identifiable.

In the app I'm writing, it's for doing network device upgrades.  Regardless of the device, sometimes you'll get a prompt before it reboots, sometimes you wont.  In the cases where you don't get one and the napalm waits out the netmiko delay_factor, we get the following:

Error trying to Napalm disconnect: 'Search pattern never detected in send_command_expect: hostname#' 

The full function is this:
```
def device_disconnect_napalm(ssh_napalm=None, log=None):
    try:
        if ssh_napalm:
            if napalm_is_connected(ssh_napalm=ssh_napalm):
                time.sleep(2)
                ssh_napalm.close()
            ssh_napalm = False
            log.info('Successfully disconnected the Napalm connection.')
    except Exception as e:
        log.warning("Error trying to Napalm disconnect: " + repr(str(e)) + "  This is normally OK on a disconnect during reboot, so just an FYI.")
        log.warning("If a socket exception occurs, also safe to ignore.  For some reason I can't catch it.")
        ssh_napalm = False
        pass
    return (ssh_napalm)
```

You can see my frustration in the log exception (lol)

So, the socket error is (probably) coming from paramiko transport.  That kind of makes sense, seeing that none of the 3 modules below the hood (napalm > netmiko > paramiko) know that the device kicked us yet.  It's normally just this:
Socket exception: Connection reset by peer (104)

I can't catch it though.  It's really odd, it just prints it to the screen (which is annoying when the logger is going, for obvious reasons).  Is this something we just need to add to the base exceptions file?  That's literally the only log I get :(

**Comment by ktbyers** [comment]
Do you have the full stack trace or line number that the exception happens at?

You say it just prints it to the screen--are you sure it isn't being caught by some earlier exception handler that you have that comes before the above code?

**Comment by TomCos** [comment]
The logger is doing all output to the screen in color and also logging to 2 files.  It comes to the screen with no color and doesn't end up in either file.  It's hard to generate, because it basically depends on how the host played with us, but that plain print to the screen is all I got.  More than happy to help generate a traceback, but not sure how I'm going to be able to.  The above code block is where it's happening because the only time I see and exception and generate "If a socket exception occurs, also safe to ignore.  For some reason I can't catch it." is when it shows up.  Would need a recommendation on what else to try, because nothing I've tried has worked.

I imported these to help, but it didn't:
import paramiko.ssh_exception
import netmiko.ssh_exception

**Comment by TomCos** [comment]
This may be related?
https://github.com/paramiko/paramiko/issues/1336

**Comment by TomCos** [comment]
Looks like there are others that I can't catch....
`Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2138, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 563, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2143, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
`

**Comment by sanseihappa** [comment]
Seeing the same.  I'm observing two different failure modes, both during _check_banner: EOFError and ConnectionResetError.

paramiko 2.4.2 on Python 3.7:

`05-Jun-2019 11:24:49	    (Traceback (most recent call last):
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2138, in _check_banner
05-Jun-2019 11:24:49	    buf = self.packetizer.readline(timeout)
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 367, in readline
05-Jun-2019 11:24:49	    buf += self._read_timeout(timeout)
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 563, in _read_timeout
05-Jun-2019 11:24:49	    raise EOFError()
05-Jun-2019 11:24:49	EOFError
05-Jun-2019 11:24:49
05-Jun-2019 11:24:49	During handling of the above exception, another exception occurred:
05-Jun-2019 11:24:49
05-Jun-2019 11:24:49	Traceback (most recent call last):
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 397, in connect
05-Jun-2019 11:24:49	    t.start_client(timeout=timeout)
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 587, in start_client
05-Jun-2019 11:24:49	    raise e
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1966, in run
05-Jun-2019 11:24:49	    self._check_banner()
05-Jun-2019 11:24:49	  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2143, in _check_banner
05-Jun-2019 11:24:49	    "Error reading SSH protocol banner" + str(e)
05-Jun-2019 11:24:49	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`

`2019-06-05 16:02:00,791 DEBUG:paramiko.transport:starting thread (client mode): 0xb4243908
2019-06-05 16:02:00,791 DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
2019-06-05 16:02:00,794 ERROR:paramiko.transport:Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2019-06-05 16:02:00,795 ERROR:paramiko.transport:Traceback (most recent call last):
2019-06-05 16:02:00,795 ERROR:paramiko.transport:  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2138, in _check_banner
2019-06-05 16:02:00,795 ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
2019-06-05 16:02:00,795 ERROR:paramiko.transport:  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 367, in readline
2019-06-05 16:02:00,795 ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
2019-06-05 16:02:00,795 ERROR:paramiko.transport:  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 561, in _read_timeout
2019-06-05 16:02:00,795 ERROR:paramiko.transport:    x = self.__socket.recv(128)
2019-06-05 16:02:00,795 ERROR:paramiko.transport:ConnectionResetError: [Errno 104] Connection reset by peer
2019-06-05 16:02:00,795 ERROR:paramiko.transport:
2019-06-05 16:02:00,795 ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
2019-06-05 16:02:00,795 ERROR:paramiko.transport:
2019-06-05 16:02:00,795 ERROR:paramiko.transport:Traceback (most recent call last):
2019-06-05 16:02:00,795 ERROR:paramiko.transport:  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1966, in run
2019-06-05 16:02:00,795 ERROR:paramiko.transport:    self._check_banner()
2019-06-05 16:02:00,795 ERROR:paramiko.transport:  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2143, in _check_banner
2019-06-05 16:02:00,795 ERROR:paramiko.transport:    "Error reading SSH protocol banner" + str(e)
2019-06-05 16:02:00,795 ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2019-06-05 16:02:00,795 ERROR:paramiko.transport:`

**Comment by sanseihappa** [comment]
Somewhat anecdotal observation: paramiko 2.4.2 with Python 2.7.x, and didn't observe this issue.

**Comment by Vuader** [comment]
@TomCos did you ever find a way to work around the "connection reset by peer" issue?

**Comment by TomCos** [comment]
Nope, never found a solution sadly.  Still happens though, I just added a user log message to ignore it.
