### ISSUE TITLE
Napalm Getter "environment" broken

### ISSUE THREAD

**Issue by LongBeachHXC** [napalm-automation/napalm#977]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

When attempting to retrieve the network device environment using napalm's environment getter the traceback provided below is returned.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.4.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.07.05E RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2017 by Cisco Systems, Inc.
Compiled Fri 10-Feb-17 07:59 by prod_rel_team



Cisco IOS-XE software, Copyright (c) 2005-2015 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.
(http://www.gnu.org/licenses/gpl-2.0.html) For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.



ROM: IOS-XE ROMMON
BOOTLDR: CAT3K_CAA Boot Loader (CAT3K_CAA-HBOOT-M) Version 3.58, RELEASE SOFTWARE (P)

US-TOP-MDF-AS1 uptime is 11 weeks, 6 days, 9 hours, 49 minutes
Uptime for this control processor is 11 weeks, 6 days, 9 hours, 56 minutes
System returned to ROM by SSO Switchover at 06:39:06 PDT Wed Sep 19 2018
System restarted at 22:50:25 PST Mon Feb 11 2019
System image file is "flash:packages.conf"
Last reload reason: Power Failure



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Level: Ipbase
License Type: Permanent
Next reload license Level: Ipbase

cisco WS-C3850-48U (MIPS) processor with 4194304K bytes of physical memory.
Processor board ID FCW2132C0RY
3 Virtual Ethernet interfaces
104 Gigabit Ethernet interfaces
8 Ten Gigabit Ethernet interfaces
2048K bytes of non-volatile configuration memory.
4194304K bytes of physical memory.
250456K bytes of Crash Files at crashinfo:.
252000K bytes of Crash Files at crashinfo-2:.
1609272K bytes of Flash at flash:.
1611414K bytes of Flash at flash-2:.
0K bytes of Dummy USB Flash at usbflash0:.
0K bytes of  at webui:.

Base Ethernet MAC Address          : 
Motherboard Assembly Number        : 
Motherboard Serial Number          : 
Model Revision Number              : 
Motherboard Revision Number        : 
Model Number                       : WS-C3850-48U
System Serial Number               : 


Switch Ports Model              SW Version        SW Image              Mode
------ ----- -----              ----------        ----------            ----
*    1 56    WS-C3850-48U       03.07.05E         cat3k_caa-universalk9 INSTALL
     2 56    WS-C3850-48U       03.07.05E         cat3k_caa-universalk9 INSTALL


Switch 02
---------
Switch uptime                      : 11 weeks, 6 days, 8 hours, 45 minutes
Base Ethernet MAC Address          :
Motherboard Assembly Number        : 
Motherboard Serial Number          : 
Model Revision Number              : 
Motherboard Revision Number        : 
Model Number                       : WS-C3850-48U
System Serial Number               : 

Configuration register is 0x102
```

### Steps to Reproduce the Issue

Initialize nornir and run a Napalm getter task for a devices environment and the following traceback error is provided

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/networking/napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "/usr/local/lib/python3.6/dist-packages/napalm/ios/ios.py", line 1860, in get_environment
    total_mem = int(proc_total_mem) + int(io_total_mem)
UnboundLocalError: local variable 'proc_total_mem' referenced before assignment
```

**Comment by ktbyers** [comment]
Duplicate issue:

https://github.com/napalm-automation/napalm/issues/468
