### ISSUE TITLE
get_interfaces_ip Attribute Error if no IPv6 addresses are present

### ISSUE THREAD

**Issue by robobeaver6** [napalm-automation/napalm#981]
### Description of Issue/Question

Using Nornir the task `task.run(task=napalm_get, getters="get_interfaces_ip")` raises an `AttributeError` because the Napalm function can not handle the None type due to the device not returning any data.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
```
napalm==2.4.0
napalm-asa==0.1.1
nornir==2.1.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

NX-OSv is a demo version of the Nexus Operating System

Software
  loader:    version N/A
  kickstart: version 7.3(0)D1(1)
  system:    version 7.3(0)D1(1)
  kickstart image file is: bootflash:///titanium-d1-kickstart.7.3.0.D1.1.bin
  kickstart compile time:  1/11/2016 16:00:00 [02/11/2016 10:30:12]
  system image file is:    bootflash:///titanium-d1.7.3.0.D1.1.bin
  system compile time:     1/11/2016 16:00:00 [02/11/2016 13:08:11]


Hardware
  cisco NX-OSv Chassis ("NX-OSv Supervisor Module")
  QEMU Virtual CPU version 2.5 with 3064740 kB of memory.
  Processor Board ID TM00000000B

  Device name: loonlab1core1
  bootflash:    3184776 kB

Kernel uptime is 104 day(s), 0 hour(s), 28 minute(s), 14 second(s)


plugin
  Core Plugin, Ethernet Plugin

Active Package(s)
```

### Steps to Reproduce the Issue
Run the nornir command on a device with no IPv6 addresses:  
`task.run(task=napalm_get, getters="get_interfaces_ip")`

If I add an IPv6 address to any interface the command execures correctly.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
2019-05-15 12:02:49,466 [   ERROR]               nornir.core.task: Host 'loonlab1core1.intra.gsacapital.com': task 'Get Interface Info' failed with traceback:
Traceback (most recent call last):
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 61, in napalm_get
    result[g] = method(**options)
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 1091, in get_interfaces_ip
    ipv6_command, "TABLE_intf", "ROW_intf"
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 721, in _get_command_table
    return self._get_reply_table(json_output, table_name, row_name)
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 717, in _get_reply_table
    return self._get_table_rows(result, table_name, row_name)
  File "/home/rhall/.virtualenvs/nornir-netops-6ImgWdqL/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 706, in _get_table_rows
    _table = parent_table.get(table_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ktbyers** [comment]
@carlniger You want to see if you can reproduce this and do a PR on it? This looks like it is NX-API.

**Comment by carlniger** [comment]
@robobeaver6 can you try this with the develop branch please? Pretty sure #969 fixed this (or at least I can confirm it does on N9Kv). I dont have a a 7k/Titanium instance to test against right now but looking at tests and thinking back I think this should work on 7k/Titanium as well.

**Comment by ktbyers** [comment]
Just re-open if not already fixed.
